// Generated by Qleany v1.5.5 from feature_use_case_uow.tera

use crate::use_cases::deactivate_user_uc::{
    DeactivateUserUnitOfWorkFactoryTrait, DeactivateUserUnitOfWorkTrait,
};
use anyhow::{Ok, Result};
use common::database::CommandUnitOfWork;
use common::database::{db_context::DbContext, transactions::Transaction};
#[allow(unused_imports)]
use common::entities::{Session, User};
use common::event::{AllEvent, DirectAccessEntity, Event, EventBuffer, EventHub, Origin};
#[allow(unused_imports)]
use common::types;
#[allow(unused_imports)]
use common::types::EntityId;
use std::cell::RefCell;
use std::sync::Arc;

// Unit of work for DeactivateUser

pub struct DeactivateUserUnitOfWork {
    context: DbContext,
    transaction: Option<Transaction>,
    event_hub: Arc<EventHub>,
    event_buffer: RefCell<EventBuffer>,
}

impl DeactivateUserUnitOfWork {
    pub fn new(db_context: &DbContext, event_hub: &Arc<EventHub>) -> Self {
        DeactivateUserUnitOfWork {
            context: db_context.clone(),
            transaction: None,
            event_hub: event_hub.clone(),
            event_buffer: RefCell::new(EventBuffer::new()),
        }
    }
}

impl CommandUnitOfWork for DeactivateUserUnitOfWork {
    fn begin_transaction(&mut self) -> Result<()> {
        self.transaction = Some(Transaction::begin_write_transaction(&self.context)?);
        self.event_buffer.get_mut().begin_buffering();
        Ok(())
    }

    fn commit(&mut self) -> Result<()> {
        self.transaction
            .take()
            .ok_or_else(|| anyhow::anyhow!("No active transaction"))?
            .commit()?;
        for event in self.event_buffer.get_mut().flush() {
            self.event_hub.send_event(event);
        }
        Ok(())
    }

    fn rollback(&mut self) -> Result<()> {
        self.transaction
            .take()
            .ok_or_else(|| anyhow::anyhow!("No active transaction"))?
            .rollback()?;
        self.event_buffer.get_mut().discard();
        Ok(())
    }

    fn create_savepoint(&self) -> Result<types::Savepoint> {
        self.transaction
            .as_ref()
            .ok_or_else(|| anyhow::anyhow!("No active transaction"))?
            .create_savepoint()
    }

    fn restore_to_savepoint(&mut self, savepoint: types::Savepoint) -> Result<()> {
        let mut transaction = self
            .transaction
            .take()
            .ok_or_else(|| anyhow::anyhow!("No active transaction"))?;
        transaction.restore_to_savepoint(savepoint)?;

        // Discard buffered events — savepoint restore invalidated them
        self.event_buffer.get_mut().discard();

        // Send Reset immediately (not buffered — UI must refresh now)
        self.event_hub.send_event(Event {
            origin: Origin::DirectAccess(DirectAccessEntity::All(AllEvent::Reset)),
            ids: vec![],
            data: None,
        });

        // Recreate the transaction after restoring to savepoint
        self.transaction = Some(transaction);

        Ok(())
    }
}

#[macros::uow_action(entity = "User", action = "Get")]
#[macros::uow_action(entity = "User", action = "GetMulti")]
#[macros::uow_action(entity = "User", action = "Update")]
#[macros::uow_action(entity = "User", action = "UpdateWithRelationships")]
#[macros::uow_action(entity = "User", action = "Snapshot")]
#[macros::uow_action(entity = "User", action = "Restore")]
#[macros::uow_action(entity = "Session", action = "Get")]
#[macros::uow_action(entity = "Session", action = "GetMulti")]
#[macros::uow_action(entity = "Session", action = "Remove")]
#[macros::uow_action(entity = "Session", action = "Snapshot")]
#[macros::uow_action(entity = "Session", action = "Restore")]
impl DeactivateUserUnitOfWorkTrait for DeactivateUserUnitOfWork {}

pub struct DeactivateUserUnitOfWorkFactory {
    context: DbContext,
    event_hub: Arc<EventHub>,
}

impl DeactivateUserUnitOfWorkFactory {
    pub fn new(db_context: &DbContext, event_hub: &Arc<EventHub>) -> Self {
        DeactivateUserUnitOfWorkFactory {
            context: db_context.clone(),
            event_hub: event_hub.clone(),
        }
    }
}

impl DeactivateUserUnitOfWorkFactoryTrait for DeactivateUserUnitOfWorkFactory {
    fn create(&self) -> Box<dyn DeactivateUserUnitOfWorkTrait> {
        Box::new(DeactivateUserUnitOfWork::new(
            &self.context,
            &self.event_hub,
        ))
    }
}
