// Generated by Qleany v1.5.5 from feature_use_case_uow.tera

use crate::use_cases::list_users_uc::{ListUsersUnitOfWorkFactoryTrait, ListUsersUnitOfWorkTrait};
use anyhow::{Ok, Result};
use common::database::QueryUnitOfWork;
use common::database::{db_context::DbContext, transactions::Transaction};
#[allow(unused_imports)]
use common::entities::User;
#[allow(unused_imports)]
use common::types;
#[allow(unused_imports)]
use common::types::EntityId;
use std::cell::RefCell;

// Unit of work for ListUsers

pub struct ListUsersUnitOfWork {
    context: DbContext,
    transaction: RefCell<Option<Transaction>>,
}

impl ListUsersUnitOfWork {
    pub fn new(db_context: &DbContext) -> Self {
        ListUsersUnitOfWork {
            context: db_context.clone(),
            transaction: RefCell::new(None),
        }
    }
}

impl QueryUnitOfWork for ListUsersUnitOfWork {
    fn begin_transaction(&self) -> Result<()> {
        self.transaction
            .replace(Some(Transaction::begin_read_transaction(&self.context)?));
        Ok(())
    }

    fn end_transaction(&self) -> Result<()> {
        self.transaction
            .take()
            .ok_or_else(|| anyhow::anyhow!("No active transaction"))?
            .end_read_transaction()?;
        Ok(())
    }
}

//TODO: adapt entities and actions to real use :
// GetRO, GetMultiRO, GetRelationshipRO, GetRelationshipsFromRightIdsRO
//
// You have here a read-only unit of work.
//
// RO means Read Only, so *RO actions should be used here.
// Do not mix read-only and write actions in the same unit of work.
//
// Exactly the same macros must be set in the use case uow trait file in ../use_cases/list_users_uc.rs
//
// Exactly the same macros must be set in the use case uow trait file in ../use_cases/list_users_uc.rs
#[macros::uow_action(entity = "User", action = "GetRO")]
#[macros::uow_action(entity = "User", action = "GetMultiRO")]
#[macros::uow_action(entity = "User", action = "GetAllRO")]
impl ListUsersUnitOfWorkTrait for ListUsersUnitOfWork {}

pub struct ListUsersUnitOfWorkFactory {
    context: DbContext,
}

impl ListUsersUnitOfWorkFactory {
    pub fn new(db_context: &DbContext) -> Self {
        ListUsersUnitOfWorkFactory {
            context: db_context.clone(),
        }
    }
}

impl ListUsersUnitOfWorkFactoryTrait for ListUsersUnitOfWorkFactory {
    fn create(&self) -> Box<dyn ListUsersUnitOfWorkTrait> {
        Box::new(ListUsersUnitOfWork::new(&self.context))
    }
}
