// Generated by Qleany v1.5.5 from feature_controller.tera

use crate::FindNearestLocationsDto;
use crate::GetLocationInventoryDto;
use crate::LocationInventoryDto;
use crate::NearestLocationsDto;
use crate::units_of_work::find_nearest_locations_uow::FindNearestLocationsUnitOfWorkFactory;
use crate::units_of_work::get_location_inventory_uow::GetLocationInventoryUnitOfWorkFactory;
use crate::use_cases::find_nearest_locations_uc::FindNearestLocationsUseCase;
use crate::use_cases::get_location_inventory_uc::GetLocationInventoryUseCase;
use anyhow::Result;
use common::event::{Event, Origin};

use common::event::LocationManagementEvent::FindNearestLocations;
use common::event::LocationManagementEvent::GetLocationInventory;

use common::{database::db_context::DbContext, event::EventHub};
use std::sync::Arc;

pub fn get_location_inventory(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    dto: &GetLocationInventoryDto,
) -> Result<LocationInventoryDto> {
    let uow_context = GetLocationInventoryUnitOfWorkFactory::new(db_context);
    let mut uc = GetLocationInventoryUseCase::new(Box::new(uow_context));
    let return_dto = uc.execute(dto)?;
    // Notify that the handling manifest has been loaded
    event_hub.send_event(Event {
        origin: Origin::LocationManagement(GetLocationInventory),
        ids: vec![],
        data: None,
    });
    Ok(return_dto)
}

pub fn find_nearest_locations(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    dto: &FindNearestLocationsDto,
) -> Result<NearestLocationsDto> {
    let uow_context = FindNearestLocationsUnitOfWorkFactory::new(db_context);
    let mut uc = FindNearestLocationsUseCase::new(Box::new(uow_context));
    let return_dto = uc.execute(dto)?;
    // Notify that the handling manifest has been loaded
    event_hub.send_event(Event {
        origin: Origin::LocationManagement(FindNearestLocations),
        ids: vec![],
        data: None,
    });
    Ok(return_dto)
}
