// Generated by Qleany v1.5.5 from common_entity_table.tera

use super::session_repository::SessionTable;
use super::session_repository::SessionTableRO;
use crate::database::Postcard;
use crate::database::db_helpers;
use crate::entities::Session;
use crate::error::RepositoryError;
use crate::snapshot::{JunctionSnapshot, TableLevelSnapshot, TableSnapshot};
use crate::types::EntityId;
use redb::{ReadTransaction, ReadableTable, TableDefinition, WriteTransaction};

const SESSION_TABLE: TableDefinition<EntityId, Postcard<Session>> = TableDefinition::new("session");
const COUNTER_TABLE: TableDefinition<String, EntityId> = TableDefinition::new("__counter");
// forward relationships

// backward relationships

const SESSION_FROM_USER_SESSION_JUNCTION_TABLE: TableDefinition<EntityId, Vec<EntityId>> =
    TableDefinition::new("session_from_user_session_junction");

pub struct SessionRedbTable<'a> {
    transaction: &'a WriteTransaction,
}
impl<'a> SessionRedbTable<'a> {
    pub fn new(transaction: &'a WriteTransaction) -> Self {
        SessionRedbTable { transaction }
    }

    pub fn init_tables(transaction: &WriteTransaction) -> Result<(), RepositoryError> {
        transaction.open_table(SESSION_TABLE)?;
        transaction.open_table(COUNTER_TABLE)?;

        transaction.open_table(SESSION_FROM_USER_SESSION_JUNCTION_TABLE)?;
        Ok(())
    }
}

impl<'a> SessionTable for SessionRedbTable<'a> {
    fn create(&mut self, entity: &Session) -> Result<Session, RepositoryError> {
        let v = self.create_multi(std::slice::from_ref(entity))?;
        Ok(v.into_iter().next().unwrap())
    }
    fn get(&self, id: &EntityId) -> Result<Option<Session>, RepositoryError> {
        let v = self.get_multi(std::slice::from_ref(id))?;
        Ok(v.into_iter().next().unwrap())
    }
    fn update(&mut self, entity: &Session) -> Result<Session, RepositoryError> {
        let v = self.update_multi(std::slice::from_ref(entity))?;
        Ok(v.into_iter().next().unwrap())
    }
    fn update_with_relationships(&mut self, entity: &Session) -> Result<Session, RepositoryError> {
        let v = self.update_with_relationships_multi(std::slice::from_ref(entity))?;
        Ok(v.into_iter().next().unwrap())
    }
    fn remove(&mut self, id: &EntityId) -> Result<(), RepositoryError> {
        self.remove_multi(std::slice::from_ref(id))
    }

    fn create_multi(&mut self, entities: &[Session]) -> Result<Vec<Session>, RepositoryError> {
        let mut created = Vec::new();
        let mut counter_table = self.transaction.open_table(COUNTER_TABLE)?;
        let mut counter = if let Some(counter) = counter_table.get(&"session".to_string())? {
            counter.value()
        } else {
            1
        };
        let mut session_table = self.transaction.open_table(SESSION_TABLE)?;

        for entity in entities {
            let new_entity = if entity.id == EntityId::default() {
                Session {
                    id: counter,
                    ..entity.clone()
                }
            } else {
                if session_table.get(&entity.id)?.is_some() {
                    return Err(RepositoryError::DuplicateId {
                        entity: "Session",
                        id: entity.id,
                    });
                }
                entity.clone()
            };

            session_table.insert(new_entity.id, new_entity.clone())?;

            created.push(new_entity);
            if entity.id == EntityId::default() {
                counter += 1;
            }
        }
        counter_table.insert("session".to_string(), counter)?;
        Ok(created)
    }

    fn get_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<Session>>, RepositoryError> {
        if ids.is_empty() {
            return Ok(Vec::new());
        }
        let mut list = Vec::new();
        let session_table = self.transaction.open_table(SESSION_TABLE)?;

        for id in ids {
            let item = if let Some(guard) = session_table.get(id)? {
                let entity = guard.value().clone();
                let mut _junction_complete = true;

                if _junction_complete {
                    Some(entity)
                } else {
                    None
                }
            } else {
                None
            };
            list.push(item);
        }

        Ok(list)
    }

    fn get_all(&self) -> Result<Vec<Session>, RepositoryError> {
        let mut list = Vec::new();
        let session_table = self.transaction.open_table(SESSION_TABLE)?;

        let mut iter = session_table.iter()?;
        while let Some(Ok((id, data))) = iter.next() {
            let _id = id.value();
            let entity = data.value().clone();
            let mut _junction_complete = true;

            if _junction_complete {
                list.push(entity);
            }
        }

        Ok(list)
    }

    // Scalar-only update: writes entity data to the main table but does NOT touch junction tables.
    // The serialized entity may contain stale/default relationship field values in the main table;
    // this is harmless because get_multi() always overlays fresh data from junction tables.
    // Use update_with_relationships_multi() to write both scalars and relationships.
    fn update_multi(&mut self, entities: &[Session]) -> Result<Vec<Session>, RepositoryError> {
        let mut session_table = self.transaction.open_table(SESSION_TABLE)?;
        let ids: Vec<EntityId> = entities.iter().map(|e| e.id).collect();

        for entity in entities {
            session_table.insert(entity.id, entity)?;
        }
        drop(session_table);

        // Re-read entities to populate relationship fields from junction tables
        let result = self.get_multi(&ids)?;
        Ok(result.into_iter().flatten().collect())
    }

    fn update_with_relationships_multi(
        &mut self,
        entities: &[Session],
    ) -> Result<Vec<Session>, RepositoryError> {
        let mut session_table = self.transaction.open_table(SESSION_TABLE)?;

        let ids: Vec<EntityId> = entities.iter().map(|e| e.id).collect();

        for entity in entities {
            session_table.insert(entity.id, entity)?;
        }
        drop(session_table);

        // Re-read entities to populate relationship fields from junction tables
        let result = self.get_multi(&ids)?;
        Ok(result.into_iter().flatten().collect())
    }

    fn remove_multi(&mut self, ids: &[EntityId]) -> Result<(), RepositoryError> {
        let mut session_table = self.transaction.open_table(SESSION_TABLE)?;

        // forward relationships

        // backward relationships

        let mut backward_user_session_junction_table = self
            .transaction
            .open_table(SESSION_FROM_USER_SESSION_JUNCTION_TABLE)?;

        for id in ids {
            session_table.remove(id)?;

            db_helpers::delete_from_backward_junction_table(
                &mut backward_user_session_junction_table,
                id,
            )?;
        }
        Ok(())
    }

    fn snapshot_rows(&self, ids: &[EntityId]) -> Result<TableLevelSnapshot, RepositoryError> {
        let session_table = self.transaction.open_table(SESSION_TABLE)?;

        // Snapshot entity rows as postcard bytes
        let mut rows = Vec::new();
        for id in ids {
            if let Some(guard) = session_table.get(id)? {
                let entity = guard.value();
                let bytes = postcard::to_allocvec(&entity)
                    .map_err(|e| RepositoryError::Serialization(e.to_string()))?;
                rows.push((*id, bytes));
            }
        }

        // Snapshot forward junction tables
        let forward_junctions = Vec::new();

        // Snapshot backward junction tables (entries that reference any of the given ids)
        let mut backward_junctions = Vec::new();

        {
            let junction_table = self
                .transaction
                .open_table(SESSION_FROM_USER_SESSION_JUNCTION_TABLE)?;
            let mut entries = Vec::new();
            let mut iter = junction_table.iter()?;
            while let Some(Ok((left_id_guard, right_ids_guard))) = iter.next() {
                let left_id = left_id_guard.value();
                let right_ids = right_ids_guard.value();
                if ids.iter().any(|id| right_ids.contains(id)) {
                    entries.push((left_id, right_ids));
                }
            }
            if !entries.is_empty() {
                backward_junctions.push(JunctionSnapshot {
                    table_name: "session_from_user_session_junction".to_string(),
                    entries,
                });
            }
        }

        Ok(TableLevelSnapshot {
            entity_rows: TableSnapshot {
                table_name: "session".to_string(),
                rows,
            },
            forward_junctions,
            backward_junctions,
        })
    }

    fn restore_rows(&mut self, snap: &TableLevelSnapshot) -> Result<(), RepositoryError> {
        let mut session_table = self.transaction.open_table(SESSION_TABLE)?;

        // Restore entity rows from postcard bytes (redb insert is upsert)
        for (id, bytes) in &snap.entity_rows.rows {
            let entity: Session = postcard::from_bytes(bytes)
                .map_err(|e| RepositoryError::Serialization(e.to_string()))?;
            session_table.insert(*id, entity)?;
        }

        // Restore forward junction entries

        // Restore backward junction entries

        {
            let mut junction_table = self
                .transaction
                .open_table(SESSION_FROM_USER_SESSION_JUNCTION_TABLE)?;
            for junction_snap in &snap.backward_junctions {
                if junction_snap.table_name == "session_from_user_session_junction" {
                    for (left_id, right_ids) in &junction_snap.entries {
                        junction_table.insert(*left_id, right_ids.clone())?;
                    }
                }
            }
        }

        Ok(())
    }
}

pub struct SessionRedbTableRO<'a> {
    transaction: &'a ReadTransaction,
}
impl<'a> SessionRedbTableRO<'a> {
    pub fn new(transaction: &'a ReadTransaction) -> Self {
        SessionRedbTableRO { transaction }
    }
}

impl<'a> SessionTableRO for SessionRedbTableRO<'a> {
    fn get(&self, id: &EntityId) -> Result<Option<Session>, RepositoryError> {
        let v = self.get_multi(std::slice::from_ref(id))?;
        Ok(v.into_iter().next().unwrap())
    }

    fn get_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<Session>>, RepositoryError> {
        if ids.is_empty() {
            return Ok(Vec::new());
        }
        let mut list = Vec::new();
        let session_table = self.transaction.open_table(SESSION_TABLE)?;

        for id in ids {
            let item = if let Some(guard) = session_table.get(id)? {
                let entity = guard.value().clone();
                let mut _junction_complete = true;

                if _junction_complete {
                    Some(entity)
                } else {
                    None
                }
            } else {
                None
            };
            list.push(item);
        }

        Ok(list)
    }

    fn get_all(&self) -> Result<Vec<Session>, RepositoryError> {
        let mut list = Vec::new();
        let session_table = self.transaction.open_table(SESSION_TABLE)?;

        let mut iter = session_table.iter()?;
        while let Some(Ok((id, data))) = iter.next() {
            let _id = id.value();
            let entity = data.value().clone();
            let mut _junction_complete = true;

            if _junction_complete {
                list.push(entity);
            }
        }

        Ok(list)
    }
}
