// Generated by Qleany v1.5.5 from feature_use_case.tera
use crate::CreatePurchaseDealDto;
use crate::CreatePurchaseDealReturnDto;
use anyhow::{Result, anyhow};
use common::database::CommandUnitOfWork;
use common::entities::{Deal, Person, Product, Root};
use common::types::EntityId;

pub trait CreatePurchaseDealUnitOfWorkFactoryTrait: Send + Sync {
    fn create(&self) -> Box<dyn CreatePurchaseDealUnitOfWorkTrait>;
}

//TODO: adapt entities and actions to real use :
// Create, CreateMulti, Get, GetMulti, Update (scalar-only), UpdateMulti (scalar-only),
// UpdateWithRelationships, UpdateWithRelationshipsMulti,
// Remove, RemoveMulti, GetRelationship, GetRelationshipsFromRightIds,
// SetRelationship, SetRelationshipMulti
//
// You have here a read-write unit of work trait.
//
// RO means Read Only.
// Do not mix read-only and write actions in the same unit of work.
//
// Exactly the same macros must be set in the use case uow trait file in ../units_of_work/create_purchase_deal_uow.rs
//
#[macros::uow_action(entity = "Root", action = "Get")]
#[macros::uow_action(entity = "Root", action = "GetMulti")]
#[macros::uow_action(entity = "Root", action = "Snapshot")]
#[macros::uow_action(entity = "Root", action = "Restore")]
#[macros::uow_action(entity = "Product", action = "Get")]
#[macros::uow_action(entity = "Product", action = "GetMulti")]
#[macros::uow_action(entity = "Product", action = "Snapshot")]
#[macros::uow_action(entity = "Product", action = "Restore")]
#[macros::uow_action(entity = "Person", action = "Get")]
#[macros::uow_action(entity = "Person", action = "GetMulti")]
#[macros::uow_action(entity = "Person", action = "Snapshot")]
#[macros::uow_action(entity = "Person", action = "Restore")]
#[macros::uow_action(entity = "Deal", action = "Get")]
#[macros::uow_action(entity = "Deal", action = "GetMulti")]
#[macros::uow_action(entity = "Deal", action = "Snapshot")]
#[macros::uow_action(entity = "Deal", action = "Restore")]
pub trait CreatePurchaseDealUnitOfWorkTrait: CommandUnitOfWork {}

pub struct CreatePurchaseDealUseCase {
    uow_factory: Box<dyn CreatePurchaseDealUnitOfWorkFactoryTrait>,
}

impl CreatePurchaseDealUseCase {
    pub fn new(uow_factory: Box<dyn CreatePurchaseDealUnitOfWorkFactoryTrait>) -> Self {
        CreatePurchaseDealUseCase { uow_factory }
    }

    pub fn execute(&mut self, dto: &CreatePurchaseDealDto) -> Result<CreatePurchaseDealReturnDto> {
        let mut uow = self.uow_factory.create();
        uow.begin_transaction()?;

        //TODO: CreatePurchaseDealUseCase to be implemented
        unimplemented!("CreatePurchaseDealUseCase unimplemented");
        uow.commit()?;
        //Ok(CreatePurchaseDealReturnDto {
        //
        //})
        // placeholder to allow compilation
        Err(anyhow!("Not implemented"))
    }
}
use common::undo_redo::UndoRedoCommand;
use std::any::Any;
impl UndoRedoCommand for CreatePurchaseDealUseCase {
    fn undo(&mut self) -> Result<()> {
        //TODO: CreatePurchaseDealUseCase  undo to be implemented
        unimplemented!("CreatePurchaseDealUseCase undo unimplemented");

        Ok(())
    }

    fn redo(&mut self) -> Result<()> {
        //TODO: CreatePurchaseDealUseCase  redo to be implemented
        unimplemented!("CreatePurchaseDealUseCase redo unimplemented");

        Ok(())
    }
    fn as_any(&self) -> &dyn Any {
        self
    }
}
