// Generated by Qleany v1.5.5 from feature_use_case.tera
use crate::DealListDto;
use crate::GetDealsBySupplierDto;
use anyhow::{Result, anyhow};
use common::database::QueryUnitOfWork;
use common::entities::{Deal, Person, Product};
use common::types::EntityId;

pub trait GetDealsBySupplierUnitOfWorkFactoryTrait: Send + Sync {
    fn create(&self) -> Box<dyn GetDealsBySupplierUnitOfWorkTrait>;
}

//TODO: adapt entities and actions to real use :
// GetRO, GetMultiRO, GetRelationship, GetRelationshipRO,
// GetRelationshipsFromRightIdsRO
//
// You have here a read-only unit of work trait.
//
// RO means Read Only, so *RO actions should be used here.
// Do not mix read-only and write actions in the same unit of work.
//
// Exactly the same macros must be set in the use case uow trait file in ../units_of_work/get_deals_by_supplier_uow.rs
//
#[macros::uow_action(entity = "Product", action = "GetRO")]
#[macros::uow_action(entity = "Product", action = "GetMultiRO")]
#[macros::uow_action(entity = "Person", action = "GetRO")]
#[macros::uow_action(entity = "Person", action = "GetMultiRO")]
#[macros::uow_action(entity = "Deal", action = "GetRO")]
#[macros::uow_action(entity = "Deal", action = "GetMultiRO")]
pub trait GetDealsBySupplierUnitOfWorkTrait: QueryUnitOfWork {}

pub struct GetDealsBySupplierUseCase {
    uow_factory: Box<dyn GetDealsBySupplierUnitOfWorkFactoryTrait>,
}

impl GetDealsBySupplierUseCase {
    pub fn new(uow_factory: Box<dyn GetDealsBySupplierUnitOfWorkFactoryTrait>) -> Self {
        GetDealsBySupplierUseCase { uow_factory }
    }

    pub fn execute(&mut self, dto: &GetDealsBySupplierDto) -> Result<DealListDto> {
        let mut uow = self.uow_factory.create();
        uow.begin_transaction()?;

        //TODO: GetDealsBySupplierUseCase to be implemented
        unimplemented!("GetDealsBySupplierUseCase unimplemented");
        uow.end_transaction()?;
        //Ok(DealListDto {
        //
        //})
        // placeholder to allow compilation
        Err(anyhow!("Not implemented"))
    }
}
