// Generated by Qleany v1.5.5 from feature_use_case.tera
use crate::ActiveDealsDto;
use anyhow::Result;
use common::database::QueryUnitOfWork;
use common::entities::{Deal, DealStatus, Person, Product};
use common::types::EntityId;

pub trait GetActiveDealsUnitOfWorkFactoryTrait: Send + Sync {
    fn create(&self) -> Box<dyn GetActiveDealsUnitOfWorkTrait>;
}

// Exactly the same macros must be set in the use case uow trait file in ../units_of_work/get_active_deals_uow.rs
#[macros::uow_action(entity = "Product", action = "GetRO")]
#[macros::uow_action(entity = "Product", action = "GetMultiRO")]
#[macros::uow_action(entity = "Person", action = "GetRO")]
#[macros::uow_action(entity = "Person", action = "GetMultiRO")]
#[macros::uow_action(entity = "Deal", action = "GetRO")]
#[macros::uow_action(entity = "Deal", action = "GetMultiRO")]
#[macros::uow_action(entity = "Deal", action = "GetAllRO")]
pub trait GetActiveDealsUnitOfWorkTrait: QueryUnitOfWork {}

pub struct GetActiveDealsUseCase {
    uow_factory: Box<dyn GetActiveDealsUnitOfWorkFactoryTrait>,
}

impl GetActiveDealsUseCase {
    pub fn new(uow_factory: Box<dyn GetActiveDealsUnitOfWorkFactoryTrait>) -> Self {
        GetActiveDealsUseCase { uow_factory }
    }

    pub fn execute(&mut self) -> Result<ActiveDealsDto> {
        let uow = self.uow_factory.create();
        uow.begin_transaction()?;

        // 1. Query all deals and filter by Active status
        let all_deals = uow.get_all_deal()?;
        let active: Vec<&Deal> = all_deals
            .iter()
            .filter(|d| d.status == DealStatus::Active)
            .collect();

        // 2. Build parallel arrays
        let deal_ids: Vec<i64> = active.iter().map(|d| d.id as i64).collect();
        let titles: Vec<String> = active.iter().map(|d| d.title.clone()).collect();
        let statuses: Vec<String> = active.iter().map(|_| "Active".to_string()).collect();

        uow.end_transaction()?;

        Ok(ActiveDealsDto {
            deal_ids,
            titles,
            statuses,
        })
    }
}
