// Generated by Qleany v1.5.5 from feature_use_case.tera
use crate::DealListDto;
use crate::GetDealsBySupplierDto;
use crate::error::PurchasingError;
use anyhow::Result;
use common::database::QueryUnitOfWork;
use common::entities::{Deal, Person, Product};
use common::types::EntityId;

pub trait GetDealsBySupplierUnitOfWorkFactoryTrait: Send + Sync {
    fn create(&self) -> Box<dyn GetDealsBySupplierUnitOfWorkTrait>;
}

// Exactly the same macros must be set in the use case uow trait file in ../units_of_work/get_deals_by_supplier_uow.rs
#[macros::uow_action(entity = "Product", action = "GetRO")]
#[macros::uow_action(entity = "Product", action = "GetMultiRO")]
#[macros::uow_action(entity = "Person", action = "GetRO")]
#[macros::uow_action(entity = "Person", action = "GetMultiRO")]
#[macros::uow_action(entity = "Deal", action = "GetRO")]
#[macros::uow_action(entity = "Deal", action = "GetMultiRO")]
#[macros::uow_action(entity = "Deal", action = "GetAllRO")]
pub trait GetDealsBySupplierUnitOfWorkTrait: QueryUnitOfWork {}

pub struct GetDealsBySupplierUseCase {
    uow_factory: Box<dyn GetDealsBySupplierUnitOfWorkFactoryTrait>,
}

impl GetDealsBySupplierUseCase {
    pub fn new(uow_factory: Box<dyn GetDealsBySupplierUnitOfWorkFactoryTrait>) -> Self {
        GetDealsBySupplierUseCase { uow_factory }
    }

    pub fn execute(&mut self, dto: &GetDealsBySupplierDto) -> Result<DealListDto> {
        let uow = self.uow_factory.create();
        uow.begin_transaction()?;

        // 1. Validate supplier_id references an existing Person
        let supplier = uow.get_person(&(dto.supplier_id as EntityId))?;
        if supplier.is_none() {
            return Err(
                PurchasingError::SupplierNotFound {
                    id: dto.supplier_id,
                }
                .into(),
            );
        }

        // 2. Query all deals and filter by supplier
        let all_deals = uow.get_all_deal()?;
        let matching: Vec<&Deal> = all_deals
            .iter()
            .filter(|d| d.supplier == Some(dto.supplier_id as EntityId))
            .collect();

        // 3. Build parallel arrays
        let deal_ids: Vec<i64> = matching.iter().map(|d| d.id as i64).collect();
        let titles: Vec<String> = matching.iter().map(|d| d.title.clone()).collect();

        uow.end_transaction()?;

        Ok(DealListDto { deal_ids, titles })
    }
}
