// Generated by Qleany v1.5.5 from feature_use_case_uow.tera

use crate::use_cases::get_budget_summary_uc::{
    GetBudgetSummaryUnitOfWorkFactoryTrait, GetBudgetSummaryUnitOfWorkTrait,
};
use anyhow::{Ok, Result};
use common::database::QueryUnitOfWork;
use common::database::{db_context::DbContext, transactions::Transaction};
#[allow(unused_imports)]
use common::entities::BudgetEntry;
#[allow(unused_imports)]
use common::types;
#[allow(unused_imports)]
use common::types::EntityId;
use std::cell::RefCell;

pub struct GetBudgetSummaryUnitOfWork {
    context: DbContext,
    transaction: RefCell<Option<Transaction>>,
}

impl GetBudgetSummaryUnitOfWork {
    pub fn new(db_context: &DbContext) -> Self {
        GetBudgetSummaryUnitOfWork {
            context: db_context.clone(),
            transaction: RefCell::new(None),
        }
    }
}

impl QueryUnitOfWork for GetBudgetSummaryUnitOfWork {
    fn begin_transaction(&self) -> Result<()> {
        self.transaction
            .replace(Some(Transaction::begin_read_transaction(&self.context)?));
        Ok(())
    }

    fn end_transaction(&self) -> Result<()> {
        self.transaction
            .take()
            .ok_or_else(|| anyhow::anyhow!("No active transaction"))?
            .end_read_transaction()?;
        Ok(())
    }
}

// Exactly the same macros as in ../use_cases/get_budget_summary_uc.rs
#[macros::uow_action(entity = "BudgetEntry", action = "GetAllRO")]
impl GetBudgetSummaryUnitOfWorkTrait for GetBudgetSummaryUnitOfWork {}

pub struct GetBudgetSummaryUnitOfWorkFactory {
    context: DbContext,
}

impl GetBudgetSummaryUnitOfWorkFactory {
    pub fn new(db_context: &DbContext) -> Self {
        GetBudgetSummaryUnitOfWorkFactory {
            context: db_context.clone(),
        }
    }
}

impl GetBudgetSummaryUnitOfWorkFactoryTrait for GetBudgetSummaryUnitOfWorkFactory {
    fn create(&self) -> Box<dyn GetBudgetSummaryUnitOfWorkTrait> {
        Box::new(GetBudgetSummaryUnitOfWork::new(&self.context))
    }
}
