// Generated by Qleany v1.5.5 from feature_use_case_uow.tera

use crate::use_cases::get_budget_projection_uc::{
    GetBudgetProjectionUnitOfWorkFactoryTrait, GetBudgetProjectionUnitOfWorkTrait,
};
use anyhow::{Ok, Result};
use common::database::QueryUnitOfWork;
use common::database::{db_context::DbContext, transactions::Transaction};
#[allow(unused_imports)]
use common::entities::{BudgetEntry, Deal};
#[allow(unused_imports)]
use common::types;
#[allow(unused_imports)]
use common::types::EntityId;
use std::cell::RefCell;

pub struct GetBudgetProjectionUnitOfWork {
    context: DbContext,
    transaction: RefCell<Option<Transaction>>,
}

impl GetBudgetProjectionUnitOfWork {
    pub fn new(db_context: &DbContext) -> Self {
        GetBudgetProjectionUnitOfWork {
            context: db_context.clone(),
            transaction: RefCell::new(None),
        }
    }
}

impl QueryUnitOfWork for GetBudgetProjectionUnitOfWork {
    fn begin_transaction(&self) -> Result<()> {
        self.transaction
            .replace(Some(Transaction::begin_read_transaction(&self.context)?));
        Ok(())
    }

    fn end_transaction(&self) -> Result<()> {
        self.transaction
            .take()
            .ok_or_else(|| anyhow::anyhow!("No active transaction"))?
            .end_read_transaction()?;
        Ok(())
    }
}

// Exactly the same macros as in ../use_cases/get_budget_projection_uc.rs
#[macros::uow_action(entity = "BudgetEntry", action = "GetAllRO")]
#[macros::uow_action(entity = "Deal", action = "GetAllRO")]
impl GetBudgetProjectionUnitOfWorkTrait for GetBudgetProjectionUnitOfWork {}

pub struct GetBudgetProjectionUnitOfWorkFactory {
    context: DbContext,
}

impl GetBudgetProjectionUnitOfWorkFactory {
    pub fn new(db_context: &DbContext) -> Self {
        GetBudgetProjectionUnitOfWorkFactory {
            context: db_context.clone(),
        }
    }
}

impl GetBudgetProjectionUnitOfWorkFactoryTrait for GetBudgetProjectionUnitOfWorkFactory {
    fn create(&self) -> Box<dyn GetBudgetProjectionUnitOfWorkTrait> {
        Box::new(GetBudgetProjectionUnitOfWork::new(&self.context))
    }
}
