// Generated by Qleany v1.5.5 from feature_use_case_uow.tera

use crate::use_cases::record_budget_entry_uc::{
    RecordBudgetEntryUnitOfWorkFactoryTrait, RecordBudgetEntryUnitOfWorkTrait,
};
use anyhow::{Ok, Result};
use common::database::CommandUnitOfWork;
use common::database::{db_context::DbContext, transactions::Transaction};
#[allow(unused_imports)]
use common::entities::{BudgetEntry, Deal, Product, Root};
use common::event::{AllEvent, DirectAccessEntity, Event, EventBuffer, EventHub, Origin};
#[allow(unused_imports)]
use common::types;
#[allow(unused_imports)]
use common::types::EntityId;
use std::cell::RefCell;
use std::sync::Arc;

pub struct RecordBudgetEntryUnitOfWork {
    context: DbContext,
    transaction: Option<Transaction>,
    event_hub: Arc<EventHub>,
    event_buffer: RefCell<EventBuffer>,
}

impl RecordBudgetEntryUnitOfWork {
    pub fn new(db_context: &DbContext, event_hub: &Arc<EventHub>) -> Self {
        RecordBudgetEntryUnitOfWork {
            context: db_context.clone(),
            transaction: None,
            event_hub: event_hub.clone(),
            event_buffer: RefCell::new(EventBuffer::new()),
        }
    }
}

impl CommandUnitOfWork for RecordBudgetEntryUnitOfWork {
    fn begin_transaction(&mut self) -> Result<()> {
        self.transaction = Some(Transaction::begin_write_transaction(&self.context)?);
        self.event_buffer.get_mut().begin_buffering();
        Ok(())
    }

    fn commit(&mut self) -> Result<()> {
        self.transaction
            .take()
            .ok_or_else(|| anyhow::anyhow!("No active transaction"))?
            .commit()?;
        for event in self.event_buffer.get_mut().flush() {
            self.event_hub.send_event(event);
        }
        Ok(())
    }

    fn rollback(&mut self) -> Result<()> {
        self.transaction
            .take()
            .ok_or_else(|| anyhow::anyhow!("No active transaction"))?
            .rollback()?;
        self.event_buffer.get_mut().discard();
        Ok(())
    }

    fn create_savepoint(&self) -> Result<types::Savepoint> {
        self.transaction
            .as_ref()
            .ok_or_else(|| anyhow::anyhow!("No active transaction"))?
            .create_savepoint()
    }

    fn restore_to_savepoint(&mut self, savepoint: types::Savepoint) -> Result<()> {
        let mut transaction = self
            .transaction
            .take()
            .ok_or_else(|| anyhow::anyhow!("No active transaction"))?;
        transaction.restore_to_savepoint(savepoint)?;

        self.event_buffer.get_mut().discard();

        self.event_hub.send_event(Event {
            origin: Origin::DirectAccess(DirectAccessEntity::All(AllEvent::Reset)),
            ids: vec![],
            data: None,
        });

        self.transaction = Some(transaction);

        Ok(())
    }
}

// Exactly the same macros as in ../use_cases/record_budget_entry_uc.rs
#[macros::uow_action(entity = "Root", action = "Get")]
#[macros::uow_action(entity = "BudgetEntry", action = "Create")]
#[macros::uow_action(entity = "BudgetEntry", action = "Snapshot")]
#[macros::uow_action(entity = "BudgetEntry", action = "Restore")]
#[macros::uow_action(entity = "Product", action = "Get")]
#[macros::uow_action(entity = "Deal", action = "Get")]
impl RecordBudgetEntryUnitOfWorkTrait for RecordBudgetEntryUnitOfWork {}

pub struct RecordBudgetEntryUnitOfWorkFactory {
    context: DbContext,
    event_hub: Arc<EventHub>,
}

impl RecordBudgetEntryUnitOfWorkFactory {
    pub fn new(db_context: &DbContext, event_hub: &Arc<EventHub>) -> Self {
        RecordBudgetEntryUnitOfWorkFactory {
            context: db_context.clone(),
            event_hub: event_hub.clone(),
        }
    }
}

impl RecordBudgetEntryUnitOfWorkFactoryTrait for RecordBudgetEntryUnitOfWorkFactory {
    fn create(&self) -> Box<dyn RecordBudgetEntryUnitOfWorkTrait> {
        Box::new(RecordBudgetEntryUnitOfWork::new(
            &self.context,
            &self.event_hub,
        ))
    }
}
