// Generated by Qleany v1.5.5 from feature_use_case.tera
use crate::RecordBudgetEntryDto;
use crate::RecordBudgetEntryResultDto;
use crate::dtos::BudgetEntryTypeInput;
use crate::error::BudgetError;
use crate::validate::{validate_deal, validate_entry_input, validate_product};
use anyhow::Result;
use common::database::CommandUnitOfWork;
use common::entities::{BudgetEntry, BudgetEntryType, Deal, Product, Root};
use common::snapshot::EntityTreeSnapshot;
use common::types::EntityId;
use inventory_security::SecurityContext;
use inventory_security_macros::check_permission;

pub trait RecordBudgetEntryUnitOfWorkFactoryTrait: Send + Sync {
    fn create(&self) -> Box<dyn RecordBudgetEntryUnitOfWorkTrait>;
}

// Exactly the same macros must be set in ../units_of_work/record_budget_entry_uow.rs
#[macros::uow_action(entity = "Root", action = "Get")]
#[macros::uow_action(entity = "BudgetEntry", action = "Create")]
#[macros::uow_action(entity = "BudgetEntry", action = "Snapshot")]
#[macros::uow_action(entity = "BudgetEntry", action = "Restore")]
#[macros::uow_action(entity = "Product", action = "Get")]
#[macros::uow_action(entity = "Deal", action = "Get")]
pub trait RecordBudgetEntryUnitOfWorkTrait: CommandUnitOfWork {}

fn to_entry_type(input: &BudgetEntryTypeInput) -> BudgetEntryType {
    match input {
        BudgetEntryTypeInput::Purchase => BudgetEntryType::Purchase,
        BudgetEntryTypeInput::Sale => BudgetEntryType::Sale,
        BudgetEntryTypeInput::Expense => BudgetEntryType::Expense,
        BudgetEntryTypeInput::Forecast => BudgetEntryType::Forecast,
    }
}

pub struct RecordBudgetEntryUseCase {
    uow_factory: Box<dyn RecordBudgetEntryUnitOfWorkFactoryTrait>,
    /// Snapshot taken before creation, used for undo.
    pre_snapshot: Option<EntityTreeSnapshot>,
    /// The DTO used for redo.
    saved_dto: Option<RecordBudgetEntryDto>,
    /// The security context user_id for redo.
    saved_user_id: Option<u64>,
    /// The created entry id, used for undo snapshot targeting.
    created_entry_id: Option<EntityId>,
}

impl RecordBudgetEntryUseCase {
    pub fn new(uow_factory: Box<dyn RecordBudgetEntryUnitOfWorkFactoryTrait>) -> Self {
        RecordBudgetEntryUseCase {
            uow_factory,
            pre_snapshot: None,
            saved_dto: None,
            saved_user_id: None,
            created_entry_id: None,
        }
    }

    pub fn execute(
        &mut self,
        dto: &RecordBudgetEntryDto,
        security_context: &SecurityContext,
    ) -> Result<RecordBudgetEntryResultDto> {
        // RBAC check: requires budget:* permission (Admin, Manager)
        check_permission(security_context, "budget:*")?;

        // 1. Validate input fields
        validate_entry_input(dto.amount, &dto.description)?;

        let mut uow = self.uow_factory.create();
        uow.begin_transaction()?;

        // 2. Validate product_id (0 = absent, non-zero must exist)
        let product_ref = validate_product(dto.product_id, |id| uow.get_product(id))?;

        // 3. Validate deal_id (0 = absent, non-zero must exist)
        let deal_ref = validate_deal(dto.deal_id, |id| uow.get_deal(id))?;

        // 4. Snapshot for undo support — take savepoint before creation
        let _savepoint = uow.create_savepoint()?;

        // 5. Get root entity for ownership
        let root = uow
            .get_root(&1)?
            .ok_or_else(|| BudgetError::Internal("Root entity not found".into()))?;

        // 6. Create BudgetEntry entity
        let entry = BudgetEntry {
            id: 0,
            entry_type: to_entry_type(&dto.entry_type),
            amount: dto.amount,
            description: dto.description.clone(),
            entry_date: dto.entry_date,
            product: product_ref,
            deal: deal_ref,
            recorded_by: Some(security_context.user_id),
            ..Default::default()
        };
        let created = uow.create_budget_entry(&entry, root.id, -1)?;

        // Store snapshot of the created entry for undo
        self.pre_snapshot = Some(uow.snapshot_budget_entry(&[created.id])?);
        self.saved_dto = Some(dto.clone());
        self.saved_user_id = Some(security_context.user_id);
        self.created_entry_id = Some(created.id);

        uow.commit()?;

        Ok(RecordBudgetEntryResultDto {
            entry_id: created.id as i64,
        })
    }
}

use common::undo_redo::UndoRedoCommand;
use std::any::Any;

impl UndoRedoCommand for RecordBudgetEntryUseCase {
    fn undo(&mut self) -> Result<()> {
        // Restore the snapshot taken after creation — this effectively
        // removes the created entry by restoring the pre-creation state.
        // We use the savepoint/restore approach: snapshot the created entry,
        // then on undo we restore from that snapshot (which removes it).
        let mut uow = self.uow_factory.create();
        uow.begin_transaction()?;

        if let Some(ref snapshot) = self.pre_snapshot {
            // Restore removes the entry that was snapshotted
            uow.restore_budget_entry(snapshot)?;
        }

        uow.commit()?;
        Ok(())
    }

    fn redo(&mut self) -> Result<()> {
        // Re-create the entry using the saved DTO
        if let (Some(dto), Some(user_id)) = (&self.saved_dto, self.saved_user_id) {
            let mut uow = self.uow_factory.create();
            uow.begin_transaction()?;

            let root = uow
                .get_root(&1)?
                .ok_or_else(|| anyhow::anyhow!("Root entity not found"))?;

            let product_ref = if dto.product_id == 0 {
                None
            } else {
                Some(dto.product_id as EntityId)
            };
            let deal_ref = if dto.deal_id == 0 {
                None
            } else {
                Some(dto.deal_id as EntityId)
            };

            let entry = BudgetEntry {
                id: 0,
                entry_type: to_entry_type(&dto.entry_type),
                amount: dto.amount,
                description: dto.description.clone(),
                entry_date: dto.entry_date,
                product: product_ref,
                deal: deal_ref,
                recorded_by: Some(user_id),
                ..Default::default()
            };
            let created = uow.create_budget_entry(&entry, root.id, -1)?;

            self.pre_snapshot = Some(uow.snapshot_budget_entry(&[created.id])?);
            self.created_entry_id = Some(created.id);

            uow.commit()?;
        }
        Ok(())
    }

    fn as_any(&self) -> &dyn Any {
        self
    }
}
