// Generated by Qleany v1.5.5 from feature_use_case.tera
use crate::RecordBudgetEntryDto;
use crate::RecordBudgetEntryResultDto;
use anyhow::{Result, anyhow};
use common::database::CommandUnitOfWork;
use common::entities::{BudgetEntry, Deal, Product, Root, User};
use common::types::EntityId;

pub trait RecordBudgetEntryUnitOfWorkFactoryTrait: Send + Sync {
    fn create(&self) -> Box<dyn RecordBudgetEntryUnitOfWorkTrait>;
}

//TODO: adapt entities and actions to real use :
// Create, CreateMulti, Get, GetMulti, Update (scalar-only), UpdateMulti (scalar-only),
// UpdateWithRelationships, UpdateWithRelationshipsMulti,
// Remove, RemoveMulti, GetRelationship, GetRelationshipsFromRightIds,
// SetRelationship, SetRelationshipMulti
//
// You have here a read-write unit of work trait.
//
// RO means Read Only.
// Do not mix read-only and write actions in the same unit of work.
//
// Exactly the same macros must be set in the use case uow trait file in ../units_of_work/record_budget_entry_uow.rs
//
#[macros::uow_action(entity = "Root", action = "Get")]
#[macros::uow_action(entity = "Root", action = "GetMulti")]
#[macros::uow_action(entity = "Root", action = "Snapshot")]
#[macros::uow_action(entity = "Root", action = "Restore")]
#[macros::uow_action(entity = "User", action = "Get")]
#[macros::uow_action(entity = "User", action = "GetMulti")]
#[macros::uow_action(entity = "User", action = "Snapshot")]
#[macros::uow_action(entity = "User", action = "Restore")]
#[macros::uow_action(entity = "BudgetEntry", action = "Get")]
#[macros::uow_action(entity = "BudgetEntry", action = "GetMulti")]
#[macros::uow_action(entity = "BudgetEntry", action = "Snapshot")]
#[macros::uow_action(entity = "BudgetEntry", action = "Restore")]
#[macros::uow_action(entity = "Product", action = "Get")]
#[macros::uow_action(entity = "Product", action = "GetMulti")]
#[macros::uow_action(entity = "Product", action = "Snapshot")]
#[macros::uow_action(entity = "Product", action = "Restore")]
#[macros::uow_action(entity = "Deal", action = "Get")]
#[macros::uow_action(entity = "Deal", action = "GetMulti")]
#[macros::uow_action(entity = "Deal", action = "Snapshot")]
#[macros::uow_action(entity = "Deal", action = "Restore")]
pub trait RecordBudgetEntryUnitOfWorkTrait: CommandUnitOfWork {}

pub struct RecordBudgetEntryUseCase {
    uow_factory: Box<dyn RecordBudgetEntryUnitOfWorkFactoryTrait>,
}

impl RecordBudgetEntryUseCase {
    pub fn new(uow_factory: Box<dyn RecordBudgetEntryUnitOfWorkFactoryTrait>) -> Self {
        RecordBudgetEntryUseCase { uow_factory }
    }

    pub fn execute(&mut self, dto: &RecordBudgetEntryDto) -> Result<RecordBudgetEntryResultDto> {
        let mut uow = self.uow_factory.create();
        uow.begin_transaction()?;

        //TODO: RecordBudgetEntryUseCase to be implemented
        unimplemented!("RecordBudgetEntryUseCase unimplemented");
        uow.commit()?;
        //Ok(RecordBudgetEntryResultDto {
        //
        //})
        // placeholder to allow compilation
        Err(anyhow!("Not implemented"))
    }
}
use common::undo_redo::UndoRedoCommand;
use std::any::Any;
impl UndoRedoCommand for RecordBudgetEntryUseCase {
    fn undo(&mut self) -> Result<()> {
        //TODO: RecordBudgetEntryUseCase  undo to be implemented
        unimplemented!("RecordBudgetEntryUseCase undo unimplemented");

        Ok(())
    }

    fn redo(&mut self) -> Result<()> {
        //TODO: RecordBudgetEntryUseCase  redo to be implemented
        unimplemented!("RecordBudgetEntryUseCase redo unimplemented");

        Ok(())
    }
    fn as_any(&self) -> &dyn Any {
        self
    }
}
