// Generated by Qleany v1.5.5 from common_entity_table.tera

use super::stock_movement_repository::StockMovementRelationshipField;
use super::stock_movement_repository::StockMovementTable;
use super::stock_movement_repository::StockMovementTableRO;
use crate::database::Postcard;
use crate::database::db_helpers;
use crate::entities::StockMovement;
use crate::error::RepositoryError;
use crate::snapshot::{JunctionSnapshot, TableLevelSnapshot, TableSnapshot};
use crate::types::EntityId;
use redb::{ReadTransaction, ReadableTable, TableDefinition, WriteTransaction};

const STOCK_MOVEMENT_TABLE: TableDefinition<EntityId, Postcard<StockMovement>> =
    TableDefinition::new("stock_movement");
const COUNTER_TABLE: TableDefinition<String, EntityId> = TableDefinition::new("__counter");
// forward relationships

const LOCATION_FROM_STOCK_MOVEMENT_FROM_LOCATION_JUNCTION_TABLE: TableDefinition<
    EntityId,
    Vec<EntityId>,
> = TableDefinition::new("location_from_stock_movement_from_location_junction");
const USER_FROM_STOCK_MOVEMENT_PERFORMED_BY_JUNCTION_TABLE: TableDefinition<
    EntityId,
    Vec<EntityId>,
> = TableDefinition::new("user_from_stock_movement_performed_by_junction");
const PRODUCT_FROM_STOCK_MOVEMENT_PRODUCT_JUNCTION_TABLE: TableDefinition<EntityId, Vec<EntityId>> =
    TableDefinition::new("product_from_stock_movement_product_junction");
const LOCATION_FROM_STOCK_MOVEMENT_TO_LOCATION_JUNCTION_TABLE: TableDefinition<
    EntityId,
    Vec<EntityId>,
> = TableDefinition::new("location_from_stock_movement_to_location_junction");
// backward relationships

const STOCK_MOVEMENT_FROM_ROOT_STOCK_MOVEMENTS_JUNCTION_TABLE: TableDefinition<
    EntityId,
    Vec<EntityId>,
> = TableDefinition::new("stock_movement_from_root_stock_movements_junction");
fn get_junction_table_definition(
    field: &'_ StockMovementRelationshipField,
) -> TableDefinition<'_, EntityId, Vec<EntityId>> {
    match field {
        StockMovementRelationshipField::FromLocation => {
            LOCATION_FROM_STOCK_MOVEMENT_FROM_LOCATION_JUNCTION_TABLE
        }
        StockMovementRelationshipField::PerformedBy => {
            USER_FROM_STOCK_MOVEMENT_PERFORMED_BY_JUNCTION_TABLE
        }
        StockMovementRelationshipField::Product => {
            PRODUCT_FROM_STOCK_MOVEMENT_PRODUCT_JUNCTION_TABLE
        }
        StockMovementRelationshipField::ToLocation => {
            LOCATION_FROM_STOCK_MOVEMENT_TO_LOCATION_JUNCTION_TABLE
        }
    }
}

pub struct StockMovementRedbTable<'a> {
    transaction: &'a WriteTransaction,
}
impl<'a> StockMovementRedbTable<'a> {
    pub fn new(transaction: &'a WriteTransaction) -> Self {
        StockMovementRedbTable { transaction }
    }

    pub fn init_tables(transaction: &WriteTransaction) -> Result<(), RepositoryError> {
        transaction.open_table(STOCK_MOVEMENT_TABLE)?;
        transaction.open_table(COUNTER_TABLE)?;

        transaction.open_table(LOCATION_FROM_STOCK_MOVEMENT_FROM_LOCATION_JUNCTION_TABLE)?;
        transaction.open_table(USER_FROM_STOCK_MOVEMENT_PERFORMED_BY_JUNCTION_TABLE)?;
        transaction.open_table(PRODUCT_FROM_STOCK_MOVEMENT_PRODUCT_JUNCTION_TABLE)?;
        transaction.open_table(LOCATION_FROM_STOCK_MOVEMENT_TO_LOCATION_JUNCTION_TABLE)?;

        transaction.open_table(STOCK_MOVEMENT_FROM_ROOT_STOCK_MOVEMENTS_JUNCTION_TABLE)?;
        Ok(())
    }
}

impl<'a> StockMovementTable for StockMovementRedbTable<'a> {
    fn create(&mut self, entity: &StockMovement) -> Result<StockMovement, RepositoryError> {
        let v = self.create_multi(std::slice::from_ref(entity))?;
        Ok(v.into_iter().next().unwrap())
    }
    fn get(&self, id: &EntityId) -> Result<Option<StockMovement>, RepositoryError> {
        let v = self.get_multi(std::slice::from_ref(id))?;
        Ok(v.into_iter().next().unwrap())
    }
    fn update(&mut self, entity: &StockMovement) -> Result<StockMovement, RepositoryError> {
        let v = self.update_multi(std::slice::from_ref(entity))?;
        Ok(v.into_iter().next().unwrap())
    }
    fn update_with_relationships(
        &mut self,
        entity: &StockMovement,
    ) -> Result<StockMovement, RepositoryError> {
        let v = self.update_with_relationships_multi(std::slice::from_ref(entity))?;
        Ok(v.into_iter().next().unwrap())
    }
    fn remove(&mut self, id: &EntityId) -> Result<(), RepositoryError> {
        self.remove_multi(std::slice::from_ref(id))
    }

    fn create_multi(
        &mut self,
        entities: &[StockMovement],
    ) -> Result<Vec<StockMovement>, RepositoryError> {
        let mut created = Vec::new();
        let mut counter_table = self.transaction.open_table(COUNTER_TABLE)?;
        let mut counter = if let Some(counter) = counter_table.get(&"stock_movement".to_string())? {
            counter.value()
        } else {
            1
        };
        let mut stock_movement_table = self.transaction.open_table(STOCK_MOVEMENT_TABLE)?;

        let mut from_location_junction_table = self
            .transaction
            .open_table(LOCATION_FROM_STOCK_MOVEMENT_FROM_LOCATION_JUNCTION_TABLE)?;
        let mut performed_by_junction_table = self
            .transaction
            .open_table(USER_FROM_STOCK_MOVEMENT_PERFORMED_BY_JUNCTION_TABLE)?;
        let mut product_junction_table = self
            .transaction
            .open_table(PRODUCT_FROM_STOCK_MOVEMENT_PRODUCT_JUNCTION_TABLE)?;
        let mut to_location_junction_table = self
            .transaction
            .open_table(LOCATION_FROM_STOCK_MOVEMENT_TO_LOCATION_JUNCTION_TABLE)?;

        for entity in entities {
            let new_entity = if entity.id == EntityId::default() {
                StockMovement {
                    id: counter,
                    ..entity.clone()
                }
            } else {
                if stock_movement_table.get(&entity.id)?.is_some() {
                    return Err(RepositoryError::DuplicateId {
                        entity: "StockMovement",
                        id: entity.id,
                    });
                }
                entity.clone()
            };

            stock_movement_table.insert(new_entity.id, new_entity.clone())?;

            from_location_junction_table.insert(
                new_entity.id,
                new_entity
                    .from_location
                    .into_iter()
                    .collect::<Vec<EntityId>>(),
            )?;
            performed_by_junction_table.insert(
                new_entity.id,
                new_entity
                    .performed_by
                    .into_iter()
                    .collect::<Vec<EntityId>>(),
            )?;
            product_junction_table.insert(
                new_entity.id,
                new_entity.product.into_iter().collect::<Vec<EntityId>>(),
            )?;
            to_location_junction_table.insert(
                new_entity.id,
                new_entity
                    .to_location
                    .into_iter()
                    .collect::<Vec<EntityId>>(),
            )?;
            created.push(new_entity);
            if entity.id == EntityId::default() {
                counter += 1;
            }
        }
        counter_table.insert("stock_movement".to_string(), counter)?;
        Ok(created)
    }

    fn get_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<StockMovement>>, RepositoryError> {
        if ids.is_empty() {
            return Ok(Vec::new());
        }
        let mut list = Vec::new();
        let stock_movement_table = self.transaction.open_table(STOCK_MOVEMENT_TABLE)?;

        let from_location_junction_table = self
            .transaction
            .open_table(LOCATION_FROM_STOCK_MOVEMENT_FROM_LOCATION_JUNCTION_TABLE)?;
        let performed_by_junction_table = self
            .transaction
            .open_table(USER_FROM_STOCK_MOVEMENT_PERFORMED_BY_JUNCTION_TABLE)?;
        let product_junction_table = self
            .transaction
            .open_table(PRODUCT_FROM_STOCK_MOVEMENT_PRODUCT_JUNCTION_TABLE)?;
        let to_location_junction_table = self
            .transaction
            .open_table(LOCATION_FROM_STOCK_MOVEMENT_TO_LOCATION_JUNCTION_TABLE)?;

        for id in ids {
            let item = if let Some(guard) = stock_movement_table.get(id)? {
                let mut entity = guard.value().clone();
                let mut _junction_complete = true;

                // get product from junction table
                let fetched_product: Option<EntityId> = product_junction_table
                    .get(id)?
                    .map(|g| g.value().clone())
                    .unwrap_or_default()
                    .pop();
                entity.product = fetched_product;
                // get from_location from junction table
                let fetched_from_location: Option<EntityId> = from_location_junction_table
                    .get(id)?
                    .map(|g| g.value().clone())
                    .unwrap_or_default()
                    .pop();
                entity.from_location = fetched_from_location;
                // get to_location from junction table
                let fetched_to_location: Option<EntityId> = to_location_junction_table
                    .get(id)?
                    .map(|g| g.value().clone())
                    .unwrap_or_default()
                    .pop();
                entity.to_location = fetched_to_location;
                // get performed_by from junction table
                let fetched_performed_by: Option<EntityId> = performed_by_junction_table
                    .get(id)?
                    .map(|g| g.value().clone())
                    .unwrap_or_default()
                    .pop();
                entity.performed_by = fetched_performed_by;
                if _junction_complete {
                    Some(entity)
                } else {
                    None
                }
            } else {
                None
            };
            list.push(item);
        }

        Ok(list)
    }

    fn get_all(&self) -> Result<Vec<StockMovement>, RepositoryError> {
        let mut list = Vec::new();
        let stock_movement_table = self.transaction.open_table(STOCK_MOVEMENT_TABLE)?;

        let from_location_junction_table = self
            .transaction
            .open_table(LOCATION_FROM_STOCK_MOVEMENT_FROM_LOCATION_JUNCTION_TABLE)?;
        let performed_by_junction_table = self
            .transaction
            .open_table(USER_FROM_STOCK_MOVEMENT_PERFORMED_BY_JUNCTION_TABLE)?;
        let product_junction_table = self
            .transaction
            .open_table(PRODUCT_FROM_STOCK_MOVEMENT_PRODUCT_JUNCTION_TABLE)?;
        let to_location_junction_table = self
            .transaction
            .open_table(LOCATION_FROM_STOCK_MOVEMENT_TO_LOCATION_JUNCTION_TABLE)?;

        let mut iter = stock_movement_table.iter()?;
        while let Some(Ok((id, data))) = iter.next() {
            let id = id.value();
            let mut entity = data.value().clone();
            let mut _junction_complete = true;

            // get product from junction table
            let fetched_product: Option<EntityId> = product_junction_table
                .get(&id)?
                .map(|g| g.value().clone())
                .unwrap_or_default()
                .pop();
            entity.product = fetched_product;
            // get from_location from junction table
            let fetched_from_location: Option<EntityId> = from_location_junction_table
                .get(&id)?
                .map(|g| g.value().clone())
                .unwrap_or_default()
                .pop();
            entity.from_location = fetched_from_location;
            // get to_location from junction table
            let fetched_to_location: Option<EntityId> = to_location_junction_table
                .get(&id)?
                .map(|g| g.value().clone())
                .unwrap_or_default()
                .pop();
            entity.to_location = fetched_to_location;
            // get performed_by from junction table
            let fetched_performed_by: Option<EntityId> = performed_by_junction_table
                .get(&id)?
                .map(|g| g.value().clone())
                .unwrap_or_default()
                .pop();
            entity.performed_by = fetched_performed_by;

            if _junction_complete {
                list.push(entity);
            }
        }

        Ok(list)
    }

    // Scalar-only update: writes entity data to the main table but does NOT touch junction tables.
    // The serialized entity may contain stale/default relationship field values in the main table;
    // this is harmless because get_multi() always overlays fresh data from junction tables.
    // Use update_with_relationships_multi() to write both scalars and relationships.
    fn update_multi(
        &mut self,
        entities: &[StockMovement],
    ) -> Result<Vec<StockMovement>, RepositoryError> {
        let mut stock_movement_table = self.transaction.open_table(STOCK_MOVEMENT_TABLE)?;
        let ids: Vec<EntityId> = entities.iter().map(|e| e.id).collect();

        for entity in entities {
            stock_movement_table.insert(entity.id, entity)?;
        }
        drop(stock_movement_table);

        // Re-read entities to populate relationship fields from junction tables
        let result = self.get_multi(&ids)?;
        Ok(result.into_iter().flatten().collect())
    }

    fn update_with_relationships_multi(
        &mut self,
        entities: &[StockMovement],
    ) -> Result<Vec<StockMovement>, RepositoryError> {
        let mut stock_movement_table = self.transaction.open_table(STOCK_MOVEMENT_TABLE)?;

        let mut from_location_junction_table = self
            .transaction
            .open_table(LOCATION_FROM_STOCK_MOVEMENT_FROM_LOCATION_JUNCTION_TABLE)?;
        let mut performed_by_junction_table = self
            .transaction
            .open_table(USER_FROM_STOCK_MOVEMENT_PERFORMED_BY_JUNCTION_TABLE)?;
        let mut product_junction_table = self
            .transaction
            .open_table(PRODUCT_FROM_STOCK_MOVEMENT_PRODUCT_JUNCTION_TABLE)?;
        let mut to_location_junction_table = self
            .transaction
            .open_table(LOCATION_FROM_STOCK_MOVEMENT_TO_LOCATION_JUNCTION_TABLE)?;
        let ids: Vec<EntityId> = entities.iter().map(|e| e.id).collect();

        for entity in entities {
            stock_movement_table.insert(entity.id, entity)?;

            product_junction_table.insert(
                entity.id,
                entity.product.into_iter().collect::<Vec<EntityId>>(),
            )?;
            from_location_junction_table.insert(
                entity.id,
                entity.from_location.into_iter().collect::<Vec<EntityId>>(),
            )?;
            to_location_junction_table.insert(
                entity.id,
                entity.to_location.into_iter().collect::<Vec<EntityId>>(),
            )?;
            performed_by_junction_table.insert(
                entity.id,
                entity.performed_by.into_iter().collect::<Vec<EntityId>>(),
            )?;
        }
        drop(stock_movement_table);
        drop(from_location_junction_table);
        drop(performed_by_junction_table);
        drop(product_junction_table);
        drop(to_location_junction_table);

        // Re-read entities to populate relationship fields from junction tables
        let result = self.get_multi(&ids)?;
        Ok(result.into_iter().flatten().collect())
    }

    fn remove_multi(&mut self, ids: &[EntityId]) -> Result<(), RepositoryError> {
        let mut stock_movement_table = self.transaction.open_table(STOCK_MOVEMENT_TABLE)?;

        // forward relationships

        let mut from_location_junction_table = self
            .transaction
            .open_table(LOCATION_FROM_STOCK_MOVEMENT_FROM_LOCATION_JUNCTION_TABLE)?;
        let mut performed_by_junction_table = self
            .transaction
            .open_table(USER_FROM_STOCK_MOVEMENT_PERFORMED_BY_JUNCTION_TABLE)?;
        let mut product_junction_table = self
            .transaction
            .open_table(PRODUCT_FROM_STOCK_MOVEMENT_PRODUCT_JUNCTION_TABLE)?;
        let mut to_location_junction_table = self
            .transaction
            .open_table(LOCATION_FROM_STOCK_MOVEMENT_TO_LOCATION_JUNCTION_TABLE)?;

        // backward relationships

        let mut backward_root_stock_movements_junction_table = self
            .transaction
            .open_table(STOCK_MOVEMENT_FROM_ROOT_STOCK_MOVEMENTS_JUNCTION_TABLE)?;

        for id in ids {
            stock_movement_table.remove(id)?;

            product_junction_table.remove(id)?;
            from_location_junction_table.remove(id)?;
            to_location_junction_table.remove(id)?;
            performed_by_junction_table.remove(id)?;

            db_helpers::delete_from_backward_junction_table(
                &mut backward_root_stock_movements_junction_table,
                id,
            )?;
        }
        Ok(())
    }
    fn get_relationship(
        &self,
        id: &EntityId,
        field: &StockMovementRelationshipField,
    ) -> Result<Vec<EntityId>, RepositoryError> {
        let table = self
            .transaction
            .open_table(get_junction_table_definition(field))?;
        let guard = table.get(id)?;
        Ok(guard.map(|g| g.value().clone()).unwrap_or_default())
    }

    fn get_relationship_many(
        &self,
        ids: &[EntityId],
        field: &StockMovementRelationshipField,
    ) -> Result<std::collections::HashMap<EntityId, Vec<EntityId>>, RepositoryError> {
        let table = self
            .transaction
            .open_table(get_junction_table_definition(field))?;
        let mut map = std::collections::HashMap::new();
        for id in ids {
            let right_ids = table
                .get(id)?
                .map(|g| g.value().clone())
                .unwrap_or_default();
            map.insert(*id, right_ids);
        }
        Ok(map)
    }

    fn get_relationship_count(
        &self,
        id: &EntityId,
        field: &StockMovementRelationshipField,
    ) -> Result<usize, RepositoryError> {
        let table = self
            .transaction
            .open_table(get_junction_table_definition(field))?;
        Ok(table.get(id)?.map(|g| g.value().len()).unwrap_or(0))
    }

    fn get_relationship_in_range(
        &self,
        id: &EntityId,
        field: &StockMovementRelationshipField,
        offset: usize,
        limit: usize,
    ) -> Result<Vec<EntityId>, RepositoryError> {
        let table = self
            .transaction
            .open_table(get_junction_table_definition(field))?;
        let all = table
            .get(id)?
            .map(|g| g.value().clone())
            .unwrap_or_default();
        Ok(all.into_iter().skip(offset).take(limit).collect())
    }

    fn get_relationships_from_right_ids(
        &self,
        field: &StockMovementRelationshipField,
        right_ids: &[EntityId],
    ) -> Result<Vec<(EntityId, Vec<EntityId>)>, RepositoryError> {
        let table = self
            .transaction
            .open_table(get_junction_table_definition(field))?;
        let mut iter = table.iter()?;
        let mut rels = vec![];
        while let Some(Ok((left_id, right_entities))) = iter.next() {
            let left_id = left_id.value();
            let right_entities = right_entities.value();
            if right_ids.iter().any(|eid| right_entities.contains(eid)) {
                rels.push((left_id, right_entities));
            }
        }
        Ok(rels)
    }

    fn set_relationship_multi(
        &mut self,
        field: &StockMovementRelationshipField,
        relationships: Vec<(EntityId, Vec<EntityId>)>,
    ) -> Result<(), RepositoryError> {
        let mut table = self
            .transaction
            .open_table(get_junction_table_definition(field))?;
        for (left_id, entities) in relationships {
            table.insert(left_id, entities)?;
        }
        Ok(())
    }

    fn set_relationship(
        &mut self,
        id: &EntityId,
        field: &StockMovementRelationshipField,
        right_ids: &[EntityId],
    ) -> Result<(), RepositoryError> {
        let mut table = self
            .transaction
            .open_table(get_junction_table_definition(field))?;
        table.insert(*id, right_ids.to_vec())?;
        Ok(())
    }

    fn move_relationship_ids(
        &mut self,
        id: &EntityId,
        field: &StockMovementRelationshipField,
        ids_to_move: &[EntityId],
        new_index: i32,
    ) -> Result<Vec<EntityId>, RepositoryError> {
        if ids_to_move.is_empty() {
            return self.get_relationship(id, field);
        }
        let current_ids = self.get_relationship(id, field)?;
        let move_set: std::collections::HashSet<EntityId> = ids_to_move.iter().copied().collect();
        let mut remaining: Vec<EntityId> = current_ids
            .into_iter()
            .filter(|eid| !move_set.contains(eid))
            .collect();
        let insert_pos = if new_index < 0 || (new_index as usize) > remaining.len() {
            remaining.len()
        } else {
            new_index as usize
        };
        for (i, &eid) in ids_to_move.iter().enumerate() {
            remaining.insert(insert_pos + i, eid);
        }
        let mut table = self
            .transaction
            .open_table(get_junction_table_definition(field))?;
        table.insert(*id, remaining.clone())?;
        Ok(remaining)
    }

    fn snapshot_rows(&self, ids: &[EntityId]) -> Result<TableLevelSnapshot, RepositoryError> {
        let stock_movement_table = self.transaction.open_table(STOCK_MOVEMENT_TABLE)?;

        // Snapshot entity rows as postcard bytes
        let mut rows = Vec::new();
        for id in ids {
            if let Some(guard) = stock_movement_table.get(id)? {
                let entity = guard.value();
                let bytes = postcard::to_allocvec(&entity)
                    .map_err(|e| RepositoryError::Serialization(e.to_string()))?;
                rows.push((*id, bytes));
            }
        }

        // Snapshot forward junction tables
        let mut forward_junctions = Vec::new();

        {
            let junction_table = self
                .transaction
                .open_table(LOCATION_FROM_STOCK_MOVEMENT_FROM_LOCATION_JUNCTION_TABLE)?;
            let mut entries = Vec::new();
            for id in ids {
                if let Some(guard) = junction_table.get(id)? {
                    entries.push((*id, guard.value().clone()));
                }
            }
            forward_junctions.push(JunctionSnapshot {
                table_name: "location_from_stock_movement_from_location_junction".to_string(),
                entries,
            });
        }
        {
            let junction_table = self
                .transaction
                .open_table(USER_FROM_STOCK_MOVEMENT_PERFORMED_BY_JUNCTION_TABLE)?;
            let mut entries = Vec::new();
            for id in ids {
                if let Some(guard) = junction_table.get(id)? {
                    entries.push((*id, guard.value().clone()));
                }
            }
            forward_junctions.push(JunctionSnapshot {
                table_name: "user_from_stock_movement_performed_by_junction".to_string(),
                entries,
            });
        }
        {
            let junction_table = self
                .transaction
                .open_table(PRODUCT_FROM_STOCK_MOVEMENT_PRODUCT_JUNCTION_TABLE)?;
            let mut entries = Vec::new();
            for id in ids {
                if let Some(guard) = junction_table.get(id)? {
                    entries.push((*id, guard.value().clone()));
                }
            }
            forward_junctions.push(JunctionSnapshot {
                table_name: "product_from_stock_movement_product_junction".to_string(),
                entries,
            });
        }
        {
            let junction_table = self
                .transaction
                .open_table(LOCATION_FROM_STOCK_MOVEMENT_TO_LOCATION_JUNCTION_TABLE)?;
            let mut entries = Vec::new();
            for id in ids {
                if let Some(guard) = junction_table.get(id)? {
                    entries.push((*id, guard.value().clone()));
                }
            }
            forward_junctions.push(JunctionSnapshot {
                table_name: "location_from_stock_movement_to_location_junction".to_string(),
                entries,
            });
        }

        // Snapshot backward junction tables (entries that reference any of the given ids)
        let mut backward_junctions = Vec::new();

        {
            let junction_table = self
                .transaction
                .open_table(STOCK_MOVEMENT_FROM_ROOT_STOCK_MOVEMENTS_JUNCTION_TABLE)?;
            let mut entries = Vec::new();
            let mut iter = junction_table.iter()?;
            while let Some(Ok((left_id_guard, right_ids_guard))) = iter.next() {
                let left_id = left_id_guard.value();
                let right_ids = right_ids_guard.value();
                if ids.iter().any(|id| right_ids.contains(id)) {
                    entries.push((left_id, right_ids));
                }
            }
            if !entries.is_empty() {
                backward_junctions.push(JunctionSnapshot {
                    table_name: "stock_movement_from_root_stock_movements_junction".to_string(),
                    entries,
                });
            }
        }

        Ok(TableLevelSnapshot {
            entity_rows: TableSnapshot {
                table_name: "stock_movement".to_string(),
                rows,
            },
            forward_junctions,
            backward_junctions,
        })
    }

    fn restore_rows(&mut self, snap: &TableLevelSnapshot) -> Result<(), RepositoryError> {
        let mut stock_movement_table = self.transaction.open_table(STOCK_MOVEMENT_TABLE)?;

        // Restore entity rows from postcard bytes (redb insert is upsert)
        for (id, bytes) in &snap.entity_rows.rows {
            let entity: StockMovement = postcard::from_bytes(bytes)
                .map_err(|e| RepositoryError::Serialization(e.to_string()))?;
            stock_movement_table.insert(*id, entity)?;
        }

        // Restore forward junction entries

        {
            let mut junction_table = self
                .transaction
                .open_table(LOCATION_FROM_STOCK_MOVEMENT_FROM_LOCATION_JUNCTION_TABLE)?;
            for junction_snap in &snap.forward_junctions {
                if junction_snap.table_name == "location_from_stock_movement_from_location_junction"
                {
                    for (left_id, right_ids) in &junction_snap.entries {
                        junction_table.insert(*left_id, right_ids.clone())?;
                    }
                }
            }
        }
        {
            let mut junction_table = self
                .transaction
                .open_table(USER_FROM_STOCK_MOVEMENT_PERFORMED_BY_JUNCTION_TABLE)?;
            for junction_snap in &snap.forward_junctions {
                if junction_snap.table_name == "user_from_stock_movement_performed_by_junction" {
                    for (left_id, right_ids) in &junction_snap.entries {
                        junction_table.insert(*left_id, right_ids.clone())?;
                    }
                }
            }
        }
        {
            let mut junction_table = self
                .transaction
                .open_table(PRODUCT_FROM_STOCK_MOVEMENT_PRODUCT_JUNCTION_TABLE)?;
            for junction_snap in &snap.forward_junctions {
                if junction_snap.table_name == "product_from_stock_movement_product_junction" {
                    for (left_id, right_ids) in &junction_snap.entries {
                        junction_table.insert(*left_id, right_ids.clone())?;
                    }
                }
            }
        }
        {
            let mut junction_table = self
                .transaction
                .open_table(LOCATION_FROM_STOCK_MOVEMENT_TO_LOCATION_JUNCTION_TABLE)?;
            for junction_snap in &snap.forward_junctions {
                if junction_snap.table_name == "location_from_stock_movement_to_location_junction" {
                    for (left_id, right_ids) in &junction_snap.entries {
                        junction_table.insert(*left_id, right_ids.clone())?;
                    }
                }
            }
        }

        // Restore backward junction entries

        {
            let mut junction_table = self
                .transaction
                .open_table(STOCK_MOVEMENT_FROM_ROOT_STOCK_MOVEMENTS_JUNCTION_TABLE)?;
            for junction_snap in &snap.backward_junctions {
                if junction_snap.table_name == "stock_movement_from_root_stock_movements_junction" {
                    for (left_id, right_ids) in &junction_snap.entries {
                        junction_table.insert(*left_id, right_ids.clone())?;
                    }
                }
            }
        }

        Ok(())
    }
}

pub struct StockMovementRedbTableRO<'a> {
    transaction: &'a ReadTransaction,
}
impl<'a> StockMovementRedbTableRO<'a> {
    pub fn new(transaction: &'a ReadTransaction) -> Self {
        StockMovementRedbTableRO { transaction }
    }
}

impl<'a> StockMovementTableRO for StockMovementRedbTableRO<'a> {
    fn get(&self, id: &EntityId) -> Result<Option<StockMovement>, RepositoryError> {
        let v = self.get_multi(std::slice::from_ref(id))?;
        Ok(v.into_iter().next().unwrap())
    }

    fn get_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<StockMovement>>, RepositoryError> {
        if ids.is_empty() {
            return Ok(Vec::new());
        }
        let mut list = Vec::new();
        let stock_movement_table = self.transaction.open_table(STOCK_MOVEMENT_TABLE)?;

        let from_location_junction_table = self
            .transaction
            .open_table(LOCATION_FROM_STOCK_MOVEMENT_FROM_LOCATION_JUNCTION_TABLE)?;
        let performed_by_junction_table = self
            .transaction
            .open_table(USER_FROM_STOCK_MOVEMENT_PERFORMED_BY_JUNCTION_TABLE)?;
        let product_junction_table = self
            .transaction
            .open_table(PRODUCT_FROM_STOCK_MOVEMENT_PRODUCT_JUNCTION_TABLE)?;
        let to_location_junction_table = self
            .transaction
            .open_table(LOCATION_FROM_STOCK_MOVEMENT_TO_LOCATION_JUNCTION_TABLE)?;

        for id in ids {
            let item = if let Some(guard) = stock_movement_table.get(id)? {
                let mut entity = guard.value().clone();
                let mut _junction_complete = true;

                // get product from junction table
                let fetched_product: Option<EntityId> = product_junction_table
                    .get(id)?
                    .map(|g| g.value().clone())
                    .unwrap_or_default()
                    .pop();
                entity.product = fetched_product;
                // get from_location from junction table
                let fetched_from_location: Option<EntityId> = from_location_junction_table
                    .get(id)?
                    .map(|g| g.value().clone())
                    .unwrap_or_default()
                    .pop();
                entity.from_location = fetched_from_location;
                // get to_location from junction table
                let fetched_to_location: Option<EntityId> = to_location_junction_table
                    .get(id)?
                    .map(|g| g.value().clone())
                    .unwrap_or_default()
                    .pop();
                entity.to_location = fetched_to_location;
                // get performed_by from junction table
                let fetched_performed_by: Option<EntityId> = performed_by_junction_table
                    .get(id)?
                    .map(|g| g.value().clone())
                    .unwrap_or_default()
                    .pop();
                entity.performed_by = fetched_performed_by;
                if _junction_complete {
                    Some(entity)
                } else {
                    None
                }
            } else {
                None
            };
            list.push(item);
        }

        Ok(list)
    }

    fn get_all(&self) -> Result<Vec<StockMovement>, RepositoryError> {
        let mut list = Vec::new();
        let stock_movement_table = self.transaction.open_table(STOCK_MOVEMENT_TABLE)?;

        let from_location_junction_table = self
            .transaction
            .open_table(LOCATION_FROM_STOCK_MOVEMENT_FROM_LOCATION_JUNCTION_TABLE)?;
        let performed_by_junction_table = self
            .transaction
            .open_table(USER_FROM_STOCK_MOVEMENT_PERFORMED_BY_JUNCTION_TABLE)?;
        let product_junction_table = self
            .transaction
            .open_table(PRODUCT_FROM_STOCK_MOVEMENT_PRODUCT_JUNCTION_TABLE)?;
        let to_location_junction_table = self
            .transaction
            .open_table(LOCATION_FROM_STOCK_MOVEMENT_TO_LOCATION_JUNCTION_TABLE)?;

        let mut iter = stock_movement_table.iter()?;
        while let Some(Ok((id, data))) = iter.next() {
            let id = id.value();
            let mut entity = data.value().clone();
            let mut _junction_complete = true;

            // get product from junction table
            let fetched_product: Option<EntityId> = product_junction_table
                .get(&id)?
                .map(|g| g.value().clone())
                .unwrap_or_default()
                .pop();
            entity.product = fetched_product;
            // get from_location from junction table
            let fetched_from_location: Option<EntityId> = from_location_junction_table
                .get(&id)?
                .map(|g| g.value().clone())
                .unwrap_or_default()
                .pop();
            entity.from_location = fetched_from_location;
            // get to_location from junction table
            let fetched_to_location: Option<EntityId> = to_location_junction_table
                .get(&id)?
                .map(|g| g.value().clone())
                .unwrap_or_default()
                .pop();
            entity.to_location = fetched_to_location;
            // get performed_by from junction table
            let fetched_performed_by: Option<EntityId> = performed_by_junction_table
                .get(&id)?
                .map(|g| g.value().clone())
                .unwrap_or_default()
                .pop();
            entity.performed_by = fetched_performed_by;

            if _junction_complete {
                list.push(entity);
            }
        }

        Ok(list)
    }
    fn get_relationship(
        &self,
        id: &EntityId,
        field: &StockMovementRelationshipField,
    ) -> Result<Vec<EntityId>, RepositoryError> {
        let table = self
            .transaction
            .open_table(get_junction_table_definition(field))?;
        let guard = table.get(id)?;
        Ok(guard.map(|g| g.value().clone()).unwrap_or_default())
    }

    fn get_relationship_many(
        &self,
        ids: &[EntityId],
        field: &StockMovementRelationshipField,
    ) -> Result<std::collections::HashMap<EntityId, Vec<EntityId>>, RepositoryError> {
        let table = self
            .transaction
            .open_table(get_junction_table_definition(field))?;
        let mut map = std::collections::HashMap::new();
        for id in ids {
            let right_ids = table
                .get(id)?
                .map(|g| g.value().clone())
                .unwrap_or_default();
            map.insert(*id, right_ids);
        }
        Ok(map)
    }

    fn get_relationship_count(
        &self,
        id: &EntityId,
        field: &StockMovementRelationshipField,
    ) -> Result<usize, RepositoryError> {
        let table = self
            .transaction
            .open_table(get_junction_table_definition(field))?;
        Ok(table.get(id)?.map(|g| g.value().len()).unwrap_or(0))
    }

    fn get_relationship_in_range(
        &self,
        id: &EntityId,
        field: &StockMovementRelationshipField,
        offset: usize,
        limit: usize,
    ) -> Result<Vec<EntityId>, RepositoryError> {
        let table = self
            .transaction
            .open_table(get_junction_table_definition(field))?;
        let all = table
            .get(id)?
            .map(|g| g.value().clone())
            .unwrap_or_default();
        Ok(all.into_iter().skip(offset).take(limit).collect())
    }

    fn get_relationships_from_right_ids(
        &self,
        field: &StockMovementRelationshipField,
        right_ids: &[EntityId],
    ) -> Result<Vec<(EntityId, Vec<EntityId>)>, RepositoryError> {
        let table = self
            .transaction
            .open_table(get_junction_table_definition(field))?;
        let mut iter = table.iter()?;
        let mut rels = vec![];
        while let Some(Ok((left_id, right_entities))) = iter.next() {
            let left_id = left_id.value();
            let right_entities = right_entities.value();
            if right_ids.iter().any(|eid| right_entities.contains(eid)) {
                rels.push((left_id, right_entities));
            }
        }
        Ok(rels)
    }
}
