// Generated by Qleany v1.5.5 from feature_use_case_uow.tera

use crate::use_cases::generate_stock_movement_report_uc::{
    GenerateStockMovementReportUnitOfWorkFactoryTrait, GenerateStockMovementReportUnitOfWorkTrait,
};
use anyhow::{Ok, Result};
use common::database::QueryUnitOfWork;
use common::database::{db_context::DbContext, transactions::Transaction};
#[allow(unused_imports)]
use common::entities::{Location, Product, StockMovement, User};
#[allow(unused_imports)]
use common::types;
#[allow(unused_imports)]
use common::types::EntityId;
use std::sync::Mutex;

pub struct GenerateStockMovementReportUnitOfWork {
    context: DbContext,
    transaction: Mutex<Option<Transaction>>,
}

impl GenerateStockMovementReportUnitOfWork {
    pub fn new(db_context: &DbContext) -> Self {
        GenerateStockMovementReportUnitOfWork {
            context: db_context.clone(),
            transaction: Mutex::new(None),
        }
    }
}

impl QueryUnitOfWork for GenerateStockMovementReportUnitOfWork {
    fn begin_transaction(&self) -> Result<()> {
        let mut transaction = self.transaction.lock().unwrap();
        *transaction = Some(Transaction::begin_read_transaction(&self.context)?);
        Ok(())
    }

    fn end_transaction(&self) -> Result<()> {
        let mut transaction = self.transaction.lock().unwrap();
        transaction
            .take()
            .ok_or_else(|| anyhow::anyhow!("No active transaction"))?
            .end_read_transaction()?;
        Ok(())
    }
}
#[macros::uow_action(entity = "User", action = "GetRO", thread_safe = true)]
#[macros::uow_action(entity = "User", action = "GetMultiRO", thread_safe = true)]
#[macros::uow_action(entity = "StockMovement", action = "GetRO", thread_safe = true)]
#[macros::uow_action(entity = "StockMovement", action = "GetMultiRO", thread_safe = true)]
#[macros::uow_action(entity = "StockMovement", action = "GetAllRO", thread_safe = true)]
#[macros::uow_action(entity = "Product", action = "GetRO", thread_safe = true)]
#[macros::uow_action(entity = "Product", action = "GetMultiRO", thread_safe = true)]
#[macros::uow_action(entity = "Location", action = "GetRO", thread_safe = true)]
#[macros::uow_action(entity = "Location", action = "GetMultiRO", thread_safe = true)]
impl GenerateStockMovementReportUnitOfWorkTrait for GenerateStockMovementReportUnitOfWork {}

pub struct GenerateStockMovementReportUnitOfWorkFactory {
    context: DbContext,
}

impl GenerateStockMovementReportUnitOfWorkFactory {
    pub fn new(db_context: &DbContext) -> Self {
        GenerateStockMovementReportUnitOfWorkFactory {
            context: db_context.clone(),
        }
    }
}

impl GenerateStockMovementReportUnitOfWorkFactoryTrait
    for GenerateStockMovementReportUnitOfWorkFactory
{
    fn create(&self) -> Box<dyn GenerateStockMovementReportUnitOfWorkTrait> {
        Box::new(GenerateStockMovementReportUnitOfWork::new(&self.context))
    }
}
