// Generated by Qleany v1.5.5 from feature_use_case_uow.tera

use crate::use_cases::generate_budget_report_uc::{
    GenerateBudgetReportUnitOfWorkFactoryTrait, GenerateBudgetReportUnitOfWorkTrait,
};
use anyhow::{Ok, Result};
use common::database::QueryUnitOfWork;
use common::database::{db_context::DbContext, transactions::Transaction};
#[allow(unused_imports)]
use common::entities::{BudgetEntry, Deal, Product, User};
#[allow(unused_imports)]
use common::types;
#[allow(unused_imports)]
use common::types::EntityId;
use std::sync::Mutex;

pub struct GenerateBudgetReportUnitOfWork {
    context: DbContext,
    transaction: Mutex<Option<Transaction>>,
}

impl GenerateBudgetReportUnitOfWork {
    pub fn new(db_context: &DbContext) -> Self {
        GenerateBudgetReportUnitOfWork {
            context: db_context.clone(),
            transaction: Mutex::new(None),
        }
    }
}

impl QueryUnitOfWork for GenerateBudgetReportUnitOfWork {
    fn begin_transaction(&self) -> Result<()> {
        let mut transaction = self.transaction.lock().unwrap();
        *transaction = Some(Transaction::begin_read_transaction(&self.context)?);
        Ok(())
    }

    fn end_transaction(&self) -> Result<()> {
        let mut transaction = self.transaction.lock().unwrap();
        transaction
            .take()
            .ok_or_else(|| anyhow::anyhow!("No active transaction"))?
            .end_read_transaction()?;
        Ok(())
    }
}
//TODO: adapt entities and actions to real use :
// GetRO, GetMultiRO, GetRelationshipRO, GetRelationshipsFromRightIdsRO
//
// You have here a long operation read-only unit of work.
//
// RO means Read Only, so *RO actions should be used here.
// Don't forget to set thread_safe = true for long operation's unit of work.
// Do not mix read-only and write actions in the same unit of work.
//
// Exactly the same macros (without thread_safe) must be set in the use case file in ../use_cases/generate_budget_report_uc.rs
//
#[macros::uow_action(entity = "User", action = "GetRO", thread_safe = true)]
#[macros::uow_action(entity = "User", action = "GetMultiRO", thread_safe = true)]
#[macros::uow_action(entity = "BudgetEntry", action = "GetRO", thread_safe = true)]
#[macros::uow_action(entity = "BudgetEntry", action = "GetMultiRO", thread_safe = true)]
#[macros::uow_action(entity = "Product", action = "GetRO", thread_safe = true)]
#[macros::uow_action(entity = "Product", action = "GetMultiRO", thread_safe = true)]
#[macros::uow_action(entity = "Deal", action = "GetRO", thread_safe = true)]
#[macros::uow_action(entity = "Deal", action = "GetMultiRO", thread_safe = true)]
impl GenerateBudgetReportUnitOfWorkTrait for GenerateBudgetReportUnitOfWork {}

pub struct GenerateBudgetReportUnitOfWorkFactory {
    context: DbContext,
}

impl GenerateBudgetReportUnitOfWorkFactory {
    pub fn new(db_context: &DbContext) -> Self {
        GenerateBudgetReportUnitOfWorkFactory {
            context: db_context.clone(),
        }
    }
}

impl GenerateBudgetReportUnitOfWorkFactoryTrait for GenerateBudgetReportUnitOfWorkFactory {
    fn create(&self) -> Box<dyn GenerateBudgetReportUnitOfWorkTrait> {
        Box::new(GenerateBudgetReportUnitOfWork::new(&self.context))
    }
}
