// Generated by Qleany v1.5.5 from repository_factory.tera

pub mod write {

    use crate::{
        database::transactions::Transaction,
        direct_access::{
            budget_entry::{
                budget_entry_repository::BudgetEntryRepository,
                budget_entry_table::BudgetEntryRedbTable,
            },
            category::{
                category_repository::CategoryRepository, category_table::CategoryRedbTable,
            },
            contact::{contact_repository::ContactRepository, contact_table::ContactRedbTable},
            deal::{deal_repository::DealRepository, deal_table::DealRedbTable},
            location::{
                location_repository::LocationRepository, location_table::LocationRedbTable,
            },
            person::{person_repository::PersonRepository, person_table::PersonRedbTable},
            product::{product_repository::ProductRepository, product_table::ProductRedbTable},
            root::{root_repository::RootRepository, root_table::RootRedbTable},
            session::{session_repository::SessionRepository, session_table::SessionRedbTable},
            stock_movement::{
                stock_movement_repository::StockMovementRepository,
                stock_movement_table::StockMovementRedbTable,
            },
            user::{user_repository::UserRepository, user_table::UserRedbTable},
        },
    };
    use anyhow::Result;

    pub fn create_root_repository(transaction: &'_ Transaction) -> Result<RootRepository<'_>> {
        let root_table = RootRedbTable::new(transaction.get_write_transaction()?);
        Ok(RootRepository::new(Box::new(root_table), transaction))
    }

    pub fn create_user_repository(transaction: &'_ Transaction) -> Result<UserRepository<'_>> {
        let user_table = UserRedbTable::new(transaction.get_write_transaction()?);
        Ok(UserRepository::new(Box::new(user_table), transaction))
    }

    pub fn create_session_repository(
        transaction: &'_ Transaction,
    ) -> Result<SessionRepository<'_>> {
        let session_table = SessionRedbTable::new(transaction.get_write_transaction()?);
        Ok(SessionRepository::new(Box::new(session_table), transaction))
    }

    pub fn create_stock_movement_repository(
        transaction: &'_ Transaction,
    ) -> Result<StockMovementRepository<'_>> {
        let stock_movement_table =
            StockMovementRedbTable::new(transaction.get_write_transaction()?);
        Ok(StockMovementRepository::new(
            Box::new(stock_movement_table),
            transaction,
        ))
    }

    pub fn create_budget_entry_repository(
        transaction: &'_ Transaction,
    ) -> Result<BudgetEntryRepository<'_>> {
        let budget_entry_table = BudgetEntryRedbTable::new(transaction.get_write_transaction()?);
        Ok(BudgetEntryRepository::new(
            Box::new(budget_entry_table),
            transaction,
        ))
    }

    pub fn create_product_repository(
        transaction: &'_ Transaction,
    ) -> Result<ProductRepository<'_>> {
        let product_table = ProductRedbTable::new(transaction.get_write_transaction()?);
        Ok(ProductRepository::new(Box::new(product_table), transaction))
    }

    pub fn create_category_repository(
        transaction: &'_ Transaction,
    ) -> Result<CategoryRepository<'_>> {
        let category_table = CategoryRedbTable::new(transaction.get_write_transaction()?);
        Ok(CategoryRepository::new(
            Box::new(category_table),
            transaction,
        ))
    }

    pub fn create_person_repository(transaction: &'_ Transaction) -> Result<PersonRepository<'_>> {
        let person_table = PersonRedbTable::new(transaction.get_write_transaction()?);
        Ok(PersonRepository::new(Box::new(person_table), transaction))
    }

    pub fn create_contact_repository(
        transaction: &'_ Transaction,
    ) -> Result<ContactRepository<'_>> {
        let contact_table = ContactRedbTable::new(transaction.get_write_transaction()?);
        Ok(ContactRepository::new(Box::new(contact_table), transaction))
    }

    pub fn create_deal_repository(transaction: &'_ Transaction) -> Result<DealRepository<'_>> {
        let deal_table = DealRedbTable::new(transaction.get_write_transaction()?);
        Ok(DealRepository::new(Box::new(deal_table), transaction))
    }

    pub fn create_location_repository(
        transaction: &'_ Transaction,
    ) -> Result<LocationRepository<'_>> {
        let location_table = LocationRedbTable::new(transaction.get_write_transaction()?);
        Ok(LocationRepository::new(
            Box::new(location_table),
            transaction,
        ))
    }
}

pub mod read {
    use crate::{
        database::transactions::Transaction,
        direct_access::{
            budget_entry::{
                budget_entry_repository::BudgetEntryRepositoryRO,
                budget_entry_table::BudgetEntryRedbTableRO,
            },
            category::{
                category_repository::CategoryRepositoryRO, category_table::CategoryRedbTableRO,
            },
            contact::{contact_repository::ContactRepositoryRO, contact_table::ContactRedbTableRO},
            deal::{deal_repository::DealRepositoryRO, deal_table::DealRedbTableRO},
            location::{
                location_repository::LocationRepositoryRO, location_table::LocationRedbTableRO,
            },
            person::{person_repository::PersonRepositoryRO, person_table::PersonRedbTableRO},
            product::{product_repository::ProductRepositoryRO, product_table::ProductRedbTableRO},
            root::{root_repository::RootRepositoryRO, root_table::RootRedbTableRO},
            session::{session_repository::SessionRepositoryRO, session_table::SessionRedbTableRO},
            stock_movement::{
                stock_movement_repository::StockMovementRepositoryRO,
                stock_movement_table::StockMovementRedbTableRO,
            },
            user::{user_repository::UserRepositoryRO, user_table::UserRedbTableRO},
        },
    };
    use anyhow::Result;

    pub fn create_root_repository(transaction: &'_ Transaction) -> Result<RootRepositoryRO<'_>> {
        let root_table = RootRedbTableRO::new(transaction.get_read_transaction()?);
        Ok(RootRepositoryRO::new(Box::new(root_table)))
    }

    pub fn create_user_repository(transaction: &'_ Transaction) -> Result<UserRepositoryRO<'_>> {
        let user_table = UserRedbTableRO::new(transaction.get_read_transaction()?);
        Ok(UserRepositoryRO::new(Box::new(user_table)))
    }

    pub fn create_session_repository(
        transaction: &'_ Transaction,
    ) -> Result<SessionRepositoryRO<'_>> {
        let session_table = SessionRedbTableRO::new(transaction.get_read_transaction()?);
        Ok(SessionRepositoryRO::new(Box::new(session_table)))
    }

    pub fn create_stock_movement_repository(
        transaction: &'_ Transaction,
    ) -> Result<StockMovementRepositoryRO<'_>> {
        let stock_movement_table =
            StockMovementRedbTableRO::new(transaction.get_read_transaction()?);
        Ok(StockMovementRepositoryRO::new(Box::new(
            stock_movement_table,
        )))
    }

    pub fn create_budget_entry_repository(
        transaction: &'_ Transaction,
    ) -> Result<BudgetEntryRepositoryRO<'_>> {
        let budget_entry_table = BudgetEntryRedbTableRO::new(transaction.get_read_transaction()?);
        Ok(BudgetEntryRepositoryRO::new(Box::new(budget_entry_table)))
    }

    pub fn create_product_repository(
        transaction: &'_ Transaction,
    ) -> Result<ProductRepositoryRO<'_>> {
        let product_table = ProductRedbTableRO::new(transaction.get_read_transaction()?);
        Ok(ProductRepositoryRO::new(Box::new(product_table)))
    }

    pub fn create_category_repository(
        transaction: &'_ Transaction,
    ) -> Result<CategoryRepositoryRO<'_>> {
        let category_table = CategoryRedbTableRO::new(transaction.get_read_transaction()?);
        Ok(CategoryRepositoryRO::new(Box::new(category_table)))
    }

    pub fn create_person_repository(
        transaction: &'_ Transaction,
    ) -> Result<PersonRepositoryRO<'_>> {
        let person_table = PersonRedbTableRO::new(transaction.get_read_transaction()?);
        Ok(PersonRepositoryRO::new(Box::new(person_table)))
    }

    pub fn create_contact_repository(
        transaction: &'_ Transaction,
    ) -> Result<ContactRepositoryRO<'_>> {
        let contact_table = ContactRedbTableRO::new(transaction.get_read_transaction()?);
        Ok(ContactRepositoryRO::new(Box::new(contact_table)))
    }

    pub fn create_deal_repository(transaction: &'_ Transaction) -> Result<DealRepositoryRO<'_>> {
        let deal_table = DealRedbTableRO::new(transaction.get_read_transaction()?);
        Ok(DealRepositoryRO::new(Box::new(deal_table)))
    }

    pub fn create_location_repository(
        transaction: &'_ Transaction,
    ) -> Result<LocationRepositoryRO<'_>> {
        let location_table = LocationRedbTableRO::new(transaction.get_read_transaction()?);
        Ok(LocationRepositoryRO::new(Box::new(location_table)))
    }
}
