// Generated by Qleany v1.5.5 from common_setup.tera
use crate::error::RepositoryError;
use redb::WriteTransaction;

use crate::direct_access::budget_entry::budget_entry_table::BudgetEntryRedbTable;
use crate::direct_access::category::category_table::CategoryRedbTable;
use crate::direct_access::contact::contact_table::ContactRedbTable;
use crate::direct_access::deal::deal_table::DealRedbTable;
use crate::direct_access::location::location_table::LocationRedbTable;
use crate::direct_access::person::person_table::PersonRedbTable;
use crate::direct_access::product::product_table::ProductRedbTable;
use crate::direct_access::root::root_table::RootRedbTable;
use crate::direct_access::session::session_table::SessionRedbTable;
use crate::direct_access::stock_movement::stock_movement_table::StockMovementRedbTable;
use crate::direct_access::user::user_table::UserRedbTable;

pub fn initialize_all_tables(transaction: &WriteTransaction) -> Result<(), RepositoryError> {
    RootRedbTable::init_tables(transaction)?;
    UserRedbTable::init_tables(transaction)?;
    SessionRedbTable::init_tables(transaction)?;
    StockMovementRedbTable::init_tables(transaction)?;
    BudgetEntryRedbTable::init_tables(transaction)?;
    ProductRedbTable::init_tables(transaction)?;
    CategoryRedbTable::init_tables(transaction)?;
    PersonRedbTable::init_tables(transaction)?;
    ContactRedbTable::init_tables(transaction)?;
    DealRedbTable::init_tables(transaction)?;
    LocationRedbTable::init_tables(transaction)?;
    Ok(())
}
