// Generated by Qleany v1.5.5 from entity_controller.tera

use super::{
    dtos::{CreateSessionDto, SessionDto, UpdateSessionDto},
    units_of_work::{SessionReadUoWFactory, SessionWriteUoWFactory},
};
use anyhow::{Ok, Result};
use common::direct_access::use_cases;

use common::{database::db_context::DbContext, event::EventHub, types::EntityId};
use std::sync::Arc;

pub fn create_orphan(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    entity: &CreateSessionDto,
) -> Result<SessionDto> {
    let uow_factory = SessionWriteUoWFactory::new(db_context, event_hub);
    let mut uc = use_cases::CreateOrphanUseCase::new(uow_factory);
    let entity_in: common::entities::Session = entity.into();
    let result = uc.execute(&entity_in)?;
    Ok(result.into())
}

pub fn create_orphan_multi(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    entities: &[CreateSessionDto],
) -> Result<Vec<SessionDto>> {
    let uow_factory = SessionWriteUoWFactory::new(db_context, event_hub);
    let entities_in: Vec<common::entities::Session> =
        entities.iter().map(|dto| dto.into()).collect();
    let mut uc = use_cases::CreateOrphanUseCase::new(uow_factory);
    let result = uc.execute_multi(&entities_in)?;
    Ok(result.into_iter().map(|e| e.into()).collect())
}

pub fn create(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    entity: &CreateSessionDto,
    owner_id: EntityId,
    index: i32,
) -> Result<SessionDto> {
    let uow_factory = SessionWriteUoWFactory::new(db_context, event_hub);
    let entity_in: common::entities::Session = entity.into();
    let mut uc = use_cases::CreateUseCase::new(uow_factory);
    let result = uc.execute(&entity_in, owner_id, index)?;
    Ok(result.into())
}

pub fn create_multi(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    entities: &[CreateSessionDto],
    owner_id: EntityId,
    index: i32,
) -> Result<Vec<SessionDto>> {
    let uow_factory = SessionWriteUoWFactory::new(db_context, event_hub);
    let entities_in: Vec<common::entities::Session> =
        entities.iter().map(|dto| dto.into()).collect();
    let mut uc = use_cases::CreateUseCase::new(uow_factory);
    let result = uc.execute_multi(&entities_in, owner_id, index)?;
    Ok(result.into_iter().map(|e| e.into()).collect())
}

pub fn get(db_context: &DbContext, id: &EntityId) -> Result<Option<SessionDto>> {
    let uow_factory = SessionReadUoWFactory::new(db_context);
    let uc = use_cases::GetUseCase::new(uow_factory);
    Ok(uc.execute(id)?.map(|e| e.into()))
}

pub fn get_all(db_context: &DbContext) -> Result<Vec<SessionDto>> {
    let uow_factory = SessionReadUoWFactory::new(db_context);
    let uc = use_cases::GetUseCase::new(uow_factory);
    Ok(uc.execute_all()?.into_iter().map(|e| e.into()).collect())
}

pub fn get_multi(db_context: &DbContext, ids: &[EntityId]) -> Result<Vec<Option<SessionDto>>> {
    let uow_factory = SessionReadUoWFactory::new(db_context);
    let uc = use_cases::GetUseCase::new(uow_factory);
    Ok(uc
        .execute_multi(ids)?
        .into_iter()
        .map(|o| o.map(|e| e.into()))
        .collect())
}

pub fn update(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    entity: &UpdateSessionDto,
) -> Result<SessionDto> {
    let uow_factory = SessionWriteUoWFactory::new(db_context, event_hub);
    let entity_in: common::entities::Session = entity.into();
    let mut uc = use_cases::UpdateUseCase::new(uow_factory);
    let result = uc.execute(&entity_in)?;
    Ok(result.into())
}

pub fn update_multi(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    entities: &[UpdateSessionDto],
) -> Result<Vec<SessionDto>> {
    let uow_factory = SessionWriteUoWFactory::new(db_context, event_hub);
    let entities_in: Vec<common::entities::Session> =
        entities.iter().map(|dto| dto.into()).collect();
    let mut uc = use_cases::UpdateUseCase::new(uow_factory);
    let result = uc.execute_multi(&entities_in)?;
    Ok(result.into_iter().map(|e| e.into()).collect())
}

pub fn update_with_relationships(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    entity: &SessionDto,
) -> Result<SessionDto> {
    let uow_factory = SessionWriteUoWFactory::new(db_context, event_hub);
    let entity_in: common::entities::Session = entity.into();
    let mut uc = use_cases::UpdateWithRelationshipsUseCase::new(uow_factory);
    let result = uc.execute(&entity_in)?;
    Ok(result.into())
}

pub fn update_with_relationships_multi(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    entities: &[SessionDto],
) -> Result<Vec<SessionDto>> {
    let uow_factory = SessionWriteUoWFactory::new(db_context, event_hub);
    let entities_in: Vec<common::entities::Session> =
        entities.iter().map(|dto| dto.into()).collect();
    let mut uc = use_cases::UpdateWithRelationshipsUseCase::new(uow_factory);
    let result = uc.execute_multi(&entities_in)?;
    Ok(result.into_iter().map(|e| e.into()).collect())
}

pub fn remove(db_context: &DbContext, event_hub: &Arc<EventHub>, id: &EntityId) -> Result<()> {
    let uow_factory = SessionWriteUoWFactory::new(db_context, event_hub);
    let mut uc = use_cases::RemoveUseCase::new(uow_factory);
    uc.execute(id)?;
    Ok(())
}

pub fn remove_multi(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    ids: &[EntityId],
) -> Result<()> {
    let uow_factory = SessionWriteUoWFactory::new(db_context, event_hub);
    let mut uc = use_cases::RemoveUseCase::new(uow_factory);
    uc.execute_multi(ids)?;
    Ok(())
}
