// Generated by Qleany v1.5.5 from feature_use_case_uow.tera

use crate::use_cases::export_products_uc::{
    ExportProductsUnitOfWorkFactoryTrait, ExportProductsUnitOfWorkTrait,
};
use anyhow::{Ok, Result};
use common::database::QueryUnitOfWork;
use common::database::{db_context::DbContext, transactions::Transaction};
#[allow(unused_imports)]
use common::entities::{Category, Location, Person, Product, Root};
#[allow(unused_imports)]
use common::types;
#[allow(unused_imports)]
use common::types::EntityId;
use std::cell::RefCell;

// Unit of work for ExportProducts

pub struct ExportProductsUnitOfWork {
    context: DbContext,
    transaction: RefCell<Option<Transaction>>,
}

impl ExportProductsUnitOfWork {
    pub fn new(db_context: &DbContext) -> Self {
        ExportProductsUnitOfWork {
            context: db_context.clone(),
            transaction: RefCell::new(None),
        }
    }
}

impl QueryUnitOfWork for ExportProductsUnitOfWork {
    fn begin_transaction(&self) -> Result<()> {
        self.transaction
            .replace(Some(Transaction::begin_read_transaction(&self.context)?));
        Ok(())
    }

    fn end_transaction(&self) -> Result<()> {
        self.transaction
            .take()
            .ok_or_else(|| anyhow::anyhow!("No active transaction"))?
            .end_read_transaction()?;
        Ok(())
    }
}

//TODO: adapt entities and actions to real use :
// GetRO, GetMultiRO, GetRelationshipRO, GetRelationshipsFromRightIdsRO
//
// You have here a read-only unit of work.
//
// RO means Read Only, so *RO actions should be used here.
// Do not mix read-only and write actions in the same unit of work.
//
// Exactly the same macros must be set in the use case uow trait file in ../use_cases/export_products_uc.rs
//
#[macros::uow_action(entity = "Root", action = "GetRO")]
#[macros::uow_action(entity = "Root", action = "GetMultiRO")]
#[macros::uow_action(entity = "Product", action = "GetRO")]
#[macros::uow_action(entity = "Product", action = "GetMultiRO")]
#[macros::uow_action(entity = "Category", action = "GetRO")]
#[macros::uow_action(entity = "Category", action = "GetMultiRO")]
#[macros::uow_action(entity = "Person", action = "GetRO")]
#[macros::uow_action(entity = "Person", action = "GetMultiRO")]
#[macros::uow_action(entity = "Location", action = "GetRO")]
#[macros::uow_action(entity = "Location", action = "GetMultiRO")]
impl ExportProductsUnitOfWorkTrait for ExportProductsUnitOfWork {}

pub struct ExportProductsUnitOfWorkFactory {
    context: DbContext,
}

impl ExportProductsUnitOfWorkFactory {
    pub fn new(db_context: &DbContext) -> Self {
        ExportProductsUnitOfWorkFactory {
            context: db_context.clone(),
        }
    }
}

impl ExportProductsUnitOfWorkFactoryTrait for ExportProductsUnitOfWorkFactory {
    fn create(&self) -> Box<dyn ExportProductsUnitOfWorkTrait> {
        Box::new(ExportProductsUnitOfWork::new(&self.context))
    }
}
