pub mod api;
pub mod auth;
pub mod debt;
pub mod error;
pub mod expenses;
pub mod inventory;
pub mod models;
pub mod persistence;
pub mod recipes;
pub mod reports;
pub mod sales;
pub mod sync;
pub mod utils;
pub mod wallet;

// Re-export types needed by UniFFI scaffolding
pub use api::SweetLabCore;
pub use error::AppError;
pub use models::domain::{
    ConflictLog, Customer, DebtAllocation, DebtPayment, DebtRecord, Expense, ExpenseCategory,
    ExpenseCategoryGroup, FinancialSummary, FinishedGood, FinishedGoodReport, FundTransfer,
    InventoryReport, Invoice, Pagination, ProductionLog, RawMaterial, RawMaterialReport, Receipt,
    Recipe, RecipeAvailability, RecipeIngredient, SafeUser, Sale, SaleLineItem, Session,
    SyncQueueItem, SyncStatus, UserRole, Wallet, WalletTransaction, WalletType,
};
pub use models::Money;

// Re-export types needed by UniFFI scaffolding for custom type converters
pub use uuid::Uuid;

/// Type alias for DateTime<Utc> so UniFFI can reference it without generics.
pub type DateTime = chrono::DateTime<chrono::Utc>;

uniffi::include_scaffolding!("sweet_lab_core");

// UniFFI custom type converters — must be after include_scaffolding
// because UniffiCustomTypeConverter trait is generated by the scaffolding.

impl UniffiCustomTypeConverter for uuid::Uuid {
    type Builtin = String;

    fn into_custom(val: Self::Builtin) -> uniffi::Result<Self> {
        uuid::Uuid::parse_str(&val).map_err(|e| anyhow::anyhow!("Invalid UUID: {e}"))
    }

    fn from_custom(obj: Self) -> Self::Builtin {
        obj.to_string()
    }
}

impl UniffiCustomTypeConverter for DateTime {
    type Builtin = String;

    fn into_custom(val: Self::Builtin) -> uniffi::Result<Self> {
        val.parse::<DateTime>()
            .map_err(|e| anyhow::anyhow!("Invalid DateTime: {e}"))
    }

    fn from_custom(obj: Self) -> Self::Builtin {
        obj.to_rfc3339()
    }
}

impl UniffiCustomTypeConverter for Money {
    type Builtin = i64;

    fn into_custom(val: Self::Builtin) -> uniffi::Result<Self> {
        Ok(Money(val))
    }

    fn from_custom(obj: Self) -> Self::Builtin {
        obj.0
    }
}
