// Generated by Qleany v1.5.5 from feature_use_case.tera
use crate::StockSummaryDto;
use anyhow::{Result, anyhow};
use common::database::QueryUnitOfWork;
use common::entities::{Location, Product, StockMovement};
use common::types::EntityId;

pub trait GetStockSummaryUnitOfWorkFactoryTrait: Send + Sync {
    fn create(&self) -> Box<dyn GetStockSummaryUnitOfWorkTrait>;
}

//TODO: adapt entities and actions to real use :
// GetRO, GetMultiRO, GetRelationship, GetRelationshipRO,
// GetRelationshipsFromRightIdsRO
//
// You have here a read-only unit of work trait.
//
// RO means Read Only, so *RO actions should be used here.
// Do not mix read-only and write actions in the same unit of work.
//
// Exactly the same macros must be set in the use case uow trait file in ../units_of_work/get_stock_summary_uow.rs
//
#[macros::uow_action(entity = "StockMovement", action = "GetRO")]
#[macros::uow_action(entity = "StockMovement", action = "GetMultiRO")]
#[macros::uow_action(entity = "Product", action = "GetRO")]
#[macros::uow_action(entity = "Product", action = "GetMultiRO")]
#[macros::uow_action(entity = "Location", action = "GetRO")]
#[macros::uow_action(entity = "Location", action = "GetMultiRO")]
pub trait GetStockSummaryUnitOfWorkTrait: QueryUnitOfWork {}

pub struct GetStockSummaryUseCase {
    uow_factory: Box<dyn GetStockSummaryUnitOfWorkFactoryTrait>,
}

impl GetStockSummaryUseCase {
    pub fn new(uow_factory: Box<dyn GetStockSummaryUnitOfWorkFactoryTrait>) -> Self {
        GetStockSummaryUseCase { uow_factory }
    }

    pub fn execute(&mut self) -> Result<StockSummaryDto> {
        let mut uow = self.uow_factory.create();
        uow.begin_transaction()?;

        //TODO: GetStockSummaryUseCase to be implemented
        unimplemented!("GetStockSummaryUseCase unimplemented");
        uow.end_transaction()?;
        //Ok(StockSummaryDto {
        //
        //})
        // placeholder to allow compilation
        Err(anyhow!("Not implemented"))
    }
}
