// Generated by Qleany v1.5.5 from feature_use_case.tera
use crate::GetStockHistoryDto;
use crate::StockHistoryDto;
use crate::error::StockTrackingError;
use crate::quantity::compute_delta;
use crate::running_total::compute_running_totals;
use anyhow::Result;
use common::database::QueryUnitOfWork;
use common::entities::{MovementType, Product, StockMovement};
use common::types::EntityId;
use inventory_security::SecurityContext;
use inventory_security_macros::check_permission;

pub trait GetStockHistoryUnitOfWorkFactoryTrait: Send + Sync {
    fn create(&self) -> Box<dyn GetStockHistoryUnitOfWorkTrait>;
}

// Exactly the same macros must be set in ../units_of_work/get_stock_history_uow.rs
#[macros::uow_action(entity = "StockMovement", action = "GetAllRO")]
#[macros::uow_action(entity = "Product", action = "GetRO")]
pub trait GetStockHistoryUnitOfWorkTrait: QueryUnitOfWork {}

pub struct GetStockHistoryUseCase {
    uow_factory: Box<dyn GetStockHistoryUnitOfWorkFactoryTrait>,
}

impl GetStockHistoryUseCase {
    pub fn new(uow_factory: Box<dyn GetStockHistoryUnitOfWorkFactoryTrait>) -> Self {
        GetStockHistoryUseCase { uow_factory }
    }

    pub fn execute(
        &mut self,
        dto: &GetStockHistoryDto,
        security_context: &SecurityContext,
    ) -> Result<StockHistoryDto> {
        // RBAC: requires stock:* or *:read permission (all roles)
        let perm_check = check_permission(security_context, "stock:*")
            .or_else(|_| check_permission(security_context, "*:read"));
        perm_check?;

        let uow = self.uow_factory.create();
        uow.begin_transaction()?;

        // 1. Validate product exists
        let product = uow
            .get_product(&(dto.product_id as EntityId))?
            .ok_or(StockTrackingError::ProductNotFound { id: dto.product_id })?;

        // 2. Get all stock movements and filter for this product
        let all_movements = uow.get_all_stock_movement()?;

        // Filter movements for this product, sorted by created_at ASC
        let mut product_movements: Vec<&StockMovement> = all_movements
            .iter()
            .filter(|m| m.product == Some(dto.product_id as EntityId))
            .collect();
        product_movements.sort_by_key(|m| m.created_at);

        // 3. Compute initial_quantity: product.quantity minus sum of all deltas
        //    from ALL movements for this product (to reconstruct the starting quantity),
        //    then add back deltas from movements before from_date.
        //    Simpler: initial = product.quantity - sum(all deltas), then add deltas before from_date.
        let all_deltas_sum: i64 = product_movements
            .iter()
            .map(|m| compute_delta(&m.movement_type, m.quantity))
            .sum();
        let base_quantity = product.quantity - all_deltas_sum;

        // Movements before from_date contribute to initial quantity
        let pre_range_delta: i64 = product_movements
            .iter()
            .filter(|m| m.created_at < dto.from_date)
            .map(|m| compute_delta(&m.movement_type, m.quantity))
            .sum();
        let initial_quantity = base_quantity + pre_range_delta;

        // 4. Filter to date range [from_date, to_date] inclusive
        let range_movements: Vec<&StockMovement> = product_movements
            .iter()
            .filter(|m| m.created_at >= dto.from_date && m.created_at <= dto.to_date)
            .copied()
            .collect();

        // 5. Compute running totals
        let movement_pairs: Vec<(MovementType, i64)> = range_movements
            .iter()
            .map(|m| (m.movement_type.clone(), m.quantity))
            .collect();
        let running_totals = compute_running_totals(initial_quantity, &movement_pairs);

        // 6. Build parallel arrays
        let movement_ids: Vec<i64> = range_movements.iter().map(|m| m.id as i64).collect();
        let movement_types: Vec<String> = range_movements
            .iter()
            .map(|m| format!("{:?}", m.movement_type))
            .collect();
        let quantities: Vec<i64> = range_movements.iter().map(|m| m.quantity).collect();
        let dates: Vec<String> = range_movements
            .iter()
            .map(|m| m.created_at.to_rfc3339())
            .collect();

        uow.end_transaction()?;

        Ok(StockHistoryDto {
            movement_ids,
            movement_types,
            quantities,
            dates,
            running_totals,
        })
    }
}
