// Generated by Qleany v1.5.5 from feature_use_case.tera
use crate::ChangePasswordDto;
use crate::ChangePasswordResultDto;
use anyhow::{Result, anyhow};
use common::database::CommandUnitOfWork;
use common::entities::User;
use common::types::EntityId;

pub trait ChangePasswordUnitOfWorkFactoryTrait: Send + Sync {
    fn create(&self) -> Box<dyn ChangePasswordUnitOfWorkTrait>;
}

//TODO: adapt entities and actions to real use :
// Create, CreateMulti, Get, GetMulti, Update (scalar-only), UpdateMulti (scalar-only),
// UpdateWithRelationships, UpdateWithRelationshipsMulti,
// Remove, RemoveMulti, GetRelationship, GetRelationshipsFromRightIds,
// SetRelationship, SetRelationshipMulti
//
// You have here a read-write unit of work trait.
//
// RO means Read Only.
// Do not mix read-only and write actions in the same unit of work.
//
// Exactly the same macros must be set in the use case uow trait file in ../units_of_work/change_password_uow.rs
//
#[macros::uow_action(entity = "User", action = "Get")]
#[macros::uow_action(entity = "User", action = "GetMulti")]
#[macros::uow_action(entity = "User", action = "Snapshot")]
#[macros::uow_action(entity = "User", action = "Restore")]
pub trait ChangePasswordUnitOfWorkTrait: CommandUnitOfWork {}

pub struct ChangePasswordUseCase {
    uow_factory: Box<dyn ChangePasswordUnitOfWorkFactoryTrait>,
}

impl ChangePasswordUseCase {
    pub fn new(uow_factory: Box<dyn ChangePasswordUnitOfWorkFactoryTrait>) -> Self {
        ChangePasswordUseCase { uow_factory }
    }

    pub fn execute(&mut self, dto: &ChangePasswordDto) -> Result<ChangePasswordResultDto> {
        let mut uow = self.uow_factory.create();
        uow.begin_transaction()?;

        //TODO: ChangePasswordUseCase to be implemented
        unimplemented!("ChangePasswordUseCase unimplemented");
        uow.commit()?;
        //Ok(ChangePasswordResultDto {
        //
        //})
        // placeholder to allow compilation
        Err(anyhow!("Not implemented"))
    }
}
