// Generated by Qleany v1.5.5 from feature_use_case.tera
use crate::LoginDto;
use crate::LoginResultDto;
use anyhow::{Result, anyhow};
use common::database::CommandUnitOfWork;
use common::entities::{Session, User};
use common::types::EntityId;

pub trait LoginUnitOfWorkFactoryTrait: Send + Sync {
    fn create(&self) -> Box<dyn LoginUnitOfWorkTrait>;
}

//TODO: adapt entities and actions to real use :
// Create, CreateMulti, Get, GetMulti, Update (scalar-only), UpdateMulti (scalar-only),
// UpdateWithRelationships, UpdateWithRelationshipsMulti,
// Remove, RemoveMulti, GetRelationship, GetRelationshipsFromRightIds,
// SetRelationship, SetRelationshipMulti
//
// You have here a read-write unit of work trait.
//
// RO means Read Only.
// Do not mix read-only and write actions in the same unit of work.
//
// Exactly the same macros must be set in the use case uow trait file in ../units_of_work/login_uow.rs
//
#[macros::uow_action(entity = "User", action = "Get")]
#[macros::uow_action(entity = "User", action = "GetMulti")]
#[macros::uow_action(entity = "User", action = "Snapshot")]
#[macros::uow_action(entity = "User", action = "Restore")]
#[macros::uow_action(entity = "Session", action = "Get")]
#[macros::uow_action(entity = "Session", action = "GetMulti")]
#[macros::uow_action(entity = "Session", action = "Snapshot")]
#[macros::uow_action(entity = "Session", action = "Restore")]
pub trait LoginUnitOfWorkTrait: CommandUnitOfWork {}

pub struct LoginUseCase {
    uow_factory: Box<dyn LoginUnitOfWorkFactoryTrait>,
}

impl LoginUseCase {
    pub fn new(uow_factory: Box<dyn LoginUnitOfWorkFactoryTrait>) -> Self {
        LoginUseCase { uow_factory }
    }

    pub fn execute(&mut self, dto: &LoginDto) -> Result<LoginResultDto> {
        let mut uow = self.uow_factory.create();
        uow.begin_transaction()?;

        //TODO: LoginUseCase to be implemented
        unimplemented!("LoginUseCase unimplemented");
        uow.commit()?;
        //Ok(LoginResultDto {
        //
        //})
        // placeholder to allow compilation
        Err(anyhow!("Not implemented"))
    }
}
