// Generated by Qleany v1.5.5 from feature_use_case.tera
use crate::LogoutDto;
use anyhow::{Result, anyhow};
use common::database::CommandUnitOfWork;
use common::entities::{Session, User};
use common::types::EntityId;

pub trait LogoutUnitOfWorkFactoryTrait: Send + Sync {
    fn create(&self) -> Box<dyn LogoutUnitOfWorkTrait>;
}

// Exactly the same macros must be set in the use case uow trait file in ../units_of_work/logout_uow.rs
#[macros::uow_action(entity = "User", action = "Get")]
#[macros::uow_action(entity = "User", action = "GetMulti")]
#[macros::uow_action(entity = "User", action = "GetAll")]
#[macros::uow_action(entity = "User", action = "UpdateWithRelationships")]
#[macros::uow_action(entity = "User", action = "Snapshot")]
#[macros::uow_action(entity = "User", action = "Restore")]
#[macros::uow_action(entity = "Session", action = "Get")]
#[macros::uow_action(entity = "Session", action = "GetMulti")]
#[macros::uow_action(entity = "Session", action = "GetAll")]
#[macros::uow_action(entity = "Session", action = "Remove")]
#[macros::uow_action(entity = "Session", action = "Snapshot")]
#[macros::uow_action(entity = "Session", action = "Restore")]
pub trait LogoutUnitOfWorkTrait: CommandUnitOfWork {}

pub struct LogoutUseCase {
    uow_factory: Box<dyn LogoutUnitOfWorkFactoryTrait>,
}

impl LogoutUseCase {
    pub fn new(uow_factory: Box<dyn LogoutUnitOfWorkFactoryTrait>) -> Self {
        LogoutUseCase { uow_factory }
    }

    pub fn execute(&mut self, dto: &LogoutDto) -> Result<()> {
        // Validate token format
        inventory_auth::validate_logout(&dto.token)?;

        let mut uow = self.uow_factory.create();
        uow.begin_transaction()?;

        // Find the session by token
        let sessions = uow.get_all_session()?;
        let session = sessions.iter().find(|s| s.token == dto.token);
        let session = match session {
            Some(s) => s.clone(),
            None => {
                uow.rollback()?;
                return Err(anyhow!("Session not found"));
            }
        };

        // Unlink session from user
        let users = uow.get_all_user()?;
        if let Some(user) = users.iter().find(|u| u.session == Some(session.id)) {
            let mut updated_user = user.clone();
            updated_user.session = None;
            uow.update_with_relationships_user(&updated_user)?;
        }

        // Delete the session
        uow.remove_session(&session.id)?;

        uow.commit()?;
        Ok(())
    }
}
