// Generated by Qleany v1.5.5 from feature_use_case.tera
use crate::LogoutDto;
use anyhow::{Result, anyhow};
use common::database::CommandUnitOfWork;
use common::entities::{Session, User};
use common::types::EntityId;

pub trait LogoutUnitOfWorkFactoryTrait: Send + Sync {
    fn create(&self) -> Box<dyn LogoutUnitOfWorkTrait>;
}

//TODO: adapt entities and actions to real use :
// Create, CreateMulti, Get, GetMulti, Update (scalar-only), UpdateMulti (scalar-only),
// UpdateWithRelationships, UpdateWithRelationshipsMulti,
// Remove, RemoveMulti, GetRelationship, GetRelationshipsFromRightIds,
// SetRelationship, SetRelationshipMulti
//
// You have here a read-write unit of work trait.
//
// RO means Read Only.
// Do not mix read-only and write actions in the same unit of work.
//
// Exactly the same macros must be set in the use case uow trait file in ../units_of_work/logout_uow.rs
//
#[macros::uow_action(entity = "User", action = "Get")]
#[macros::uow_action(entity = "User", action = "GetMulti")]
#[macros::uow_action(entity = "User", action = "Snapshot")]
#[macros::uow_action(entity = "User", action = "Restore")]
#[macros::uow_action(entity = "Session", action = "Get")]
#[macros::uow_action(entity = "Session", action = "GetMulti")]
#[macros::uow_action(entity = "Session", action = "Snapshot")]
#[macros::uow_action(entity = "Session", action = "Restore")]
pub trait LogoutUnitOfWorkTrait: CommandUnitOfWork {}

pub struct LogoutUseCase {
    uow_factory: Box<dyn LogoutUnitOfWorkFactoryTrait>,
}

impl LogoutUseCase {
    pub fn new(uow_factory: Box<dyn LogoutUnitOfWorkFactoryTrait>) -> Self {
        LogoutUseCase { uow_factory }
    }

    pub fn execute(&mut self, dto: &LogoutDto) -> Result<()> {
        let mut uow = self.uow_factory.create();
        uow.begin_transaction()?;

        //TODO: LogoutUseCase to be implemented
        unimplemented!("LogoutUseCase unimplemented");
        uow.commit()?;
        Ok(())
    }
}
