// Generated by Qleany v1.5.5 from entity_dtos.tera

use common::entities::Deal;
pub use common::entities::DealFrequency;
pub use common::entities::DealStatus;
use common::types::EntityId;
use serde::{Deserialize, Serialize};
use std::convert::From;

#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct DealDto {
    pub id: EntityId,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
    pub title: String,
    pub description: String,
    pub unit_cost: f64,
    pub total_value: f64,
    pub start_date: chrono::DateTime<chrono::Utc>,
    pub end_date: chrono::DateTime<chrono::Utc>,
    pub frequency: DealFrequency,
    pub status: DealStatus,
    pub product: Option<EntityId>,
    pub supplier: Option<EntityId>,
    pub manager: Option<EntityId>,
}

impl From<DealDto> for Deal {
    fn from(dto: DealDto) -> Self {
        Deal {
            id: dto.id,
            created_at: dto.created_at,
            updated_at: dto.updated_at,
            title: dto.title,
            description: dto.description,
            unit_cost: dto.unit_cost,
            total_value: dto.total_value,
            start_date: dto.start_date,
            end_date: dto.end_date,
            frequency: dto.frequency,
            status: dto.status,
            product: dto.product,
            supplier: dto.supplier,
            manager: dto.manager,
        }
    }
}

impl From<&DealDto> for Deal {
    fn from(dto: &DealDto) -> Self {
        Deal {
            id: dto.id,
            created_at: dto.created_at.clone(),
            updated_at: dto.updated_at.clone(),
            title: dto.title.clone(),
            description: dto.description.clone(),
            unit_cost: dto.unit_cost.clone(),
            total_value: dto.total_value.clone(),
            start_date: dto.start_date.clone(),
            end_date: dto.end_date.clone(),
            frequency: dto.frequency.clone(),
            status: dto.status.clone(),
            product: dto.product.clone(),
            supplier: dto.supplier.clone(),
            manager: dto.manager.clone(),
        }
    }
}

impl From<Deal> for DealDto {
    fn from(entity: Deal) -> Self {
        DealDto {
            id: entity.id,
            created_at: entity.created_at,
            updated_at: entity.updated_at,
            title: entity.title,
            description: entity.description,
            unit_cost: entity.unit_cost,
            total_value: entity.total_value,
            start_date: entity.start_date,
            end_date: entity.end_date,
            frequency: entity.frequency,
            status: entity.status,
            product: entity.product,
            supplier: entity.supplier,
            manager: entity.manager,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateDealDto {
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
    pub title: String,
    pub description: String,
    pub unit_cost: f64,
    pub total_value: f64,
    pub start_date: chrono::DateTime<chrono::Utc>,
    pub end_date: chrono::DateTime<chrono::Utc>,
    pub frequency: DealFrequency,
    pub status: DealStatus,
    pub product: Option<EntityId>,
    pub supplier: Option<EntityId>,
    pub manager: Option<EntityId>,
}

impl From<CreateDealDto> for Deal {
    fn from(dto: CreateDealDto) -> Self {
        Deal {
            id: 0,
            created_at: dto.created_at,
            updated_at: dto.updated_at,
            title: dto.title,
            description: dto.description,
            unit_cost: dto.unit_cost,
            total_value: dto.total_value,
            start_date: dto.start_date,
            end_date: dto.end_date,
            frequency: dto.frequency,
            status: dto.status,
            product: dto.product,
            supplier: dto.supplier,
            manager: dto.manager,
        }
    }
}

impl From<&CreateDealDto> for Deal {
    fn from(dto: &CreateDealDto) -> Self {
        Deal {
            id: 0,
            created_at: dto.created_at.clone(),
            updated_at: dto.updated_at.clone(),
            title: dto.title.clone(),
            description: dto.description.clone(),
            unit_cost: dto.unit_cost.clone(),
            total_value: dto.total_value.clone(),
            start_date: dto.start_date.clone(),
            end_date: dto.end_date.clone(),
            frequency: dto.frequency.clone(),
            status: dto.status.clone(),
            product: dto.product.clone(),
            supplier: dto.supplier.clone(),
            manager: dto.manager.clone(),
        }
    }
}

impl From<Deal> for CreateDealDto {
    fn from(entity: Deal) -> Self {
        CreateDealDto {
            created_at: entity.created_at,
            updated_at: entity.updated_at,
            title: entity.title,
            description: entity.description,
            unit_cost: entity.unit_cost,
            total_value: entity.total_value,
            start_date: entity.start_date,
            end_date: entity.end_date,
            frequency: entity.frequency,
            status: entity.status,
            product: entity.product,
            supplier: entity.supplier,
            manager: entity.manager,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateDealDto {
    pub id: EntityId,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
    pub title: String,
    pub description: String,
    pub unit_cost: f64,
    pub total_value: f64,
    pub start_date: chrono::DateTime<chrono::Utc>,
    pub end_date: chrono::DateTime<chrono::Utc>,
    pub frequency: DealFrequency,
    pub status: DealStatus,
}

impl From<UpdateDealDto> for Deal {
    fn from(dto: UpdateDealDto) -> Self {
        Deal {
            id: dto.id,
            created_at: dto.created_at,
            updated_at: dto.updated_at,
            title: dto.title,
            description: dto.description,
            unit_cost: dto.unit_cost,
            total_value: dto.total_value,
            start_date: dto.start_date,
            end_date: dto.end_date,
            frequency: dto.frequency,
            status: dto.status,
            product: Default::default(),
            supplier: Default::default(),
            manager: Default::default(),
        }
    }
}

impl From<&UpdateDealDto> for Deal {
    fn from(dto: &UpdateDealDto) -> Self {
        Deal {
            id: dto.id,
            created_at: dto.created_at.clone(),
            updated_at: dto.updated_at.clone(),
            title: dto.title.clone(),
            description: dto.description.clone(),
            unit_cost: dto.unit_cost.clone(),
            total_value: dto.total_value.clone(),
            start_date: dto.start_date.clone(),
            end_date: dto.end_date.clone(),
            frequency: dto.frequency.clone(),
            status: dto.status.clone(),
            product: Default::default(),
            supplier: Default::default(),
            manager: Default::default(),
        }
    }
}

impl From<Deal> for UpdateDealDto {
    fn from(entity: Deal) -> Self {
        UpdateDealDto {
            id: entity.id,
            created_at: entity.created_at,
            updated_at: entity.updated_at,
            title: entity.title,
            description: entity.description,
            unit_cost: entity.unit_cost,
            total_value: entity.total_value,
            start_date: entity.start_date,
            end_date: entity.end_date,
            frequency: entity.frequency,
            status: entity.status,
        }
    }
}

impl From<DealDto> for UpdateDealDto {
    fn from(dto: DealDto) -> Self {
        UpdateDealDto {
            id: dto.id,
            created_at: dto.created_at,
            updated_at: dto.updated_at,
            title: dto.title,
            description: dto.description,
            unit_cost: dto.unit_cost,
            total_value: dto.total_value,
            start_date: dto.start_date,
            end_date: dto.end_date,
            frequency: dto.frequency,
            status: dto.status,
        }
    }
}
pub use common::direct_access::deal::DealRelationshipField;

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct DealRelationshipDto {
    pub id: EntityId,
    pub field: DealRelationshipField,
    pub right_ids: Vec<EntityId>,
}
