// Generated by Qleany v1.5.5 from feature_controller.tera

use crate::GenerateBudgetReportDto;
use crate::GenerateBudgetReportReturnDto;
use crate::GenerateInventoryReportDto;
use crate::GeneratePurchasingReportDto;
use crate::GeneratePurchasingReportReturnDto;
use crate::GenerateReportReturnDto;
use crate::GenerateStockMovementReportDto;
use crate::GenerateStockReportReturnDto;
use crate::units_of_work::generate_budget_report_uow::GenerateBudgetReportUnitOfWorkFactory;
use crate::units_of_work::generate_inventory_report_uow::GenerateInventoryReportUnitOfWorkFactory;
use crate::units_of_work::generate_purchasing_report_uow::GeneratePurchasingReportUnitOfWorkFactory;
use crate::units_of_work::generate_stock_movement_report_uow::GenerateStockMovementReportUnitOfWorkFactory;
use crate::use_cases::generate_budget_report_uc::GenerateBudgetReportUseCase;
use crate::use_cases::generate_inventory_report_uc::GenerateInventoryReportUseCase;
use crate::use_cases::generate_purchasing_report_uc::GeneratePurchasingReportUseCase;
use crate::use_cases::generate_stock_movement_report_uc::GenerateStockMovementReportUseCase;
use anyhow::Result;
use common::event::{Event, Origin};

use common::long_operation::{LongOperationManager, OperationProgress};
use common::{database::db_context::DbContext, event::EventHub};
use std::sync::Arc;

pub fn generate_inventory_report(
    db_context: &DbContext,
    _event_hub: &Arc<EventHub>,
    long_operation_manager: &mut LongOperationManager,
    dto: &GenerateInventoryReportDto,
) -> Result<String> {
    let uow_context = GenerateInventoryReportUnitOfWorkFactory::new(db_context);
    let uc = GenerateInventoryReportUseCase::new(Box::new(uow_context), dto);
    let operation_id = long_operation_manager.start_operation(uc);
    Ok(operation_id)
}

pub fn get_generate_inventory_report_progress(
    long_operation_manager: &LongOperationManager,
    operation_id: &str,
) -> Option<OperationProgress> {
    long_operation_manager.get_operation_progress(operation_id)
}

pub fn get_generate_inventory_report_result(
    long_operation_manager: &LongOperationManager,
    operation_id: &str,
) -> Result<Option<GenerateReportReturnDto>> {
    // Get the operation result as a JSON string
    let result_json = long_operation_manager.get_operation_result(operation_id);

    // If there's no result, return None
    if result_json.is_none() {
        return Ok(None);
    }
    // Parse the JSON string into a GenerateReportReturnDto
    let result_dto: GenerateReportReturnDto = serde_json::from_str(&result_json.unwrap())?;

    Ok(Some(result_dto))
}

pub fn generate_stock_movement_report(
    db_context: &DbContext,
    _event_hub: &Arc<EventHub>,
    long_operation_manager: &mut LongOperationManager,
    dto: &GenerateStockMovementReportDto,
) -> Result<String> {
    let uow_context = GenerateStockMovementReportUnitOfWorkFactory::new(db_context);
    let uc = GenerateStockMovementReportUseCase::new(Box::new(uow_context), dto);
    let operation_id = long_operation_manager.start_operation(uc);
    Ok(operation_id)
}

pub fn get_generate_stock_movement_report_progress(
    long_operation_manager: &LongOperationManager,
    operation_id: &str,
) -> Option<OperationProgress> {
    long_operation_manager.get_operation_progress(operation_id)
}

pub fn get_generate_stock_movement_report_result(
    long_operation_manager: &LongOperationManager,
    operation_id: &str,
) -> Result<Option<GenerateStockReportReturnDto>> {
    // Get the operation result as a JSON string
    let result_json = long_operation_manager.get_operation_result(operation_id);

    // If there's no result, return None
    if result_json.is_none() {
        return Ok(None);
    }
    // Parse the JSON string into a GenerateStockReportReturnDto
    let result_dto: GenerateStockReportReturnDto = serde_json::from_str(&result_json.unwrap())?;

    Ok(Some(result_dto))
}

pub fn generate_budget_report(
    db_context: &DbContext,
    _event_hub: &Arc<EventHub>,
    long_operation_manager: &mut LongOperationManager,
    dto: &GenerateBudgetReportDto,
) -> Result<String> {
    let uow_context = GenerateBudgetReportUnitOfWorkFactory::new(db_context);
    let uc = GenerateBudgetReportUseCase::new(Box::new(uow_context), dto);
    let operation_id = long_operation_manager.start_operation(uc);
    Ok(operation_id)
}

pub fn get_generate_budget_report_progress(
    long_operation_manager: &LongOperationManager,
    operation_id: &str,
) -> Option<OperationProgress> {
    long_operation_manager.get_operation_progress(operation_id)
}

pub fn get_generate_budget_report_result(
    long_operation_manager: &LongOperationManager,
    operation_id: &str,
) -> Result<Option<GenerateBudgetReportReturnDto>> {
    // Get the operation result as a JSON string
    let result_json = long_operation_manager.get_operation_result(operation_id);

    // If there's no result, return None
    if result_json.is_none() {
        return Ok(None);
    }
    // Parse the JSON string into a GenerateBudgetReportReturnDto
    let result_dto: GenerateBudgetReportReturnDto = serde_json::from_str(&result_json.unwrap())?;

    Ok(Some(result_dto))
}

pub fn generate_purchasing_report(
    db_context: &DbContext,
    _event_hub: &Arc<EventHub>,
    long_operation_manager: &mut LongOperationManager,
    dto: &GeneratePurchasingReportDto,
) -> Result<String> {
    let uow_context = GeneratePurchasingReportUnitOfWorkFactory::new(db_context);
    let uc = GeneratePurchasingReportUseCase::new(Box::new(uow_context), dto);
    let operation_id = long_operation_manager.start_operation(uc);
    Ok(operation_id)
}

pub fn get_generate_purchasing_report_progress(
    long_operation_manager: &LongOperationManager,
    operation_id: &str,
) -> Option<OperationProgress> {
    long_operation_manager.get_operation_progress(operation_id)
}

pub fn get_generate_purchasing_report_result(
    long_operation_manager: &LongOperationManager,
    operation_id: &str,
) -> Result<Option<GeneratePurchasingReportReturnDto>> {
    // Get the operation result as a JSON string
    let result_json = long_operation_manager.get_operation_result(operation_id);

    // If there's no result, return None
    if result_json.is_none() {
        return Ok(None);
    }
    // Parse the JSON string into a GeneratePurchasingReportReturnDto
    let result_dto: GeneratePurchasingReportReturnDto =
        serde_json::from_str(&result_json.unwrap())?;

    Ok(Some(result_dto))
}
