// Generated by Qleany v1.5.5 from feature_use_cases_mod.tera

pub(crate) mod generate_budget_report_uc;
pub(crate) mod generate_inventory_report_uc;
pub(crate) mod generate_purchasing_report_uc;
pub(crate) mod generate_stock_movement_report_uc;
