// Generated by Qleany v1.5.5 from feature_use_case.tera
use crate::GeneratePurchasingReportDto;
use crate::GeneratePurchasingReportReturnDto;
use crate::collectors;
use crate::generate;
use crate::types::ReportFormat;
use anyhow::{Result, anyhow};
use common::database::QueryUnitOfWork;
use common::entities::{Deal, Person, Product};
use common::long_operation::LongOperation;
use common::types::EntityId;
use std::sync::Arc;

pub trait GeneratePurchasingReportUnitOfWorkFactoryTrait: Send + Sync {
    fn create(&self) -> Box<dyn GeneratePurchasingReportUnitOfWorkTrait>;
}

#[macros::uow_action(entity = "Product", action = "GetRO")]
#[macros::uow_action(entity = "Product", action = "GetMultiRO")]
#[macros::uow_action(entity = "Person", action = "GetRO")]
#[macros::uow_action(entity = "Person", action = "GetMultiRO")]
#[macros::uow_action(entity = "Deal", action = "GetRO")]
#[macros::uow_action(entity = "Deal", action = "GetMultiRO")]
#[macros::uow_action(entity = "Deal", action = "GetAllRO")]
pub trait GeneratePurchasingReportUnitOfWorkTrait: QueryUnitOfWork + Send + Sync {}

pub struct GeneratePurchasingReportUseCase {
    uow_factory: Box<dyn GeneratePurchasingReportUnitOfWorkFactoryTrait>,
    dto: GeneratePurchasingReportDto,
}

impl GeneratePurchasingReportUseCase {
    pub fn new(
        uow_factory: Box<dyn GeneratePurchasingReportUnitOfWorkFactoryTrait>,
        dto: &GeneratePurchasingReportDto,
    ) -> Self {
        GeneratePurchasingReportUseCase {
            uow_factory,
            dto: dto.clone(),
        }
    }
}

impl LongOperation for GeneratePurchasingReportUseCase {
    type Output = GeneratePurchasingReportReturnDto;

    fn execute(
        &self,
        progress_callback: Box<dyn Fn(common::long_operation::OperationProgress) + Send>,
        _cancel_flag: Arc<std::sync::atomic::AtomicBool>,
    ) -> Result<Self::Output> {
        progress_callback(common::long_operation::OperationProgress::new(
            0.0,
            Some("Starting purchasing report...".to_string()),
        ));

        let uow = self.uow_factory.create();
        uow.begin_transaction()?;

        let format = match self.dto.format {
            crate::dtos::PurchasingReportFormat::Excel => ReportFormat::Excel,
            crate::dtos::PurchasingReportFormat::Pdf => ReportFormat::Pdf,
            crate::dtos::PurchasingReportFormat::Csv => ReportFormat::Csv,
        };

        let (rows, _count) = collectors::collect_purchasing_rows(
            uow.as_ref(),
            &self.dto.status_filter,
        ).map_err(|e| anyhow!(e.to_string()))?;

        let headers = &[
            "Title", "Description", "Supplier", "Product", "Status",
            "Frequency", "Unit Cost", "Total Value", "Start Date", "End Date",
        ];

        let (file_path, row_count) = generate::generate_report(
            "Purchasing Report",
            headers,
            rows,
            &format,
            &self.dto.output_path,
            &*progress_callback,
        ).map_err(|e| anyhow!(e.to_string()))?;

        uow.end_transaction()?;

        progress_callback(common::long_operation::OperationProgress::new(
            100.0,
            Some("Purchasing report completed".to_string()),
        ));

        Ok(GeneratePurchasingReportReturnDto {
            file_path,
            row_count: row_count as i64,
        })
    }
}
