// Generated by Qleany v1.5.5 from feature_use_case.tera
use crate::GenerateInventoryReportDto;
use crate::GenerateReportReturnDto;
use anyhow::{Result, anyhow};
use common::database::QueryUnitOfWork;
use common::entities::{Category, Location, Person, Product};
use common::long_operation::LongOperation;
use common::types::EntityId;
use std::sync::Arc;

pub trait GenerateInventoryReportUnitOfWorkFactoryTrait: Send + Sync {
    fn create(&self) -> Box<dyn GenerateInventoryReportUnitOfWorkTrait>;
}
//TODO: adapt entities and actions to real use :
// GetRO, GetMultiRO, GetRelationship, GetRelationshipRO,
// GetRelationshipsFromRightIdsRO
//
// You have here a read-only unit of work trait.
//
// RO means Read Only, so *RO actions should be used here.
// Do not mix read-only and write actions in the same unit of work.
//
// Exactly the same macros must be set in the use case uow trait file in ../units_of_work/generate_inventory_report_uow.rs
//
#[macros::uow_action(entity = "Product", action = "GetRO")]
#[macros::uow_action(entity = "Product", action = "GetMultiRO")]
#[macros::uow_action(entity = "Category", action = "GetRO")]
#[macros::uow_action(entity = "Category", action = "GetMultiRO")]
#[macros::uow_action(entity = "Person", action = "GetRO")]
#[macros::uow_action(entity = "Person", action = "GetMultiRO")]
#[macros::uow_action(entity = "Location", action = "GetRO")]
#[macros::uow_action(entity = "Location", action = "GetMultiRO")]
pub trait GenerateInventoryReportUnitOfWorkTrait: QueryUnitOfWork + Send + Sync {}

pub struct GenerateInventoryReportUseCase {
    uow_factory: Box<dyn GenerateInventoryReportUnitOfWorkFactoryTrait>,
    dto: GenerateInventoryReportDto,
}

impl GenerateInventoryReportUseCase {
    pub fn new(
        uow_factory: Box<dyn GenerateInventoryReportUnitOfWorkFactoryTrait>,
        dto: &GenerateInventoryReportDto,
    ) -> Self {
        GenerateInventoryReportUseCase {
            uow_factory,
            dto: dto.clone(),
        }
    }
}
impl LongOperation for GenerateInventoryReportUseCase {
    type Output = GenerateReportReturnDto;

    fn execute(
        &self,
        progress_callback: Box<dyn Fn(common::long_operation::OperationProgress) + Send>,
        cancel_flag: Arc<std::sync::atomic::AtomicBool>,
    ) -> Result<Self::Output> {
        use std::sync::atomic::Ordering;

        progress_callback(common::long_operation::OperationProgress::new(
            0.0,
            Some("Starting...".to_string()),
        ));

        let uow = self.uow_factory.create();
        uow.begin_transaction()?;

        //TODO: GenerateInventoryReportUseCase to be implemented
        unimplemented!("GenerateInventoryReportUseCase unimplemented");

        if cancel_flag.load(Ordering::Relaxed) {
            uow.end_transaction()?;
            return Err(anyhow!("Operation was cancelled"));
        }
        uow.end_transaction()?;

        // Final progress
        progress_callback(common::long_operation::OperationProgress::new(
            100.0,
            Some("completed".to_string()),
        ));
        //Ok(GenerateReportReturnDto {
        //
        //})
        // placeholder to allow compilation
        Err(anyhow!("Not implemented"))
    }
}
