// Generated by Qleany v1.5.5 from feature_use_case.tera
use crate::GenerateStockMovementReportDto;
use crate::GenerateStockReportReturnDto;
use crate::collectors;
use crate::error::ReportError;
use crate::generate;
use crate::types::ReportFormat;
use anyhow::{Result, anyhow};
use common::database::QueryUnitOfWork;
use common::entities::{Location, Product, StockMovement, User};
use common::long_operation::LongOperation;
use common::types::EntityId;
use std::sync::Arc;

pub trait GenerateStockMovementReportUnitOfWorkFactoryTrait: Send + Sync {
    fn create(&self) -> Box<dyn GenerateStockMovementReportUnitOfWorkTrait>;
}

#[macros::uow_action(entity = "User", action = "GetRO")]
#[macros::uow_action(entity = "User", action = "GetMultiRO")]
#[macros::uow_action(entity = "StockMovement", action = "GetRO")]
#[macros::uow_action(entity = "StockMovement", action = "GetMultiRO")]
#[macros::uow_action(entity = "StockMovement", action = "GetAllRO")]
#[macros::uow_action(entity = "Product", action = "GetRO")]
#[macros::uow_action(entity = "Product", action = "GetMultiRO")]
#[macros::uow_action(entity = "Location", action = "GetRO")]
#[macros::uow_action(entity = "Location", action = "GetMultiRO")]
pub trait GenerateStockMovementReportUnitOfWorkTrait: QueryUnitOfWork + Send + Sync {}

pub struct GenerateStockMovementReportUseCase {
    uow_factory: Box<dyn GenerateStockMovementReportUnitOfWorkFactoryTrait>,
    dto: GenerateStockMovementReportDto,
}

impl GenerateStockMovementReportUseCase {
    pub fn new(
        uow_factory: Box<dyn GenerateStockMovementReportUnitOfWorkFactoryTrait>,
        dto: &GenerateStockMovementReportDto,
    ) -> Self {
        GenerateStockMovementReportUseCase {
            uow_factory,
            dto: dto.clone(),
        }
    }
}

impl LongOperation for GenerateStockMovementReportUseCase {
    type Output = GenerateStockReportReturnDto;

    fn execute(
        &self,
        progress_callback: Box<dyn Fn(common::long_operation::OperationProgress) + Send>,
        _cancel_flag: Arc<std::sync::atomic::AtomicBool>,
    ) -> Result<Self::Output> {
        progress_callback(common::long_operation::OperationProgress::new(
            0.0,
            Some("Starting stock movement report...".to_string()),
        ));

        // Validate date range
        if self.dto.from_date > self.dto.to_date {
            return Err(anyhow!(ReportError::InvalidDateRange.to_string()));
        }

        let uow = self.uow_factory.create();
        uow.begin_transaction()?;

        let format = match self.dto.format {
            crate::dtos::StockReportFormat::Excel => ReportFormat::Excel,
            crate::dtos::StockReportFormat::Pdf => ReportFormat::Pdf,
            crate::dtos::StockReportFormat::Csv => ReportFormat::Csv,
        };

        let (rows, _count) = collectors::collect_stock_movement_rows(
            uow.as_ref(),
            &self.dto.from_date,
            &self.dto.to_date,
        ).map_err(|e| anyhow!(e.to_string()))?;

        let headers = &[
            "Date", "Movement Type", "Product Name", "Product Reference",
            "Quantity", "From Location", "To Location", "Performed By", "Note",
        ];

        let (file_path, row_count) = generate::generate_report(
            "Stock Movement Report",
            headers,
            rows,
            &format,
            &self.dto.output_path,
            &*progress_callback,
        ).map_err(|e| anyhow!(e.to_string()))?;

        uow.end_transaction()?;

        progress_callback(common::long_operation::OperationProgress::new(
            100.0,
            Some("Stock movement report completed".to_string()),
        ));

        Ok(GenerateStockReportReturnDto {
            file_path,
            row_count: row_count as i64,
        })
    }
}
