// Generated by Qleany v1.5.5 from feature_use_case.tera
use crate::GenerateInventoryReportDto;
use crate::GenerateReportReturnDto;
use crate::collectors;
use crate::generate;
use crate::types::ReportFormat;
use anyhow::{Result, anyhow};
use common::database::QueryUnitOfWork;
use common::entities::{Category, Location, Person, Product};
use common::long_operation::LongOperation;
use common::types::EntityId;
use std::sync::Arc;

pub trait GenerateInventoryReportUnitOfWorkFactoryTrait: Send + Sync {
    fn create(&self) -> Box<dyn GenerateInventoryReportUnitOfWorkTrait>;
}

#[macros::uow_action(entity = "Product", action = "GetRO")]
#[macros::uow_action(entity = "Product", action = "GetMultiRO")]
#[macros::uow_action(entity = "Product", action = "GetAllRO")]
#[macros::uow_action(entity = "Category", action = "GetRO")]
#[macros::uow_action(entity = "Category", action = "GetMultiRO")]
#[macros::uow_action(entity = "Person", action = "GetRO")]
#[macros::uow_action(entity = "Person", action = "GetMultiRO")]
#[macros::uow_action(entity = "Location", action = "GetRO")]
#[macros::uow_action(entity = "Location", action = "GetMultiRO")]
pub trait GenerateInventoryReportUnitOfWorkTrait: QueryUnitOfWork + Send + Sync {}

pub struct GenerateInventoryReportUseCase {
    uow_factory: Box<dyn GenerateInventoryReportUnitOfWorkFactoryTrait>,
    dto: GenerateInventoryReportDto,
}

impl GenerateInventoryReportUseCase {
    pub fn new(
        uow_factory: Box<dyn GenerateInventoryReportUnitOfWorkFactoryTrait>,
        dto: &GenerateInventoryReportDto,
    ) -> Self {
        GenerateInventoryReportUseCase {
            uow_factory,
            dto: dto.clone(),
        }
    }
}

impl LongOperation for GenerateInventoryReportUseCase {
    type Output = GenerateReportReturnDto;

    fn execute(
        &self,
        progress_callback: Box<dyn Fn(common::long_operation::OperationProgress) + Send>,
        _cancel_flag: Arc<std::sync::atomic::AtomicBool>,
    ) -> Result<Self::Output> {
        progress_callback(common::long_operation::OperationProgress::new(
            0.0,
            Some("Starting inventory report...".to_string()),
        ));

        let uow = self.uow_factory.create();
        uow.begin_transaction()?;

        // Convert DTO format to internal ReportFormat
        let format = match self.dto.format {
            crate::dtos::ReportFormat::Excel => ReportFormat::Excel,
            crate::dtos::ReportFormat::Pdf => ReportFormat::Pdf,
            crate::dtos::ReportFormat::Csv => ReportFormat::Csv,
        };

        let (rows, _count) = collectors::collect_inventory_rows(
            uow.as_ref(),
            self.dto.include_zero_stock,
        ).map_err(|e| anyhow!(e.to_string()))?;

        let headers = &[
            "Name", "Reference", "Description", "Quantity", "Price Unit",
            "Status", "Category", "Location", "Supplier",
        ];

        let (file_path, row_count) = generate::generate_report(
            "Inventory Report",
            headers,
            rows,
            &format,
            &self.dto.output_path,
            &*progress_callback,
        ).map_err(|e| anyhow!(e.to_string()))?;

        uow.end_transaction()?;

        progress_callback(common::long_operation::OperationProgress::new(
            100.0,
            Some("Inventory report completed".to_string()),
        ));

        Ok(GenerateReportReturnDto {
            file_path,
            row_count: row_count as i64,
        })
    }
}
