// Generated by Qleany v1.5.5 from feature_use_case.tera
use crate::GenerateBudgetReportDto;
use crate::GenerateBudgetReportReturnDto;
use anyhow::{Result, anyhow};
use common::database::QueryUnitOfWork;
use common::entities::{BudgetEntry, Deal, Product, User};
use common::long_operation::LongOperation;
use common::types::EntityId;
use std::sync::Arc;

pub trait GenerateBudgetReportUnitOfWorkFactoryTrait: Send + Sync {
    fn create(&self) -> Box<dyn GenerateBudgetReportUnitOfWorkTrait>;
}
//TODO: adapt entities and actions to real use :
// GetRO, GetMultiRO, GetRelationship, GetRelationshipRO,
// GetRelationshipsFromRightIdsRO
//
// You have here a read-only unit of work trait.
//
// RO means Read Only, so *RO actions should be used here.
// Do not mix read-only and write actions in the same unit of work.
//
// Exactly the same macros must be set in the use case uow trait file in ../units_of_work/generate_budget_report_uow.rs
//
#[macros::uow_action(entity = "User", action = "GetRO")]
#[macros::uow_action(entity = "User", action = "GetMultiRO")]
#[macros::uow_action(entity = "BudgetEntry", action = "GetRO")]
#[macros::uow_action(entity = "BudgetEntry", action = "GetMultiRO")]
#[macros::uow_action(entity = "Product", action = "GetRO")]
#[macros::uow_action(entity = "Product", action = "GetMultiRO")]
#[macros::uow_action(entity = "Deal", action = "GetRO")]
#[macros::uow_action(entity = "Deal", action = "GetMultiRO")]
pub trait GenerateBudgetReportUnitOfWorkTrait: QueryUnitOfWork + Send + Sync {}

pub struct GenerateBudgetReportUseCase {
    uow_factory: Box<dyn GenerateBudgetReportUnitOfWorkFactoryTrait>,
    dto: GenerateBudgetReportDto,
}

impl GenerateBudgetReportUseCase {
    pub fn new(
        uow_factory: Box<dyn GenerateBudgetReportUnitOfWorkFactoryTrait>,
        dto: &GenerateBudgetReportDto,
    ) -> Self {
        GenerateBudgetReportUseCase {
            uow_factory,
            dto: dto.clone(),
        }
    }
}
impl LongOperation for GenerateBudgetReportUseCase {
    type Output = GenerateBudgetReportReturnDto;

    fn execute(
        &self,
        progress_callback: Box<dyn Fn(common::long_operation::OperationProgress) + Send>,
        cancel_flag: Arc<std::sync::atomic::AtomicBool>,
    ) -> Result<Self::Output> {
        use std::sync::atomic::Ordering;

        progress_callback(common::long_operation::OperationProgress::new(
            0.0,
            Some("Starting...".to_string()),
        ));

        let uow = self.uow_factory.create();
        uow.begin_transaction()?;

        //TODO: GenerateBudgetReportUseCase to be implemented
        unimplemented!("GenerateBudgetReportUseCase unimplemented");

        if cancel_flag.load(Ordering::Relaxed) {
            uow.end_transaction()?;
            return Err(anyhow!("Operation was cancelled"));
        }
        uow.end_transaction()?;

        // Final progress
        progress_callback(common::long_operation::OperationProgress::new(
            100.0,
            Some("completed".to_string()),
        ));
        //Ok(GenerateBudgetReportReturnDto {
        //
        //})
        // placeholder to allow compilation
        Err(anyhow!("Not implemented"))
    }
}
