// Generated by Qleany v1.5.5 from entity_dtos.tera

use common::entities::Person;
pub use common::entities::PersonRole;
use common::types::EntityId;
use serde::{Deserialize, Serialize};
use std::convert::From;

#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct PersonDto {
    pub id: EntityId,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
    pub name: String,
    pub role: PersonRole,
    pub contact: Option<EntityId>,
}

impl From<PersonDto> for Person {
    fn from(dto: PersonDto) -> Self {
        Person {
            id: dto.id,
            created_at: dto.created_at,
            updated_at: dto.updated_at,
            name: dto.name,
            role: dto.role,
            contact: dto.contact,
        }
    }
}

impl From<&PersonDto> for Person {
    fn from(dto: &PersonDto) -> Self {
        Person {
            id: dto.id,
            created_at: dto.created_at.clone(),
            updated_at: dto.updated_at.clone(),
            name: dto.name.clone(),
            role: dto.role.clone(),
            contact: dto.contact.clone(),
        }
    }
}

impl From<Person> for PersonDto {
    fn from(entity: Person) -> Self {
        PersonDto {
            id: entity.id,
            created_at: entity.created_at,
            updated_at: entity.updated_at,
            name: entity.name,
            role: entity.role,
            contact: entity.contact,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct CreatePersonDto {
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
    pub name: String,
    pub role: PersonRole,
    pub contact: Option<EntityId>,
}

impl From<CreatePersonDto> for Person {
    fn from(dto: CreatePersonDto) -> Self {
        Person {
            id: 0,
            created_at: dto.created_at,
            updated_at: dto.updated_at,
            name: dto.name,
            role: dto.role,
            contact: dto.contact,
        }
    }
}

impl From<&CreatePersonDto> for Person {
    fn from(dto: &CreatePersonDto) -> Self {
        Person {
            id: 0,
            created_at: dto.created_at.clone(),
            updated_at: dto.updated_at.clone(),
            name: dto.name.clone(),
            role: dto.role.clone(),
            contact: dto.contact.clone(),
        }
    }
}

impl From<Person> for CreatePersonDto {
    fn from(entity: Person) -> Self {
        CreatePersonDto {
            created_at: entity.created_at,
            updated_at: entity.updated_at,
            name: entity.name,
            role: entity.role,
            contact: entity.contact,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdatePersonDto {
    pub id: EntityId,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
    pub name: String,
    pub role: PersonRole,
}

impl From<UpdatePersonDto> for Person {
    fn from(dto: UpdatePersonDto) -> Self {
        Person {
            id: dto.id,
            created_at: dto.created_at,
            updated_at: dto.updated_at,
            name: dto.name,
            role: dto.role,
            contact: Default::default(),
        }
    }
}

impl From<&UpdatePersonDto> for Person {
    fn from(dto: &UpdatePersonDto) -> Self {
        Person {
            id: dto.id,
            created_at: dto.created_at.clone(),
            updated_at: dto.updated_at.clone(),
            name: dto.name.clone(),
            role: dto.role.clone(),
            contact: Default::default(),
        }
    }
}

impl From<Person> for UpdatePersonDto {
    fn from(entity: Person) -> Self {
        UpdatePersonDto {
            id: entity.id,
            created_at: entity.created_at,
            updated_at: entity.updated_at,
            name: entity.name,
            role: entity.role,
        }
    }
}

impl From<PersonDto> for UpdatePersonDto {
    fn from(dto: PersonDto) -> Self {
        UpdatePersonDto {
            id: dto.id,
            created_at: dto.created_at,
            updated_at: dto.updated_at,
            name: dto.name,
            role: dto.role,
        }
    }
}
pub use common::direct_access::person::PersonRelationshipField;

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PersonRelationshipDto {
    pub id: EntityId,
    pub field: PersonRelationshipField,
    pub right_ids: Vec<EntityId>,
}
