// Generated by Qleany v1.5.5 from frontend_feature_commands.tera

//! Authentication feature commands

use crate::app_context::AppContext;
use anyhow::{Context, Result};
use authentication::{
    ChangePasswordDto, ChangePasswordResultDto, LoginDto, LoginResultDto, LogoutDto,
    authentication_controller,
};

pub fn login(ctx: &AppContext, dto: &LoginDto) -> Result<LoginResultDto> {
    authentication_controller::login(&ctx.db_context, &ctx.event_hub, dto).context("login")
}

pub fn logout(ctx: &AppContext, dto: &LogoutDto) -> Result<()> {
    authentication_controller::logout(&ctx.db_context, &ctx.event_hub, dto).context("logout")
}

pub fn change_password(
    ctx: &AppContext,
    dto: &ChangePasswordDto,
) -> Result<ChangePasswordResultDto> {
    authentication_controller::change_password(&ctx.db_context, &ctx.event_hub, dto)
        .context("change_password")
}
