// Generated by Qleany v1.5.5 from frontend_entity_commands.tera

//! BudgetEntry entity commands
#![allow(unused_imports, dead_code)]

use crate::app_context::AppContext;
use anyhow::{Context, Result};
use common::direct_access::budget_entry::BudgetEntryRelationshipField;
use common::types::EntityId;
use direct_access::BudgetEntryRelationshipDto;
use direct_access::{
    BudgetEntryDto, CreateBudgetEntryDto, UpdateBudgetEntryDto, budget_entry_controller,
};

/// Create a new budget_entry entity (orphan, no parent)
pub fn create_orphan_budget_entry(
    ctx: &AppContext,

    dto: &CreateBudgetEntryDto,
) -> Result<BudgetEntryDto> {
    budget_entry_controller::create_orphan(&ctx.db_context, &ctx.event_hub, dto)
        .context("creating budget_entry")
}
/// Create a new budget_entry entity as child of owner
pub fn create_budget_entry(
    ctx: &AppContext,

    dto: &CreateBudgetEntryDto,
    owner_id: EntityId,
    index: i32,
) -> Result<BudgetEntryDto> {
    budget_entry_controller::create(&ctx.db_context, &ctx.event_hub, dto, owner_id, index)
        .context("creating budget_entry")
}
/// Create multiple budget_entry entities (orphan, no parent)
pub fn create_orphan_budget_entry_multi(
    ctx: &AppContext,

    dtos: &[CreateBudgetEntryDto],
) -> Result<Vec<BudgetEntryDto>> {
    budget_entry_controller::create_orphan_multi(&ctx.db_context, &ctx.event_hub, dtos)
        .context("creating budget_entry entities")
}
/// Create multiple budget_entry entities as children of owner
pub fn create_budget_entry_multi(
    ctx: &AppContext,

    dtos: &[CreateBudgetEntryDto],
    owner_id: EntityId,
    index: i32,
) -> Result<Vec<BudgetEntryDto>> {
    budget_entry_controller::create_multi(&ctx.db_context, &ctx.event_hub, dtos, owner_id, index)
        .context("creating budget_entry entities")
}
/// Get a budget_entry entity by ID
pub fn get_budget_entry(ctx: &AppContext, id: &EntityId) -> Result<Option<BudgetEntryDto>> {
    budget_entry_controller::get(&ctx.db_context, id).context("getting budget_entry")
}

/// Get multiple budget_entry entities by IDs
pub fn get_budget_entry_multi(
    ctx: &AppContext,
    ids: &[EntityId],
) -> Result<Vec<Option<BudgetEntryDto>>> {
    budget_entry_controller::get_multi(&ctx.db_context, ids)
        .context("getting budget_entry entities")
}

/// Get all budget_entry entities.
/// Note: returns entities in database key order (by EntityId), not insertion order
/// or any user-defined sort. For ordered collections, use relationship-based
/// retrieval (e.g. get_*_relationship for ordered_one_to_many fields).
pub fn get_all_budget_entry(ctx: &AppContext) -> Result<Vec<BudgetEntryDto>> {
    budget_entry_controller::get_all(&ctx.db_context).context("getting all budget_entry entities")
}

/// Update a budget_entry entity
pub fn update_budget_entry(ctx: &AppContext, dto: &UpdateBudgetEntryDto) -> Result<BudgetEntryDto> {
    budget_entry_controller::update(&ctx.db_context, &ctx.event_hub, dto)
        .context("updating budget_entry")
}

/// Update multiple budget_entry entities
pub fn update_budget_entry_multi(
    ctx: &AppContext,

    dtos: &[UpdateBudgetEntryDto],
) -> Result<Vec<BudgetEntryDto>> {
    budget_entry_controller::update_multi(&ctx.db_context, &ctx.event_hub, dtos)
        .context("updating budget_entry entities")
}

/// Update a budget_entry entity with relationships
pub fn update_budget_entry_with_relationships(
    ctx: &AppContext,

    dto: &BudgetEntryDto,
) -> Result<BudgetEntryDto> {
    budget_entry_controller::update_with_relationships(&ctx.db_context, &ctx.event_hub, dto)
        .context("updating budget_entry with relationships")
}

/// Update multiple budget_entry entities with relationships
pub fn update_budget_entry_with_relationships_multi(
    ctx: &AppContext,

    dtos: &[BudgetEntryDto],
) -> Result<Vec<BudgetEntryDto>> {
    budget_entry_controller::update_with_relationships_multi(&ctx.db_context, &ctx.event_hub, dtos)
        .context("updating budget_entry entities with relationships")
}

/// Remove a budget_entry entity by ID
pub fn remove_budget_entry(ctx: &AppContext, id: &EntityId) -> Result<()> {
    budget_entry_controller::remove(&ctx.db_context, &ctx.event_hub, id)
        .context("removing budget_entry")
}

/// Remove multiple budget_entry entities by IDs
pub fn remove_budget_entry_multi(ctx: &AppContext, ids: &[EntityId]) -> Result<()> {
    budget_entry_controller::remove_multi(&ctx.db_context, &ctx.event_hub, ids)
        .context("removing budget_entry entities")
}

/// Get a budget_entry relationship
pub fn get_budget_entry_relationship(
    ctx: &AppContext,
    id: &EntityId,
    field: &BudgetEntryRelationshipField,
) -> Result<Vec<EntityId>> {
    budget_entry_controller::get_relationship(&ctx.db_context, id, field)
        .context("getting budget_entry relationship")
}

/// Get relationship IDs for multiple budget_entry entities at once
pub fn get_budget_entry_relationship_many(
    ctx: &AppContext,
    ids: &[EntityId],
    field: &BudgetEntryRelationshipField,
) -> Result<std::collections::HashMap<EntityId, Vec<EntityId>>> {
    budget_entry_controller::get_relationship_many(&ctx.db_context, ids, field)
        .context("getting budget_entry relationships (many)")
}

/// Get relationship count for a budget_entry entity
pub fn get_budget_entry_relationship_count(
    ctx: &AppContext,
    id: &EntityId,
    field: &BudgetEntryRelationshipField,
) -> Result<usize> {
    budget_entry_controller::get_relationship_count(&ctx.db_context, id, field)
        .context("getting budget_entry relationship count")
}

/// Get relationship IDs for a budget_entry entity with pagination
pub fn get_budget_entry_relationship_in_range(
    ctx: &AppContext,
    id: &EntityId,
    field: &BudgetEntryRelationshipField,
    offset: usize,
    limit: usize,
) -> Result<Vec<EntityId>> {
    budget_entry_controller::get_relationship_in_range(&ctx.db_context, id, field, offset, limit)
        .context("getting budget_entry relationship range")
}

/// Set a budget_entry relationship
pub fn set_budget_entry_relationship(
    ctx: &AppContext,

    dto: &BudgetEntryRelationshipDto,
) -> Result<()> {
    budget_entry_controller::set_relationship(&ctx.db_context, &ctx.event_hub, dto)
        .context("setting budget_entry relationship")
}

/// Move (reorder) IDs within a budget_entry relationship
pub fn move_budget_entry_relationship(
    ctx: &AppContext,

    id: &EntityId,
    field: &BudgetEntryRelationshipField,
    ids_to_move: &[EntityId],
    new_index: i32,
) -> Result<Vec<EntityId>> {
    budget_entry_controller::move_relationship(
        &ctx.db_context,
        &ctx.event_hub,
        id,
        field,
        ids_to_move,
        new_index,
    )
    .context("moving budget_entry relationship")
}
