// Generated by Qleany v1.5.5 from frontend_entity_commands.tera

//! Category entity commands
#![allow(unused_imports, dead_code)]

use crate::app_context::AppContext;
use anyhow::{Context, Result};
use common::direct_access::category::CategoryRelationshipField;
use common::types::EntityId;
use direct_access::CategoryRelationshipDto;
use direct_access::{CategoryDto, CreateCategoryDto, UpdateCategoryDto, category_controller};

/// Create a new category entity (orphan, no parent)
pub fn create_orphan_category(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dto: &CreateCategoryDto,
) -> Result<CategoryDto> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    category_controller::create_orphan(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dto,
    )
    .context("creating category")
}
/// Create a new category entity as child of owner
pub fn create_category(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dto: &CreateCategoryDto,
    owner_id: EntityId,
    index: i32,
) -> Result<CategoryDto> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    category_controller::create(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dto,
        owner_id,
        index,
    )
    .context("creating category")
}
/// Create multiple category entities (orphan, no parent)
pub fn create_orphan_category_multi(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dtos: &[CreateCategoryDto],
) -> Result<Vec<CategoryDto>> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    category_controller::create_orphan_multi(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dtos,
    )
    .context("creating category entities")
}
/// Create multiple category entities as children of owner
pub fn create_category_multi(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dtos: &[CreateCategoryDto],
    owner_id: EntityId,
    index: i32,
) -> Result<Vec<CategoryDto>> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    category_controller::create_multi(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dtos,
        owner_id,
        index,
    )
    .context("creating category entities")
}
/// Get a category entity by ID
pub fn get_category(ctx: &AppContext, id: &EntityId) -> Result<Option<CategoryDto>> {
    category_controller::get(&ctx.db_context, id).context("getting category")
}

/// Get multiple category entities by IDs
pub fn get_category_multi(ctx: &AppContext, ids: &[EntityId]) -> Result<Vec<Option<CategoryDto>>> {
    category_controller::get_multi(&ctx.db_context, ids).context("getting category entities")
}

/// Get all category entities.
/// Note: returns entities in database key order (by EntityId), not insertion order
/// or any user-defined sort. For ordered collections, use relationship-based
/// retrieval (e.g. get_*_relationship for ordered_one_to_many fields).
pub fn get_all_category(ctx: &AppContext) -> Result<Vec<CategoryDto>> {
    category_controller::get_all(&ctx.db_context).context("getting all category entities")
}

/// Update a category entity
pub fn update_category(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dto: &UpdateCategoryDto,
) -> Result<CategoryDto> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    category_controller::update(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dto,
    )
    .context("updating category")
}

/// Update multiple category entities
pub fn update_category_multi(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dtos: &[UpdateCategoryDto],
) -> Result<Vec<CategoryDto>> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    category_controller::update_multi(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dtos,
    )
    .context("updating category entities")
}

/// Update a category entity with relationships
pub fn update_category_with_relationships(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dto: &CategoryDto,
) -> Result<CategoryDto> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    category_controller::update_with_relationships(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dto,
    )
    .context("updating category with relationships")
}

/// Update multiple category entities with relationships
pub fn update_category_with_relationships_multi(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dtos: &[CategoryDto],
) -> Result<Vec<CategoryDto>> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    category_controller::update_with_relationships_multi(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dtos,
    )
    .context("updating category entities with relationships")
}

/// Remove a category entity by ID
pub fn remove_category(ctx: &AppContext, stack_id: Option<u64>, id: &EntityId) -> Result<()> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    category_controller::remove(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        id,
    )
    .context("removing category")
}

/// Remove multiple category entities by IDs
pub fn remove_category_multi(
    ctx: &AppContext,
    stack_id: Option<u64>,
    ids: &[EntityId],
) -> Result<()> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    category_controller::remove_multi(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        ids,
    )
    .context("removing category entities")
}

/// Get a category relationship
pub fn get_category_relationship(
    ctx: &AppContext,
    id: &EntityId,
    field: &CategoryRelationshipField,
) -> Result<Vec<EntityId>> {
    category_controller::get_relationship(&ctx.db_context, id, field)
        .context("getting category relationship")
}

/// Get relationship IDs for multiple category entities at once
pub fn get_category_relationship_many(
    ctx: &AppContext,
    ids: &[EntityId],
    field: &CategoryRelationshipField,
) -> Result<std::collections::HashMap<EntityId, Vec<EntityId>>> {
    category_controller::get_relationship_many(&ctx.db_context, ids, field)
        .context("getting category relationships (many)")
}

/// Get relationship count for a category entity
pub fn get_category_relationship_count(
    ctx: &AppContext,
    id: &EntityId,
    field: &CategoryRelationshipField,
) -> Result<usize> {
    category_controller::get_relationship_count(&ctx.db_context, id, field)
        .context("getting category relationship count")
}

/// Get relationship IDs for a category entity with pagination
pub fn get_category_relationship_in_range(
    ctx: &AppContext,
    id: &EntityId,
    field: &CategoryRelationshipField,
    offset: usize,
    limit: usize,
) -> Result<Vec<EntityId>> {
    category_controller::get_relationship_in_range(&ctx.db_context, id, field, offset, limit)
        .context("getting category relationship range")
}

/// Set a category relationship
pub fn set_category_relationship(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dto: &CategoryRelationshipDto,
) -> Result<()> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    category_controller::set_relationship(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dto,
    )
    .context("setting category relationship")
}

/// Move (reorder) IDs within a category relationship
pub fn move_category_relationship(
    ctx: &AppContext,
    stack_id: Option<u64>,
    id: &EntityId,
    field: &CategoryRelationshipField,
    ids_to_move: &[EntityId],
    new_index: i32,
) -> Result<Vec<EntityId>> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    category_controller::move_relationship(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        id,
        field,
        ids_to_move,
        new_index,
    )
    .context("moving category relationship")
}
