// Generated by Qleany v1.5.5 from frontend_entity_commands.tera

//! Contact entity commands
#![allow(unused_imports, dead_code)]

use crate::app_context::AppContext;
use anyhow::{Context, Result};
use common::types::EntityId;
use direct_access::{ContactDto, CreateContactDto, UpdateContactDto, contact_controller};

/// Create a new contact entity (orphan, no parent)
pub fn create_orphan_contact(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dto: &CreateContactDto,
) -> Result<ContactDto> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    contact_controller::create_orphan(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dto,
    )
    .context("creating contact")
}
/// Create a new contact entity as child of owner
pub fn create_contact(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dto: &CreateContactDto,
    owner_id: EntityId,
    index: i32,
) -> Result<ContactDto> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    contact_controller::create(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dto,
        owner_id,
        index,
    )
    .context("creating contact")
}
/// Create multiple contact entities (orphan, no parent)
pub fn create_orphan_contact_multi(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dtos: &[CreateContactDto],
) -> Result<Vec<ContactDto>> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    contact_controller::create_orphan_multi(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dtos,
    )
    .context("creating contact entities")
}
/// Create multiple contact entities as children of owner
pub fn create_contact_multi(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dtos: &[CreateContactDto],
    owner_id: EntityId,
    index: i32,
) -> Result<Vec<ContactDto>> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    contact_controller::create_multi(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dtos,
        owner_id,
        index,
    )
    .context("creating contact entities")
}
/// Get a contact entity by ID
pub fn get_contact(ctx: &AppContext, id: &EntityId) -> Result<Option<ContactDto>> {
    contact_controller::get(&ctx.db_context, id).context("getting contact")
}

/// Get multiple contact entities by IDs
pub fn get_contact_multi(ctx: &AppContext, ids: &[EntityId]) -> Result<Vec<Option<ContactDto>>> {
    contact_controller::get_multi(&ctx.db_context, ids).context("getting contact entities")
}

/// Get all contact entities.
/// Note: returns entities in database key order (by EntityId), not insertion order
/// or any user-defined sort. For ordered collections, use relationship-based
/// retrieval (e.g. get_*_relationship for ordered_one_to_many fields).
pub fn get_all_contact(ctx: &AppContext) -> Result<Vec<ContactDto>> {
    contact_controller::get_all(&ctx.db_context).context("getting all contact entities")
}

/// Update a contact entity
pub fn update_contact(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dto: &UpdateContactDto,
) -> Result<ContactDto> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    contact_controller::update(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dto,
    )
    .context("updating contact")
}

/// Update multiple contact entities
pub fn update_contact_multi(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dtos: &[UpdateContactDto],
) -> Result<Vec<ContactDto>> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    contact_controller::update_multi(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dtos,
    )
    .context("updating contact entities")
}

/// Update a contact entity with relationships
pub fn update_contact_with_relationships(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dto: &ContactDto,
) -> Result<ContactDto> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    contact_controller::update_with_relationships(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dto,
    )
    .context("updating contact with relationships")
}

/// Update multiple contact entities with relationships
pub fn update_contact_with_relationships_multi(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dtos: &[ContactDto],
) -> Result<Vec<ContactDto>> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    contact_controller::update_with_relationships_multi(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dtos,
    )
    .context("updating contact entities with relationships")
}

/// Remove a contact entity by ID
pub fn remove_contact(ctx: &AppContext, stack_id: Option<u64>, id: &EntityId) -> Result<()> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    contact_controller::remove(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        id,
    )
    .context("removing contact")
}

/// Remove multiple contact entities by IDs
pub fn remove_contact_multi(
    ctx: &AppContext,
    stack_id: Option<u64>,
    ids: &[EntityId],
) -> Result<()> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    contact_controller::remove_multi(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        ids,
    )
    .context("removing contact entities")
}
