// Generated by Qleany v1.5.5 from frontend_entity_commands.tera

//! Deal entity commands
#![allow(unused_imports, dead_code)]

use crate::app_context::AppContext;
use anyhow::{Context, Result};
use common::direct_access::deal::DealRelationshipField;
use common::types::EntityId;
use direct_access::DealRelationshipDto;
use direct_access::{CreateDealDto, DealDto, UpdateDealDto, deal_controller};

/// Create a new deal entity (orphan, no parent)
pub fn create_orphan_deal(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dto: &CreateDealDto,
) -> Result<DealDto> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    deal_controller::create_orphan(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dto,
    )
    .context("creating deal")
}
/// Create a new deal entity as child of owner
pub fn create_deal(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dto: &CreateDealDto,
    owner_id: EntityId,
    index: i32,
) -> Result<DealDto> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    deal_controller::create(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dto,
        owner_id,
        index,
    )
    .context("creating deal")
}
/// Create multiple deal entities (orphan, no parent)
pub fn create_orphan_deal_multi(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dtos: &[CreateDealDto],
) -> Result<Vec<DealDto>> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    deal_controller::create_orphan_multi(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dtos,
    )
    .context("creating deal entities")
}
/// Create multiple deal entities as children of owner
pub fn create_deal_multi(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dtos: &[CreateDealDto],
    owner_id: EntityId,
    index: i32,
) -> Result<Vec<DealDto>> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    deal_controller::create_multi(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dtos,
        owner_id,
        index,
    )
    .context("creating deal entities")
}
/// Get a deal entity by ID
pub fn get_deal(ctx: &AppContext, id: &EntityId) -> Result<Option<DealDto>> {
    deal_controller::get(&ctx.db_context, id).context("getting deal")
}

/// Get multiple deal entities by IDs
pub fn get_deal_multi(ctx: &AppContext, ids: &[EntityId]) -> Result<Vec<Option<DealDto>>> {
    deal_controller::get_multi(&ctx.db_context, ids).context("getting deal entities")
}

/// Get all deal entities.
/// Note: returns entities in database key order (by EntityId), not insertion order
/// or any user-defined sort. For ordered collections, use relationship-based
/// retrieval (e.g. get_*_relationship for ordered_one_to_many fields).
pub fn get_all_deal(ctx: &AppContext) -> Result<Vec<DealDto>> {
    deal_controller::get_all(&ctx.db_context).context("getting all deal entities")
}

/// Update a deal entity
pub fn update_deal(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dto: &UpdateDealDto,
) -> Result<DealDto> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    deal_controller::update(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dto,
    )
    .context("updating deal")
}

/// Update multiple deal entities
pub fn update_deal_multi(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dtos: &[UpdateDealDto],
) -> Result<Vec<DealDto>> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    deal_controller::update_multi(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dtos,
    )
    .context("updating deal entities")
}

/// Update a deal entity with relationships
pub fn update_deal_with_relationships(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dto: &DealDto,
) -> Result<DealDto> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    deal_controller::update_with_relationships(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dto,
    )
    .context("updating deal with relationships")
}

/// Update multiple deal entities with relationships
pub fn update_deal_with_relationships_multi(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dtos: &[DealDto],
) -> Result<Vec<DealDto>> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    deal_controller::update_with_relationships_multi(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dtos,
    )
    .context("updating deal entities with relationships")
}

/// Remove a deal entity by ID
pub fn remove_deal(ctx: &AppContext, stack_id: Option<u64>, id: &EntityId) -> Result<()> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    deal_controller::remove(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        id,
    )
    .context("removing deal")
}

/// Remove multiple deal entities by IDs
pub fn remove_deal_multi(ctx: &AppContext, stack_id: Option<u64>, ids: &[EntityId]) -> Result<()> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    deal_controller::remove_multi(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        ids,
    )
    .context("removing deal entities")
}

/// Get a deal relationship
pub fn get_deal_relationship(
    ctx: &AppContext,
    id: &EntityId,
    field: &DealRelationshipField,
) -> Result<Vec<EntityId>> {
    deal_controller::get_relationship(&ctx.db_context, id, field)
        .context("getting deal relationship")
}

/// Get relationship IDs for multiple deal entities at once
pub fn get_deal_relationship_many(
    ctx: &AppContext,
    ids: &[EntityId],
    field: &DealRelationshipField,
) -> Result<std::collections::HashMap<EntityId, Vec<EntityId>>> {
    deal_controller::get_relationship_many(&ctx.db_context, ids, field)
        .context("getting deal relationships (many)")
}

/// Get relationship count for a deal entity
pub fn get_deal_relationship_count(
    ctx: &AppContext,
    id: &EntityId,
    field: &DealRelationshipField,
) -> Result<usize> {
    deal_controller::get_relationship_count(&ctx.db_context, id, field)
        .context("getting deal relationship count")
}

/// Get relationship IDs for a deal entity with pagination
pub fn get_deal_relationship_in_range(
    ctx: &AppContext,
    id: &EntityId,
    field: &DealRelationshipField,
    offset: usize,
    limit: usize,
) -> Result<Vec<EntityId>> {
    deal_controller::get_relationship_in_range(&ctx.db_context, id, field, offset, limit)
        .context("getting deal relationship range")
}

/// Set a deal relationship
pub fn set_deal_relationship(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dto: &DealRelationshipDto,
) -> Result<()> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    deal_controller::set_relationship(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dto,
    )
    .context("setting deal relationship")
}

/// Move (reorder) IDs within a deal relationship
pub fn move_deal_relationship(
    ctx: &AppContext,
    stack_id: Option<u64>,
    id: &EntityId,
    field: &DealRelationshipField,
    ids_to_move: &[EntityId],
    new_index: i32,
) -> Result<Vec<EntityId>> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    deal_controller::move_relationship(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        id,
        field,
        ids_to_move,
        new_index,
    )
    .context("moving deal relationship")
}
