// Generated by Qleany v1.5.5 from frontend_feature_commands.tera

//! InventoryManagement feature commands

use crate::app_context::AppContext;
use anyhow::{Context, Result};
use inventory_management::{
    CheckStockLevelsDto, ExportProductsDto, ExportProductsReturnDto, ImportProductsDto,
    ImportProductsReturnDto, StockAlertDto, TransferStockDto, TransferStockReturnDto,
    inventory_management_controller,
};

use common::long_operation::OperationProgress;

/// import_products (long operation)
pub fn import_products(ctx: &AppContext, dto: &ImportProductsDto) -> Result<String> {
    inventory_management_controller::import_products(
        &ctx.db_context,
        &ctx.event_hub,
        &mut ctx.long_operation_manager.lock().unwrap(),
        dto,
    )
    .context("import_products")
}

/// Get the progress of a import_products operation
pub fn get_import_products_progress(
    ctx: &AppContext,
    operation_id: &str,
) -> Option<OperationProgress> {
    inventory_management_controller::get_import_products_progress(
        &ctx.long_operation_manager.lock().unwrap(),
        operation_id,
    )
}

/// Get the result of a import_products operation
pub fn get_import_products_result(
    ctx: &AppContext,
    operation_id: &str,
) -> Result<Option<ImportProductsReturnDto>> {
    inventory_management_controller::get_import_products_result(
        &ctx.long_operation_manager.lock().unwrap(),
        operation_id,
    )
    .context("getting import_products result")
}

pub fn export_products(
    ctx: &AppContext,
    dto: &ExportProductsDto,
) -> Result<ExportProductsReturnDto> {
    inventory_management_controller::export_products(&ctx.db_context, &ctx.event_hub, dto)
        .context("export_products")
}

pub fn check_stock_levels(ctx: &AppContext, dto: &CheckStockLevelsDto) -> Result<StockAlertDto> {
    inventory_management_controller::check_stock_levels(&ctx.db_context, &ctx.event_hub, dto)
        .context("check_stock_levels")
}

pub fn transfer_stock(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dto: &TransferStockDto,
) -> Result<TransferStockReturnDto> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    inventory_management_controller::transfer_stock(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dto,
    )
    .context("transfer_stock")
}
