// Generated by Qleany v1.5.5 from frontend_entity_commands.tera

//! Person entity commands
#![allow(unused_imports, dead_code)]

use crate::app_context::AppContext;
use anyhow::{Context, Result};
use common::direct_access::person::PersonRelationshipField;
use common::types::EntityId;
use direct_access::PersonRelationshipDto;
use direct_access::{CreatePersonDto, PersonDto, UpdatePersonDto, person_controller};

/// Create a new person entity (orphan, no parent)
pub fn create_orphan_person(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dto: &CreatePersonDto,
) -> Result<PersonDto> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    person_controller::create_orphan(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dto,
    )
    .context("creating person")
}
/// Create a new person entity as child of owner
pub fn create_person(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dto: &CreatePersonDto,
    owner_id: EntityId,
    index: i32,
) -> Result<PersonDto> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    person_controller::create(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dto,
        owner_id,
        index,
    )
    .context("creating person")
}
/// Create multiple person entities (orphan, no parent)
pub fn create_orphan_person_multi(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dtos: &[CreatePersonDto],
) -> Result<Vec<PersonDto>> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    person_controller::create_orphan_multi(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dtos,
    )
    .context("creating person entities")
}
/// Create multiple person entities as children of owner
pub fn create_person_multi(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dtos: &[CreatePersonDto],
    owner_id: EntityId,
    index: i32,
) -> Result<Vec<PersonDto>> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    person_controller::create_multi(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dtos,
        owner_id,
        index,
    )
    .context("creating person entities")
}
/// Get a person entity by ID
pub fn get_person(ctx: &AppContext, id: &EntityId) -> Result<Option<PersonDto>> {
    person_controller::get(&ctx.db_context, id).context("getting person")
}

/// Get multiple person entities by IDs
pub fn get_person_multi(ctx: &AppContext, ids: &[EntityId]) -> Result<Vec<Option<PersonDto>>> {
    person_controller::get_multi(&ctx.db_context, ids).context("getting person entities")
}

/// Get all person entities.
/// Note: returns entities in database key order (by EntityId), not insertion order
/// or any user-defined sort. For ordered collections, use relationship-based
/// retrieval (e.g. get_*_relationship for ordered_one_to_many fields).
pub fn get_all_person(ctx: &AppContext) -> Result<Vec<PersonDto>> {
    person_controller::get_all(&ctx.db_context).context("getting all person entities")
}

/// Update a person entity
pub fn update_person(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dto: &UpdatePersonDto,
) -> Result<PersonDto> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    person_controller::update(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dto,
    )
    .context("updating person")
}

/// Update multiple person entities
pub fn update_person_multi(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dtos: &[UpdatePersonDto],
) -> Result<Vec<PersonDto>> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    person_controller::update_multi(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dtos,
    )
    .context("updating person entities")
}

/// Update a person entity with relationships
pub fn update_person_with_relationships(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dto: &PersonDto,
) -> Result<PersonDto> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    person_controller::update_with_relationships(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dto,
    )
    .context("updating person with relationships")
}

/// Update multiple person entities with relationships
pub fn update_person_with_relationships_multi(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dtos: &[PersonDto],
) -> Result<Vec<PersonDto>> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    person_controller::update_with_relationships_multi(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dtos,
    )
    .context("updating person entities with relationships")
}

/// Remove a person entity by ID
pub fn remove_person(ctx: &AppContext, stack_id: Option<u64>, id: &EntityId) -> Result<()> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    person_controller::remove(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        id,
    )
    .context("removing person")
}

/// Remove multiple person entities by IDs
pub fn remove_person_multi(
    ctx: &AppContext,
    stack_id: Option<u64>,
    ids: &[EntityId],
) -> Result<()> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    person_controller::remove_multi(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        ids,
    )
    .context("removing person entities")
}

/// Get a person relationship
pub fn get_person_relationship(
    ctx: &AppContext,
    id: &EntityId,
    field: &PersonRelationshipField,
) -> Result<Vec<EntityId>> {
    person_controller::get_relationship(&ctx.db_context, id, field)
        .context("getting person relationship")
}

/// Get relationship IDs for multiple person entities at once
pub fn get_person_relationship_many(
    ctx: &AppContext,
    ids: &[EntityId],
    field: &PersonRelationshipField,
) -> Result<std::collections::HashMap<EntityId, Vec<EntityId>>> {
    person_controller::get_relationship_many(&ctx.db_context, ids, field)
        .context("getting person relationships (many)")
}

/// Get relationship count for a person entity
pub fn get_person_relationship_count(
    ctx: &AppContext,
    id: &EntityId,
    field: &PersonRelationshipField,
) -> Result<usize> {
    person_controller::get_relationship_count(&ctx.db_context, id, field)
        .context("getting person relationship count")
}

/// Get relationship IDs for a person entity with pagination
pub fn get_person_relationship_in_range(
    ctx: &AppContext,
    id: &EntityId,
    field: &PersonRelationshipField,
    offset: usize,
    limit: usize,
) -> Result<Vec<EntityId>> {
    person_controller::get_relationship_in_range(&ctx.db_context, id, field, offset, limit)
        .context("getting person relationship range")
}

/// Set a person relationship
pub fn set_person_relationship(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dto: &PersonRelationshipDto,
) -> Result<()> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    person_controller::set_relationship(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dto,
    )
    .context("setting person relationship")
}

/// Move (reorder) IDs within a person relationship
pub fn move_person_relationship(
    ctx: &AppContext,
    stack_id: Option<u64>,
    id: &EntityId,
    field: &PersonRelationshipField,
    ids_to_move: &[EntityId],
    new_index: i32,
) -> Result<Vec<EntityId>> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    person_controller::move_relationship(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        id,
        field,
        ids_to_move,
        new_index,
    )
    .context("moving person relationship")
}
