// Generated by Qleany v1.5.5 from frontend_entity_commands.tera

//! Product entity commands
#![allow(unused_imports, dead_code)]

use crate::app_context::AppContext;
use anyhow::{Context, Result};
use common::direct_access::product::ProductRelationshipField;
use common::types::EntityId;
use direct_access::ProductRelationshipDto;
use direct_access::{CreateProductDto, ProductDto, UpdateProductDto, product_controller};

/// Create a new product entity (orphan, no parent)
pub fn create_orphan_product(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dto: &CreateProductDto,
) -> Result<ProductDto> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    product_controller::create_orphan(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dto,
    )
    .context("creating product")
}
/// Create a new product entity as child of owner
pub fn create_product(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dto: &CreateProductDto,
    owner_id: EntityId,
    index: i32,
) -> Result<ProductDto> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    product_controller::create(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dto,
        owner_id,
        index,
    )
    .context("creating product")
}
/// Create multiple product entities (orphan, no parent)
pub fn create_orphan_product_multi(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dtos: &[CreateProductDto],
) -> Result<Vec<ProductDto>> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    product_controller::create_orphan_multi(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dtos,
    )
    .context("creating product entities")
}
/// Create multiple product entities as children of owner
pub fn create_product_multi(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dtos: &[CreateProductDto],
    owner_id: EntityId,
    index: i32,
) -> Result<Vec<ProductDto>> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    product_controller::create_multi(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dtos,
        owner_id,
        index,
    )
    .context("creating product entities")
}
/// Get a product entity by ID
pub fn get_product(ctx: &AppContext, id: &EntityId) -> Result<Option<ProductDto>> {
    product_controller::get(&ctx.db_context, id).context("getting product")
}

/// Get multiple product entities by IDs
pub fn get_product_multi(ctx: &AppContext, ids: &[EntityId]) -> Result<Vec<Option<ProductDto>>> {
    product_controller::get_multi(&ctx.db_context, ids).context("getting product entities")
}

/// Get all product entities.
/// Note: returns entities in database key order (by EntityId), not insertion order
/// or any user-defined sort. For ordered collections, use relationship-based
/// retrieval (e.g. get_*_relationship for ordered_one_to_many fields).
pub fn get_all_product(ctx: &AppContext) -> Result<Vec<ProductDto>> {
    product_controller::get_all(&ctx.db_context).context("getting all product entities")
}

/// Update a product entity
pub fn update_product(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dto: &UpdateProductDto,
) -> Result<ProductDto> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    product_controller::update(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dto,
    )
    .context("updating product")
}

/// Update multiple product entities
pub fn update_product_multi(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dtos: &[UpdateProductDto],
) -> Result<Vec<ProductDto>> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    product_controller::update_multi(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dtos,
    )
    .context("updating product entities")
}

/// Update a product entity with relationships
pub fn update_product_with_relationships(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dto: &ProductDto,
) -> Result<ProductDto> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    product_controller::update_with_relationships(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dto,
    )
    .context("updating product with relationships")
}

/// Update multiple product entities with relationships
pub fn update_product_with_relationships_multi(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dtos: &[ProductDto],
) -> Result<Vec<ProductDto>> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    product_controller::update_with_relationships_multi(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dtos,
    )
    .context("updating product entities with relationships")
}

/// Remove a product entity by ID
pub fn remove_product(ctx: &AppContext, stack_id: Option<u64>, id: &EntityId) -> Result<()> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    product_controller::remove(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        id,
    )
    .context("removing product")
}

/// Remove multiple product entities by IDs
pub fn remove_product_multi(
    ctx: &AppContext,
    stack_id: Option<u64>,
    ids: &[EntityId],
) -> Result<()> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    product_controller::remove_multi(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        ids,
    )
    .context("removing product entities")
}

/// Get a product relationship
pub fn get_product_relationship(
    ctx: &AppContext,
    id: &EntityId,
    field: &ProductRelationshipField,
) -> Result<Vec<EntityId>> {
    product_controller::get_relationship(&ctx.db_context, id, field)
        .context("getting product relationship")
}

/// Get relationship IDs for multiple product entities at once
pub fn get_product_relationship_many(
    ctx: &AppContext,
    ids: &[EntityId],
    field: &ProductRelationshipField,
) -> Result<std::collections::HashMap<EntityId, Vec<EntityId>>> {
    product_controller::get_relationship_many(&ctx.db_context, ids, field)
        .context("getting product relationships (many)")
}

/// Get relationship count for a product entity
pub fn get_product_relationship_count(
    ctx: &AppContext,
    id: &EntityId,
    field: &ProductRelationshipField,
) -> Result<usize> {
    product_controller::get_relationship_count(&ctx.db_context, id, field)
        .context("getting product relationship count")
}

/// Get relationship IDs for a product entity with pagination
pub fn get_product_relationship_in_range(
    ctx: &AppContext,
    id: &EntityId,
    field: &ProductRelationshipField,
    offset: usize,
    limit: usize,
) -> Result<Vec<EntityId>> {
    product_controller::get_relationship_in_range(&ctx.db_context, id, field, offset, limit)
        .context("getting product relationship range")
}

/// Set a product relationship
pub fn set_product_relationship(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dto: &ProductRelationshipDto,
) -> Result<()> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    product_controller::set_relationship(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dto,
    )
    .context("setting product relationship")
}

/// Move (reorder) IDs within a product relationship
pub fn move_product_relationship(
    ctx: &AppContext,
    stack_id: Option<u64>,
    id: &EntityId,
    field: &ProductRelationshipField,
    ids_to_move: &[EntityId],
    new_index: i32,
) -> Result<Vec<EntityId>> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    product_controller::move_relationship(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        id,
        field,
        ids_to_move,
        new_index,
    )
    .context("moving product relationship")
}
