// Generated by Qleany v1.5.5 from frontend_feature_commands.tera
// Modified: pass SecurityContext to controller functions

//! Purchasing feature commands

use crate::app_context::AppContext;
use anyhow::{Context, Result};
use inventory_security::SecurityContext;
use purchasing::{
    ActiveDealsDto, CreatePurchaseDealDto, CreatePurchaseDealReturnDto, DealListDto,
    GetDealsBySupplierDto, purchasing_controller,
};

pub fn create_purchase_deal(
    ctx: &AppContext,
    stack_id: Option<u64>,
    security_context: &SecurityContext,
    dto: &CreatePurchaseDealDto,
) -> Result<CreatePurchaseDealReturnDto> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    purchasing_controller::create_purchase_deal(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        security_context,
        dto,
    )
    .context("create_purchase_deal")
}

pub fn get_deals_by_supplier(
    ctx: &AppContext,
    security_context: &SecurityContext,
    dto: &GetDealsBySupplierDto,
) -> Result<DealListDto> {
    purchasing_controller::get_deals_by_supplier(
        &ctx.db_context,
        &ctx.event_hub,
        security_context,
        dto,
    )
    .context("get_deals_by_supplier")
}

pub fn get_active_deals(
    ctx: &AppContext,
    security_context: &SecurityContext,
) -> Result<ActiveDealsDto> {
    purchasing_controller::get_active_deals(
        &ctx.db_context,
        &ctx.event_hub,
        security_context,
    )
    .context("get_active_deals")
}
