// Generated by Qleany v1.5.5 from frontend_feature_commands.tera

//! StockTracking feature commands

use crate::app_context::AppContext;
use anyhow::{Context, Result};
use inventory_security::SecurityContext;
use stock_tracking::{
    GetStockHistoryDto, RecordStockMovementDto, RecordStockMovementResultDto, StockHistoryDto,
    StockSummaryDto, stock_tracking_controller,
};

pub fn record_stock_movement(
    ctx: &AppContext,
    security_context: &SecurityContext,
    dto: &RecordStockMovementDto,
) -> Result<RecordStockMovementResultDto> {
    stock_tracking_controller::record_stock_movement(
        &ctx.db_context,
        &ctx.event_hub,
        security_context,
        dto,
    )
    .context("record_stock_movement")
}

pub fn get_stock_history(
    ctx: &AppContext,
    security_context: &SecurityContext,
    dto: &GetStockHistoryDto,
) -> Result<StockHistoryDto> {
    stock_tracking_controller::get_stock_history(
        &ctx.db_context,
        &ctx.event_hub,
        security_context,
        dto,
    )
    .context("get_stock_history")
}

pub fn get_stock_summary(
    ctx: &AppContext,
    security_context: &SecurityContext,
) -> Result<StockSummaryDto> {
    stock_tracking_controller::get_stock_summary(
        &ctx.db_context,
        &ctx.event_hub,
        security_context,
    )
    .context("get_stock_summary")
}
