// Generated by Qleany v1.5.5 from frontend_feature_commands.tera

//! UserManagement feature commands

use crate::app_context::AppContext;
use anyhow::{Context, Result};
use user_management::{
    CreateUserDto, CreateUserResultDto, DeactivateUserDto, UserListDto, user_management_controller,
};

pub fn create_user(ctx: &AppContext, dto: &CreateUserDto) -> Result<CreateUserResultDto> {
    user_management_controller::create_user(&ctx.db_context, &ctx.event_hub, dto)
        .context("create_user")
}

pub fn deactivate_user(ctx: &AppContext, dto: &DeactivateUserDto) -> Result<()> {
    user_management_controller::deactivate_user(&ctx.db_context, &ctx.event_hub, dto)
        .context("deactivate_user")
}

pub fn list_users(ctx: &AppContext) -> Result<UserListDto> {
    user_management_controller::list_users(&ctx.db_context, &ctx.event_hub).context("list_users")
}
