// Generated by Qleany v1.5.5 from feature_use_case.tera
use crate::ExportProductsDto;
use crate::ExportProductsReturnDto;
use anyhow::{Result, anyhow};
use common::database::QueryUnitOfWork;
use common::entities::{Category, Location, Person, Product, Root};
use common::types::EntityId;

pub trait ExportProductsUnitOfWorkFactoryTrait: Send + Sync {
    fn create(&self) -> Box<dyn ExportProductsUnitOfWorkTrait>;
}

//TODO: adapt entities and actions to real use :
// GetRO, GetMultiRO, GetRelationship, GetRelationshipRO,
// GetRelationshipsFromRightIdsRO
//
// You have here a read-only unit of work trait.
//
// RO means Read Only, so *RO actions should be used here.
// Do not mix read-only and write actions in the same unit of work.
//
// Exactly the same macros must be set in the use case uow trait file in ../units_of_work/export_products_uow.rs
//
#[macros::uow_action(entity = "Root", action = "GetRO")]
#[macros::uow_action(entity = "Root", action = "GetMultiRO")]
#[macros::uow_action(entity = "Product", action = "GetRO")]
#[macros::uow_action(entity = "Product", action = "GetMultiRO")]
#[macros::uow_action(entity = "Category", action = "GetRO")]
#[macros::uow_action(entity = "Category", action = "GetMultiRO")]
#[macros::uow_action(entity = "Person", action = "GetRO")]
#[macros::uow_action(entity = "Person", action = "GetMultiRO")]
#[macros::uow_action(entity = "Location", action = "GetRO")]
#[macros::uow_action(entity = "Location", action = "GetMultiRO")]
pub trait ExportProductsUnitOfWorkTrait: QueryUnitOfWork {}

pub struct ExportProductsUseCase {
    uow_factory: Box<dyn ExportProductsUnitOfWorkFactoryTrait>,
}

impl ExportProductsUseCase {
    pub fn new(uow_factory: Box<dyn ExportProductsUnitOfWorkFactoryTrait>) -> Self {
        ExportProductsUseCase { uow_factory }
    }

    pub fn execute(&mut self, dto: &ExportProductsDto) -> Result<ExportProductsReturnDto> {
        let mut uow = self.uow_factory.create();
        uow.begin_transaction()?;

        //TODO: ExportProductsUseCase to be implemented
        unimplemented!("ExportProductsUseCase unimplemented");
        uow.end_transaction()?;
        //Ok(ExportProductsReturnDto {
        //
        //})
        // placeholder to allow compilation
        Err(anyhow!("Not implemented"))
    }
}
