// Generated by Qleany v1.5.5 from feature_use_case.tera
use crate::ImportProductsDto;
use crate::ImportProductsReturnDto;
use anyhow::{Result, anyhow};
use common::database::CommandUnitOfWork;
use common::entities::{Category, Location, Person, Product, Root};
use common::long_operation::LongOperation;
use common::types::EntityId;
use std::sync::Arc;

pub trait ImportProductsUnitOfWorkFactoryTrait: Send + Sync {
    fn create(&self) -> Box<dyn ImportProductsUnitOfWorkTrait>;
}
//TODO: adapt entities and actions to real use :
// Create, CreateMulti, Get, GetMulti, Update (scalar-only), UpdateMulti (scalar-only),
// UpdateWithRelationships, UpdateWithRelationshipsMulti,
// Remove, RemoveMulti, GetRelationship, GetRelationshipsFromRightIds,
// SetRelationship, SetRelationshipMulti
//
// You have here a read-write unit of work.
//
// RO means Read Only.
// Do not mix read-only and write actions in the same unit of work.
//
// Exactly the same macros must be set in the use case uow trait file in ../units_of_work/import_products_uow.rs
//
#[macros::uow_action(entity = "Root", action = "Get")]
#[macros::uow_action(entity = "Root", action = "GetMulti")]
#[macros::uow_action(entity = "Root", action = "Snapshot")]
#[macros::uow_action(entity = "Root", action = "Restore")]
#[macros::uow_action(entity = "Product", action = "Get")]
#[macros::uow_action(entity = "Product", action = "GetMulti")]
#[macros::uow_action(entity = "Product", action = "Snapshot")]
#[macros::uow_action(entity = "Product", action = "Restore")]
#[macros::uow_action(entity = "Category", action = "Get")]
#[macros::uow_action(entity = "Category", action = "GetMulti")]
#[macros::uow_action(entity = "Category", action = "Snapshot")]
#[macros::uow_action(entity = "Category", action = "Restore")]
#[macros::uow_action(entity = "Person", action = "Get")]
#[macros::uow_action(entity = "Person", action = "GetMulti")]
#[macros::uow_action(entity = "Person", action = "Snapshot")]
#[macros::uow_action(entity = "Person", action = "Restore")]
#[macros::uow_action(entity = "Location", action = "Get")]
#[macros::uow_action(entity = "Location", action = "GetMulti")]
#[macros::uow_action(entity = "Location", action = "Snapshot")]
#[macros::uow_action(entity = "Location", action = "Restore")]
pub trait ImportProductsUnitOfWorkTrait: CommandUnitOfWork + Send + Sync {}

pub struct ImportProductsUseCase {
    uow_factory: Box<dyn ImportProductsUnitOfWorkFactoryTrait>,
    dto: ImportProductsDto,
}

impl ImportProductsUseCase {
    pub fn new(
        uow_factory: Box<dyn ImportProductsUnitOfWorkFactoryTrait>,
        dto: &ImportProductsDto,
    ) -> Self {
        ImportProductsUseCase {
            uow_factory,
            dto: dto.clone(),
        }
    }
}
impl LongOperation for ImportProductsUseCase {
    type Output = ImportProductsReturnDto;

    fn execute(
        &self,
        progress_callback: Box<dyn Fn(common::long_operation::OperationProgress) + Send>,
        cancel_flag: Arc<std::sync::atomic::AtomicBool>,
    ) -> Result<Self::Output> {
        use std::sync::atomic::Ordering;

        progress_callback(common::long_operation::OperationProgress::new(
            0.0,
            Some("Starting...".to_string()),
        ));

        let mut uow = self.uow_factory.create();
        uow.begin_transaction()?;

        //TODO: ImportProductsUseCase to be implemented
        unimplemented!("ImportProductsUseCase unimplemented");

        if cancel_flag.load(Ordering::Relaxed) {
            uow.rollback()?;
            return Err(anyhow!("Operation was cancelled"));
        }
        uow.commit()?;

        // Final progress
        progress_callback(common::long_operation::OperationProgress::new(
            100.0,
            Some("completed".to_string()),
        ));
        //Ok(ImportProductsReturnDto {
        //
        //})
        // placeholder to allow compilation
        Err(anyhow!("Not implemented"))
    }
}
