// Generated by Qleany v1.5.5 from feature_use_case.tera
use crate::TransferStockDto;
use crate::TransferStockReturnDto;
use anyhow::{Result, anyhow};
use common::database::CommandUnitOfWork;
use common::entities::{Location, Product};
use common::types::EntityId;

pub trait TransferStockUnitOfWorkFactoryTrait: Send + Sync {
    fn create(&self) -> Box<dyn TransferStockUnitOfWorkTrait>;
}

//TODO: adapt entities and actions to real use :
// Create, CreateMulti, Get, GetMulti, Update (scalar-only), UpdateMulti (scalar-only),
// UpdateWithRelationships, UpdateWithRelationshipsMulti,
// Remove, RemoveMulti, GetRelationship, GetRelationshipsFromRightIds,
// SetRelationship, SetRelationshipMulti
//
// You have here a read-write unit of work trait.
//
// RO means Read Only.
// Do not mix read-only and write actions in the same unit of work.
//
// Exactly the same macros must be set in the use case uow trait file in ../units_of_work/transfer_stock_uow.rs
//
#[macros::uow_action(entity = "Product", action = "Get")]
#[macros::uow_action(entity = "Product", action = "GetMulti")]
#[macros::uow_action(entity = "Product", action = "Snapshot")]
#[macros::uow_action(entity = "Product", action = "Restore")]
#[macros::uow_action(entity = "Location", action = "Get")]
#[macros::uow_action(entity = "Location", action = "GetMulti")]
#[macros::uow_action(entity = "Location", action = "Snapshot")]
#[macros::uow_action(entity = "Location", action = "Restore")]
pub trait TransferStockUnitOfWorkTrait: CommandUnitOfWork {}

pub struct TransferStockUseCase {
    uow_factory: Box<dyn TransferStockUnitOfWorkFactoryTrait>,
}

impl TransferStockUseCase {
    pub fn new(uow_factory: Box<dyn TransferStockUnitOfWorkFactoryTrait>) -> Self {
        TransferStockUseCase { uow_factory }
    }

    pub fn execute(&mut self, dto: &TransferStockDto) -> Result<TransferStockReturnDto> {
        let mut uow = self.uow_factory.create();
        uow.begin_transaction()?;

        //TODO: TransferStockUseCase to be implemented
        unimplemented!("TransferStockUseCase unimplemented");
        uow.commit()?;
        //Ok(TransferStockReturnDto {
        //
        //})
        // placeholder to allow compilation
        Err(anyhow!("Not implemented"))
    }
}
use common::undo_redo::UndoRedoCommand;
use std::any::Any;
impl UndoRedoCommand for TransferStockUseCase {
    fn undo(&mut self) -> Result<()> {
        //TODO: TransferStockUseCase  undo to be implemented
        unimplemented!("TransferStockUseCase undo unimplemented");

        Ok(())
    }

    fn redo(&mut self) -> Result<()> {
        //TODO: TransferStockUseCase  redo to be implemented
        unimplemented!("TransferStockUseCase redo unimplemented");

        Ok(())
    }
    fn as_any(&self) -> &dyn Any {
        self
    }
}
