// Generated by Qleany v1.5.5 from feature_use_case.tera
use crate::TransferStockDto;
use crate::TransferStockReturnDto;
use crate::error::TransferError;
use anyhow::{Result, anyhow};
use common::database::CommandUnitOfWork;
use common::entities::{Location, MovementType, Product, Root, StockMovement};
use common::types::EntityId;

pub trait TransferStockUnitOfWorkFactoryTrait: Send + Sync {
    fn create(&self) -> Box<dyn TransferStockUnitOfWorkTrait>;
}

// Exactly the same macros must be set in the use case uow trait file in ../units_of_work/transfer_stock_uow.rs
#[macros::uow_action(entity = "Root", action = "Get")]
#[macros::uow_action(entity = "Product", action = "Get")]
#[macros::uow_action(entity = "Product", action = "GetMulti")]
#[macros::uow_action(entity = "Product", action = "Update")]
#[macros::uow_action(entity = "Product", action = "Snapshot")]
#[macros::uow_action(entity = "Product", action = "Restore")]
#[macros::uow_action(entity = "Location", action = "Get")]
#[macros::uow_action(entity = "Location", action = "GetMulti")]
#[macros::uow_action(entity = "Location", action = "Snapshot")]
#[macros::uow_action(entity = "Location", action = "Restore")]
#[macros::uow_action(entity = "StockMovement", action = "Create")]
pub trait TransferStockUnitOfWorkTrait: CommandUnitOfWork {}

pub struct TransferStockUseCase {
    uow_factory: Box<dyn TransferStockUnitOfWorkFactoryTrait>,
    dto: Option<TransferStockDto>,
    /// Savepoint captured before the transfer for undo support
    savepoint: Option<common::types::Savepoint>,
}

impl TransferStockUseCase {
    pub fn new(uow_factory: Box<dyn TransferStockUnitOfWorkFactoryTrait>) -> Self {
        TransferStockUseCase {
            uow_factory,
            dto: None,
            savepoint: None,
        }
    }

    pub fn execute(&mut self, dto: &TransferStockDto) -> Result<TransferStockReturnDto> {
        self.dto = Some(dto.clone());

        // 1. Validate: quantity > 0
        if dto.quantity <= 0 {
            return Err(TransferError::InvalidQuantity.into());
        }

        // 2. Validate: from != to
        if dto.from_location_id == dto.to_location_id {
            return Err(TransferError::SameLocation.into());
        }

        let mut uow = self.uow_factory.create();
        uow.begin_transaction()?;

        // Create savepoint for undo
        self.savepoint = Some(uow.create_savepoint()?);

        // 3. Load Product
        let product = uow.get_product(&(dto.product_id as EntityId))?
            .ok_or(TransferError::ProductNotFound { id: dto.product_id })?;

        // 4. Load source and destination Locations (verify they exist)
        let _from_location = uow.get_location(&(dto.from_location_id as EntityId))?
            .ok_or(TransferError::LocationNotFound { id: dto.from_location_id })?;
        let _to_location = uow.get_location(&(dto.to_location_id as EntityId))?
            .ok_or(TransferError::LocationNotFound { id: dto.to_location_id })?;

        // 5. Check sufficient stock
        if product.quantity < dto.quantity {
            return Err(TransferError::InsufficientStock {
                available: product.quantity,
                requested: dto.quantity,
            }.into());
        }

        // 6. Update product quantity
        let new_quantity_at_source = product.quantity - dto.quantity;
        let new_quantity_at_dest = dto.quantity; // simplified: product tracks total quantity

        let mut updated_product = product.clone();
        updated_product.quantity = new_quantity_at_source;
        uow.update_product(&updated_product)?;

        // 7. Record StockMovement
        let root = uow.get_root(&1)?
            .ok_or_else(|| anyhow!("Root entity not found"))?;

        let stock_movement = StockMovement {
            id: 0,
            movement_type: MovementType::Transfer,
            quantity: dto.quantity,
            note: format!(
                "Transfer of {} units of product {}",
                dto.quantity, dto.product_id
            ),
            product: Some(dto.product_id as EntityId),
            from_location: Some(dto.from_location_id as EntityId),
            to_location: Some(dto.to_location_id as EntityId),
            performed_by: None, // would be set from security context in production
            ..Default::default()
        };
        uow.create_stock_movement(&stock_movement, root.id, -1)?;

        uow.commit()?;

        Ok(TransferStockReturnDto {
            success: true,
            new_quantity_at_source,
            new_quantity_at_dest,
        })
    }
}

use common::undo_redo::UndoRedoCommand;
use std::any::Any;

impl UndoRedoCommand for TransferStockUseCase {
    fn undo(&mut self) -> Result<()> {
        // Undo by re-executing the reverse transfer
        let dto = self.dto.as_ref()
            .ok_or_else(|| anyhow!("No transfer to undo"))?
            .clone();

        let mut uow = self.uow_factory.create();
        uow.begin_transaction()?;

        // Load product and reverse the quantity change
        let product = uow.get_product(&(dto.product_id as EntityId))?
            .ok_or(TransferError::ProductNotFound { id: dto.product_id })?;

        let mut updated_product = product.clone();
        updated_product.quantity += dto.quantity; // restore the quantity
        uow.update_product(&updated_product)?;

        uow.commit()?;
        Ok(())
    }

    fn redo(&mut self) -> Result<()> {
        // Redo by re-applying the transfer
        let dto = self.dto.as_ref()
            .ok_or_else(|| anyhow!("No transfer to redo"))?
            .clone();

        let mut uow = self.uow_factory.create();
        uow.begin_transaction()?;

        let product = uow.get_product(&(dto.product_id as EntityId))?
            .ok_or(TransferError::ProductNotFound { id: dto.product_id })?;

        let mut updated_product = product.clone();
        updated_product.quantity -= dto.quantity;
        uow.update_product(&updated_product)?;

        uow.commit()?;
        Ok(())
    }

    fn as_any(&self) -> &dyn Any {
        self
    }
}
