// Generated by Qleany v1.5.5 from feature_use_case.tera
use crate::CreateUserDto;
use crate::CreateUserResultDto;
use anyhow::{Result, anyhow};
use common::database::CommandUnitOfWork;
use common::entities::{Root, User};
use common::types::EntityId;

pub trait CreateUserUnitOfWorkFactoryTrait: Send + Sync {
    fn create(&self) -> Box<dyn CreateUserUnitOfWorkTrait>;
}

//TODO: adapt entities and actions to real use :
// Create, CreateMulti, Get, GetMulti, Update (scalar-only), UpdateMulti (scalar-only),
// UpdateWithRelationships, UpdateWithRelationshipsMulti,
// Remove, RemoveMulti, GetRelationship, GetRelationshipsFromRightIds,
// SetRelationship, SetRelationshipMulti
//
// You have here a read-write unit of work trait.
//
// RO means Read Only.
// Do not mix read-only and write actions in the same unit of work.
//
// Exactly the same macros must be set in the use case uow trait file in ../units_of_work/create_user_uow.rs
//
#[macros::uow_action(entity = "Root", action = "Get")]
#[macros::uow_action(entity = "Root", action = "GetMulti")]
#[macros::uow_action(entity = "Root", action = "Snapshot")]
#[macros::uow_action(entity = "Root", action = "Restore")]
#[macros::uow_action(entity = "User", action = "Get")]
#[macros::uow_action(entity = "User", action = "GetMulti")]
#[macros::uow_action(entity = "User", action = "Snapshot")]
#[macros::uow_action(entity = "User", action = "Restore")]
pub trait CreateUserUnitOfWorkTrait: CommandUnitOfWork {}

pub struct CreateUserUseCase {
    uow_factory: Box<dyn CreateUserUnitOfWorkFactoryTrait>,
}

impl CreateUserUseCase {
    pub fn new(uow_factory: Box<dyn CreateUserUnitOfWorkFactoryTrait>) -> Self {
        CreateUserUseCase { uow_factory }
    }

    pub fn execute(&mut self, dto: &CreateUserDto) -> Result<CreateUserResultDto> {
        let mut uow = self.uow_factory.create();
        uow.begin_transaction()?;

        //TODO: CreateUserUseCase to be implemented
        unimplemented!("CreateUserUseCase unimplemented");
        uow.commit()?;
        //Ok(CreateUserResultDto {
        //
        //})
        // placeholder to allow compilation
        Err(anyhow!("Not implemented"))
    }
}
