// Generated by Qleany v1.5.5 from feature_dtos.tera

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct RecordStockMovementDto {
    pub product_id: i64,
    pub movement_type: MovementTypeInput,
    pub quantity: i64,
    pub from_location_id: i64,
    pub to_location_id: i64,
    pub note: String,
}

#[derive(Serialize, Deserialize, Default, Clone, Debug, PartialEq)]
pub enum MovementTypeInput {
    #[default]
    Inbound,
    Outbound,
    Transfer,
    Adjustment,
    Return,
}
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct RecordStockMovementResultDto {
    pub movement_id: i64,
    pub new_product_quantity: i64,
}
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetStockHistoryDto {
    pub product_id: i64,
    pub from_date: chrono::DateTime<chrono::Utc>,
    pub to_date: chrono::DateTime<chrono::Utc>,
}
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct StockHistoryDto {
    pub movement_ids: Vec<i64>,
    pub movement_types: Vec<String>,
    pub quantities: Vec<i64>,
    pub dates: Vec<String>,
    pub running_totals: Vec<i64>,
}
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct StockSummaryDto {
    pub product_ids: Vec<i64>,
    pub product_names: Vec<String>,
    pub current_quantities: Vec<i64>,
    pub inbound_30d: Vec<i64>,
    pub outbound_30d: Vec<i64>,
}
