/*
 * ChaOffice API
 * API definition for the ChaOffice project, a distributed platform for data and communication management in small and medium-sized enterprises (SMEs).
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.Objects;

/**
 * Cluster
 */
@javax.annotation.processing.Generated(
    value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen",
    date = "2025-03-30T15:15:44.636736291Z[GMT]")
public class Cluster {
  @SerializedName("id")
  private String id = null;

  @SerializedName("cluster_name")
  private String clusterName = null;

  /**
   * Unique identifier for the cluster.
   * @return id
   **/
  @Schema(description = "Unique identifier for the cluster.")
  public String getId() {
    return id;
  }

  public Cluster clusterName(String clusterName) {
    this.clusterName = clusterName;
    return this;
  }

  /**
   * Name of the cluster.
   * @return clusterName
   **/
  @Schema(description = "Name of the cluster.")
  public String getClusterName() {
    return clusterName;
  }

  public void setClusterName(String clusterName) {
    this.clusterName = clusterName;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Cluster cluster = (Cluster) o;
    return Objects.equals(this.id, cluster.id)
        && Objects.equals(this.clusterName, cluster.clusterName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, clusterName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Cluster {\n");

    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    clusterName: ").append(toIndentedString(clusterName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
