/*
 * ChaOffice API
 * API definition for the ChaOffice project, a distributed platform for data and communication management in small and medium-sized enterprises (SMEs).
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import java.time.OffsetDateTime;
import java.util.Objects;

/**
 * OTP
 */
@javax.annotation.processing.Generated(
    value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen",
    date = "2025-03-30T15:15:44.636736291Z[GMT]")
public class OTP {
  @SerializedName("id")
  private String id = null;

  @SerializedName("collectionRef")
  private String collectionRef = null;

  @SerializedName("recordRef")
  private String recordRef = null;

  @SerializedName("password")
  private String password = null;

  @SerializedName("sentTo")
  private String sentTo = null;

  @SerializedName("created")
  private OffsetDateTime created = null;

  @SerializedName("updated")
  private OffsetDateTime updated = null;

  /**
   * Unique identifier.
   * @return id
   **/
  @Schema(description = "Unique identifier.")
  public String getId() {
    return id;
  }

  public OTP collectionRef(String collectionRef) {
    this.collectionRef = collectionRef;
    return this;
  }

  /**
   * Collection reference.
   * @return collectionRef
   **/
  @Schema(description = "Collection reference.")
  public String getCollectionRef() {
    return collectionRef;
  }

  public void setCollectionRef(String collectionRef) {
    this.collectionRef = collectionRef;
  }

  public OTP recordRef(String recordRef) {
    this.recordRef = recordRef;
    return this;
  }

  /**
   * Record reference.
   * @return recordRef
   **/
  @Schema(description = "Record reference.")
  public String getRecordRef() {
    return recordRef;
  }

  public void setRecordRef(String recordRef) {
    this.recordRef = recordRef;
  }

  public OTP password(String password) {
    this.password = password;
    return this;
  }

  /**
   * One-time password (hashed).
   * @return password
   **/
  @Schema(description = "One-time password (hashed).")
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public OTP sentTo(String sentTo) {
    this.sentTo = sentTo;
    return this;
  }

  /**
   * Destination of the OTP.
   * @return sentTo
   **/
  @Schema(description = "Destination of the OTP.")
  public String getSentTo() {
    return sentTo;
  }

  public void setSentTo(String sentTo) {
    this.sentTo = sentTo;
  }

  /**
   * Creation timestamp.
   * @return created
   **/
  @Schema(description = "Creation timestamp.")
  public OffsetDateTime getCreated() {
    return created;
  }

  /**
   * Update timestamp.
   * @return updated
   **/
  @Schema(description = "Update timestamp.")
  public OffsetDateTime getUpdated() {
    return updated;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OTP OTP = (OTP) o;
    return Objects.equals(this.id, OTP.id)
        && Objects.equals(this.collectionRef, OTP.collectionRef)
        && Objects.equals(this.recordRef, OTP.recordRef)
        && Objects.equals(this.password, OTP.password)
        && Objects.equals(this.sentTo, OTP.sentTo)
        && Objects.equals(this.created, OTP.created)
        && Objects.equals(this.updated, OTP.updated);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, collectionRef, recordRef, password, sentTo, created, updated);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OTP {\n");

    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    collectionRef: ").append(toIndentedString(collectionRef)).append("\n");
    sb.append("    recordRef: ").append(toIndentedString(recordRef)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    sentTo: ").append(toIndentedString(sentTo)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    updated: ").append(toIndentedString(updated)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
