/*
 * ChaOffice API
 * API definition for the ChaOffice project, a distributed platform for data and communication management in small and medium-sized enterprises (SMEs).
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * Product
 */
@javax.annotation.processing.Generated(
    value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen",
    date = "2025-03-30T15:15:44.636736291Z[GMT]")
public class Product {
  @SerializedName("id")
  private String id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("price")
  private Float price = null;

  @SerializedName("quantity")
  private Float quantity = null;

  @SerializedName("image_url")
  private String imageUrl = null;

  @SerializedName("category")
  private String category = null;

  /**
   * Unique identifier for the product.
   * @return id
   **/
  @Schema(description = "Unique identifier for the product.")
  public String getId() {
    return id;
  }

  public Product name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Name of the product.
   * @return name
   **/
  @Schema(description = "Name of the product.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Product description(String description) {
    this.description = description;
    return this;
  }

  /**
   * Description of the product.
   * @return description
   **/
  @Schema(description = "Description of the product.")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Product price(Float price) {
    this.price = price;
    return this;
  }

  /**
   * Price of the product.
   * @return price
   **/
  @Schema(description = "Price of the product.")
  public Float getPrice() {
    return price;
  }

  public void setPrice(Float price) {
    this.price = price;
  }

  public Product quantity(Float quantity) {
    this.quantity = quantity;
    return this;
  }

  /**
   * Quantity of the product in stock.
   * @return quantity
   **/
  @Schema(description = "Quantity of the product in stock.")
  public Float getQuantity() {
    return quantity;
  }

  public void setQuantity(Float quantity) {
    this.quantity = quantity;
  }

  public Product imageUrl(String imageUrl) {
    this.imageUrl = imageUrl;
    return this;
  }

  /**
   * URL of the product image.
   * @return imageUrl
   **/
  @Schema(description = "URL of the product image.")
  public String getImageUrl() {
    return imageUrl;
  }

  public void setImageUrl(String imageUrl) {
    this.imageUrl = imageUrl;
  }

  public Product category(String category) {
    this.category = category;
    return this;
  }

  /**
   * ID of the category the product belongs to.
   * @return category
   **/
  @Schema(description = "ID of the category the product belongs to.")
  public String getCategory() {
    return category;
  }

  public void setCategory(String category) {
    this.category = category;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Product product = (Product) o;
    return Objects.equals(this.id, product.id)
        && Objects.equals(this.name, product.name)
        && Objects.equals(this.description, product.description)
        && Objects.equals(this.price, product.price)
        && Objects.equals(this.quantity, product.quantity)
        && Objects.equals(this.imageUrl, product.imageUrl)
        && Objects.equals(this.category, product.category);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, description, price, quantity, imageUrl, category);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Product {\n");

    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    imageUrl: ").append(toIndentedString(imageUrl)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
