// Generated by Qleany v1.5.5 from feature_use_case_uow.tera

use crate::use_cases::get_stock_history_uc::{
    GetStockHistoryUnitOfWorkFactoryTrait, GetStockHistoryUnitOfWorkTrait,
};
use anyhow::{Ok, Result};
use common::database::QueryUnitOfWork;
use common::database::{db_context::DbContext, transactions::Transaction};
#[allow(unused_imports)]
use common::entities::{Location, Product, StockMovement};
#[allow(unused_imports)]
use common::types;
#[allow(unused_imports)]
use common::types::EntityId;
use std::cell::RefCell;

// Unit of work for GetStockHistory

pub struct GetStockHistoryUnitOfWork {
    context: DbContext,
    transaction: RefCell<Option<Transaction>>,
}

impl GetStockHistoryUnitOfWork {
    pub fn new(db_context: &DbContext) -> Self {
        GetStockHistoryUnitOfWork {
            context: db_context.clone(),
            transaction: RefCell::new(None),
        }
    }
}

impl QueryUnitOfWork for GetStockHistoryUnitOfWork {
    fn begin_transaction(&self) -> Result<()> {
        self.transaction
            .replace(Some(Transaction::begin_read_transaction(&self.context)?));
        Ok(())
    }

    fn end_transaction(&self) -> Result<()> {
        self.transaction
            .take()
            .ok_or_else(|| anyhow::anyhow!("No active transaction"))?
            .end_read_transaction()?;
        Ok(())
    }
}

//TODO: adapt entities and actions to real use :
// GetRO, GetMultiRO, GetRelationshipRO, GetRelationshipsFromRightIdsRO
//
// You have here a read-only unit of work.
//
// RO means Read Only, so *RO actions should be used here.
// Do not mix read-only and write actions in the same unit of work.
//
// Exactly the same macros must be set in the use case uow trait file in ../use_cases/get_stock_history_uc.rs
//
#[macros::uow_action(entity = "StockMovement", action = "GetRO")]
#[macros::uow_action(entity = "StockMovement", action = "GetMultiRO")]
#[macros::uow_action(entity = "Product", action = "GetRO")]
#[macros::uow_action(entity = "Product", action = "GetMultiRO")]
#[macros::uow_action(entity = "Location", action = "GetRO")]
#[macros::uow_action(entity = "Location", action = "GetMultiRO")]
impl GetStockHistoryUnitOfWorkTrait for GetStockHistoryUnitOfWork {}

pub struct GetStockHistoryUnitOfWorkFactory {
    context: DbContext,
}

impl GetStockHistoryUnitOfWorkFactory {
    pub fn new(db_context: &DbContext) -> Self {
        GetStockHistoryUnitOfWorkFactory {
            context: db_context.clone(),
        }
    }
}

impl GetStockHistoryUnitOfWorkFactoryTrait for GetStockHistoryUnitOfWorkFactory {
    fn create(&self) -> Box<dyn GetStockHistoryUnitOfWorkTrait> {
        Box::new(GetStockHistoryUnitOfWork::new(&self.context))
    }
}
