// Generated by Qleany v1.5.5 from feature_dtos.tera

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct CreatePurchaseDealDto {
    pub title: String,
    pub description: String,
    pub product_id: i64,
    pub supplier_id: i64,
    pub manager_id: i64,
    pub unit_cost: f64,
    pub total_value: f64,
    pub frequency: DealFrequencyInput,
    pub start_date: chrono::DateTime<chrono::Utc>,
    pub end_date: chrono::DateTime<chrono::Utc>,
}

#[derive(Serialize, Deserialize, Default, Clone, Debug, PartialEq)]
pub enum DealFrequencyInput {
    #[default]
    OneTime,
    Weekly,
    Monthly,
    Quarterly,
    Yearly,
}
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct CreatePurchaseDealReturnDto {
    pub deal_id: i64,
}
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetDealsBySupplierDto {
    pub supplier_id: i64,
}
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct DealListDto {
    pub deal_ids: Vec<i64>,
    pub titles: Vec<String>,
}
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ActiveDealsDto {
    pub deal_ids: Vec<i64>,
    pub titles: Vec<String>,
    pub statuses: Vec<String>,
}
