// Generated by Qleany v1.5.5 from entity_controller.tera

use super::{
    dtos::{BudgetEntryDto, CreateBudgetEntryDto, UpdateBudgetEntryDto},
    units_of_work::{BudgetEntryReadUoWFactory, BudgetEntryWriteUoWFactory},
};
use crate::BudgetEntryRelationshipDto;
use anyhow::{Ok, Result};
use common::direct_access::budget_entry::BudgetEntryRelationshipField;
use common::direct_access::use_cases;

use common::{database::db_context::DbContext, event::EventHub, types::EntityId};
use std::sync::Arc;

pub fn create_orphan(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    entity: &CreateBudgetEntryDto,
) -> Result<BudgetEntryDto> {
    let uow_factory = BudgetEntryWriteUoWFactory::new(db_context, event_hub);
    let mut uc = use_cases::CreateOrphanUseCase::new(uow_factory);
    let entity_in: common::entities::BudgetEntry = entity.into();
    let result = uc.execute(&entity_in)?;
    Ok(result.into())
}

pub fn create_orphan_multi(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    entities: &[CreateBudgetEntryDto],
) -> Result<Vec<BudgetEntryDto>> {
    let uow_factory = BudgetEntryWriteUoWFactory::new(db_context, event_hub);
    let entities_in: Vec<common::entities::BudgetEntry> =
        entities.iter().map(|dto| dto.into()).collect();
    let mut uc = use_cases::CreateOrphanUseCase::new(uow_factory);
    let result = uc.execute_multi(&entities_in)?;
    Ok(result.into_iter().map(|e| e.into()).collect())
}

pub fn create(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    entity: &CreateBudgetEntryDto,
    owner_id: EntityId,
    index: i32,
) -> Result<BudgetEntryDto> {
    let uow_factory = BudgetEntryWriteUoWFactory::new(db_context, event_hub);
    let entity_in: common::entities::BudgetEntry = entity.into();
    let mut uc = use_cases::CreateUseCase::new(uow_factory);
    let result = uc.execute(&entity_in, owner_id, index)?;
    Ok(result.into())
}

pub fn create_multi(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    entities: &[CreateBudgetEntryDto],
    owner_id: EntityId,
    index: i32,
) -> Result<Vec<BudgetEntryDto>> {
    let uow_factory = BudgetEntryWriteUoWFactory::new(db_context, event_hub);
    let entities_in: Vec<common::entities::BudgetEntry> =
        entities.iter().map(|dto| dto.into()).collect();
    let mut uc = use_cases::CreateUseCase::new(uow_factory);
    let result = uc.execute_multi(&entities_in, owner_id, index)?;
    Ok(result.into_iter().map(|e| e.into()).collect())
}

pub fn get(db_context: &DbContext, id: &EntityId) -> Result<Option<BudgetEntryDto>> {
    let uow_factory = BudgetEntryReadUoWFactory::new(db_context);
    let uc = use_cases::GetUseCase::new(uow_factory);
    Ok(uc.execute(id)?.map(|e| e.into()))
}

pub fn get_all(db_context: &DbContext) -> Result<Vec<BudgetEntryDto>> {
    let uow_factory = BudgetEntryReadUoWFactory::new(db_context);
    let uc = use_cases::GetUseCase::new(uow_factory);
    Ok(uc.execute_all()?.into_iter().map(|e| e.into()).collect())
}

pub fn get_multi(db_context: &DbContext, ids: &[EntityId]) -> Result<Vec<Option<BudgetEntryDto>>> {
    let uow_factory = BudgetEntryReadUoWFactory::new(db_context);
    let uc = use_cases::GetUseCase::new(uow_factory);
    Ok(uc
        .execute_multi(ids)?
        .into_iter()
        .map(|o| o.map(|e| e.into()))
        .collect())
}

pub fn update(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    entity: &UpdateBudgetEntryDto,
) -> Result<BudgetEntryDto> {
    let uow_factory = BudgetEntryWriteUoWFactory::new(db_context, event_hub);
    let entity_in: common::entities::BudgetEntry = entity.into();
    let mut uc = use_cases::UpdateUseCase::new(uow_factory);
    let result = uc.execute(&entity_in)?;
    Ok(result.into())
}

pub fn update_multi(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    entities: &[UpdateBudgetEntryDto],
) -> Result<Vec<BudgetEntryDto>> {
    let uow_factory = BudgetEntryWriteUoWFactory::new(db_context, event_hub);
    let entities_in: Vec<common::entities::BudgetEntry> =
        entities.iter().map(|dto| dto.into()).collect();
    let mut uc = use_cases::UpdateUseCase::new(uow_factory);
    let result = uc.execute_multi(&entities_in)?;
    Ok(result.into_iter().map(|e| e.into()).collect())
}

pub fn update_with_relationships(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    entity: &BudgetEntryDto,
) -> Result<BudgetEntryDto> {
    let uow_factory = BudgetEntryWriteUoWFactory::new(db_context, event_hub);
    let entity_in: common::entities::BudgetEntry = entity.into();
    let mut uc = use_cases::UpdateWithRelationshipsUseCase::new(uow_factory);
    let result = uc.execute(&entity_in)?;
    Ok(result.into())
}

pub fn update_with_relationships_multi(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    entities: &[BudgetEntryDto],
) -> Result<Vec<BudgetEntryDto>> {
    let uow_factory = BudgetEntryWriteUoWFactory::new(db_context, event_hub);
    let entities_in: Vec<common::entities::BudgetEntry> =
        entities.iter().map(|dto| dto.into()).collect();
    let mut uc = use_cases::UpdateWithRelationshipsUseCase::new(uow_factory);
    let result = uc.execute_multi(&entities_in)?;
    Ok(result.into_iter().map(|e| e.into()).collect())
}

pub fn remove(db_context: &DbContext, event_hub: &Arc<EventHub>, id: &EntityId) -> Result<()> {
    let uow_factory = BudgetEntryWriteUoWFactory::new(db_context, event_hub);
    let mut uc = use_cases::RemoveUseCase::new(uow_factory);
    uc.execute(id)?;
    Ok(())
}

pub fn remove_multi(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    ids: &[EntityId],
) -> Result<()> {
    let uow_factory = BudgetEntryWriteUoWFactory::new(db_context, event_hub);
    let mut uc = use_cases::RemoveUseCase::new(uow_factory);
    uc.execute_multi(ids)?;
    Ok(())
}

pub fn get_relationship(
    db_context: &DbContext,
    id: &EntityId,
    field: &BudgetEntryRelationshipField,
) -> Result<Vec<EntityId>> {
    let uow_factory = BudgetEntryReadUoWFactory::new(db_context);
    let uc = use_cases::GetRelationshipUseCase::<BudgetEntryRelationshipField, _>::new(uow_factory);
    uc.execute(id, field)
}

pub fn get_relationship_many(
    db_context: &DbContext,
    ids: &[EntityId],
    field: &BudgetEntryRelationshipField,
) -> Result<std::collections::HashMap<EntityId, Vec<EntityId>>> {
    let uow_factory = BudgetEntryReadUoWFactory::new(db_context);
    let uc =
        use_cases::GetRelationshipManyUseCase::<BudgetEntryRelationshipField, _>::new(uow_factory);
    uc.execute(ids, field)
}

pub fn get_relationship_count(
    db_context: &DbContext,
    id: &EntityId,
    field: &BudgetEntryRelationshipField,
) -> Result<usize> {
    let uow_factory = BudgetEntryReadUoWFactory::new(db_context);
    let uc =
        use_cases::GetRelationshipCountUseCase::<BudgetEntryRelationshipField, _>::new(uow_factory);
    uc.execute(id, field)
}

pub fn get_relationship_in_range(
    db_context: &DbContext,
    id: &EntityId,
    field: &BudgetEntryRelationshipField,
    offset: usize,
    limit: usize,
) -> Result<Vec<EntityId>> {
    let uow_factory = BudgetEntryReadUoWFactory::new(db_context);
    let uc = use_cases::GetRelationshipInRangeUseCase::<BudgetEntryRelationshipField, _>::new(
        uow_factory,
    );
    uc.execute(id, field, offset, limit)
}

pub fn set_relationship(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    dto: &BudgetEntryRelationshipDto,
) -> Result<()> {
    let uow_factory = BudgetEntryWriteUoWFactory::new(db_context, event_hub);
    let mut uc =
        use_cases::SetRelationshipUseCase::<BudgetEntryRelationshipField, _>::new(uow_factory);
    uc.execute(&dto.id, &dto.field, dto.right_ids.as_slice())?;
    Ok(())
}

pub fn move_relationship(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    id: &EntityId,
    field: &BudgetEntryRelationshipField,
    ids_to_move: &[EntityId],
    new_index: i32,
) -> Result<Vec<EntityId>> {
    let uow_factory = BudgetEntryWriteUoWFactory::new(db_context, event_hub);
    let mut uc =
        use_cases::MoveRelationshipUseCase::<BudgetEntryRelationshipField, _>::new(uow_factory);
    let result = uc.execute(id, field, ids_to_move, new_index)?;
    Ok(result)
}
