// Generated by Qleany v1.5.5 from common_entity_table.tera

use super::location_repository::LocationTable;
use super::location_repository::LocationTableRO;
use crate::database::Postcard;
use crate::database::db_helpers;
use crate::entities::Location;
use crate::error::RepositoryError;
use crate::snapshot::{JunctionSnapshot, TableLevelSnapshot, TableSnapshot};
use crate::types::EntityId;
use redb::{ReadTransaction, ReadableTable, TableDefinition, WriteTransaction};

const LOCATION_TABLE: TableDefinition<EntityId, Postcard<Location>> =
    TableDefinition::new("location");
const COUNTER_TABLE: TableDefinition<String, EntityId> = TableDefinition::new("__counter");
// forward relationships

// backward relationships

const LOCATION_FROM_STOCK_MOVEMENT_FROM_LOCATION_JUNCTION_TABLE: TableDefinition<
    EntityId,
    Vec<EntityId>,
> = TableDefinition::new("location_from_stock_movement_from_location_junction");
const LOCATION_FROM_PRODUCT_LOCATION_JUNCTION_TABLE: TableDefinition<EntityId, Vec<EntityId>> =
    TableDefinition::new("location_from_product_location_junction");
const LOCATION_FROM_ROOT_LOCATIONS_JUNCTION_TABLE: TableDefinition<EntityId, Vec<EntityId>> =
    TableDefinition::new("location_from_root_locations_junction");
const LOCATION_FROM_STOCK_MOVEMENT_TO_LOCATION_JUNCTION_TABLE: TableDefinition<
    EntityId,
    Vec<EntityId>,
> = TableDefinition::new("location_from_stock_movement_to_location_junction");

pub struct LocationRedbTable<'a> {
    transaction: &'a WriteTransaction,
}
impl<'a> LocationRedbTable<'a> {
    pub fn new(transaction: &'a WriteTransaction) -> Self {
        LocationRedbTable { transaction }
    }

    pub fn init_tables(transaction: &WriteTransaction) -> Result<(), RepositoryError> {
        transaction.open_table(LOCATION_TABLE)?;
        transaction.open_table(COUNTER_TABLE)?;

        transaction.open_table(LOCATION_FROM_STOCK_MOVEMENT_FROM_LOCATION_JUNCTION_TABLE)?;
        transaction.open_table(LOCATION_FROM_PRODUCT_LOCATION_JUNCTION_TABLE)?;
        transaction.open_table(LOCATION_FROM_ROOT_LOCATIONS_JUNCTION_TABLE)?;
        transaction.open_table(LOCATION_FROM_STOCK_MOVEMENT_TO_LOCATION_JUNCTION_TABLE)?;
        Ok(())
    }
}

impl<'a> LocationTable for LocationRedbTable<'a> {
    fn create(&mut self, entity: &Location) -> Result<Location, RepositoryError> {
        let v = self.create_multi(std::slice::from_ref(entity))?;
        Ok(v.into_iter().next().unwrap())
    }
    fn get(&self, id: &EntityId) -> Result<Option<Location>, RepositoryError> {
        let v = self.get_multi(std::slice::from_ref(id))?;
        Ok(v.into_iter().next().unwrap())
    }
    fn update(&mut self, entity: &Location) -> Result<Location, RepositoryError> {
        let v = self.update_multi(std::slice::from_ref(entity))?;
        Ok(v.into_iter().next().unwrap())
    }
    fn update_with_relationships(
        &mut self,
        entity: &Location,
    ) -> Result<Location, RepositoryError> {
        let v = self.update_with_relationships_multi(std::slice::from_ref(entity))?;
        Ok(v.into_iter().next().unwrap())
    }
    fn remove(&mut self, id: &EntityId) -> Result<(), RepositoryError> {
        self.remove_multi(std::slice::from_ref(id))
    }

    fn create_multi(&mut self, entities: &[Location]) -> Result<Vec<Location>, RepositoryError> {
        let mut created = Vec::new();
        let mut counter_table = self.transaction.open_table(COUNTER_TABLE)?;
        let mut counter = if let Some(counter) = counter_table.get(&"location".to_string())? {
            counter.value()
        } else {
            1
        };
        let mut location_table = self.transaction.open_table(LOCATION_TABLE)?;

        for entity in entities {
            let new_entity = if entity.id == EntityId::default() {
                Location {
                    id: counter,
                    ..entity.clone()
                }
            } else {
                if location_table.get(&entity.id)?.is_some() {
                    return Err(RepositoryError::DuplicateId {
                        entity: "Location",
                        id: entity.id,
                    });
                }
                entity.clone()
            };

            location_table.insert(new_entity.id, new_entity.clone())?;

            created.push(new_entity);
            if entity.id == EntityId::default() {
                counter += 1;
            }
        }
        counter_table.insert("location".to_string(), counter)?;
        Ok(created)
    }

    fn get_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<Location>>, RepositoryError> {
        if ids.is_empty() {
            return Ok(Vec::new());
        }
        let mut list = Vec::new();
        let location_table = self.transaction.open_table(LOCATION_TABLE)?;

        for id in ids {
            let item = if let Some(guard) = location_table.get(id)? {
                let entity = guard.value().clone();
                let mut _junction_complete = true;

                if _junction_complete {
                    Some(entity)
                } else {
                    None
                }
            } else {
                None
            };
            list.push(item);
        }

        Ok(list)
    }

    fn get_all(&self) -> Result<Vec<Location>, RepositoryError> {
        let mut list = Vec::new();
        let location_table = self.transaction.open_table(LOCATION_TABLE)?;

        let mut iter = location_table.iter()?;
        while let Some(Ok((id, data))) = iter.next() {
            let _id = id.value();
            let entity = data.value().clone();
            let mut _junction_complete = true;

            if _junction_complete {
                list.push(entity);
            }
        }

        Ok(list)
    }

    // Scalar-only update: writes entity data to the main table but does NOT touch junction tables.
    // The serialized entity may contain stale/default relationship field values in the main table;
    // this is harmless because get_multi() always overlays fresh data from junction tables.
    // Use update_with_relationships_multi() to write both scalars and relationships.
    fn update_multi(&mut self, entities: &[Location]) -> Result<Vec<Location>, RepositoryError> {
        let mut location_table = self.transaction.open_table(LOCATION_TABLE)?;
        let ids: Vec<EntityId> = entities.iter().map(|e| e.id).collect();

        for entity in entities {
            location_table.insert(entity.id, entity)?;
        }
        drop(location_table);

        // Re-read entities to populate relationship fields from junction tables
        let result = self.get_multi(&ids)?;
        Ok(result.into_iter().flatten().collect())
    }

    fn update_with_relationships_multi(
        &mut self,
        entities: &[Location],
    ) -> Result<Vec<Location>, RepositoryError> {
        let mut location_table = self.transaction.open_table(LOCATION_TABLE)?;

        let ids: Vec<EntityId> = entities.iter().map(|e| e.id).collect();

        for entity in entities {
            location_table.insert(entity.id, entity)?;
        }
        drop(location_table);

        // Re-read entities to populate relationship fields from junction tables
        let result = self.get_multi(&ids)?;
        Ok(result.into_iter().flatten().collect())
    }

    fn remove_multi(&mut self, ids: &[EntityId]) -> Result<(), RepositoryError> {
        let mut location_table = self.transaction.open_table(LOCATION_TABLE)?;

        // forward relationships

        // backward relationships

        let mut backward_stock_movement_from_location_junction_table = self
            .transaction
            .open_table(LOCATION_FROM_STOCK_MOVEMENT_FROM_LOCATION_JUNCTION_TABLE)?;
        let mut backward_product_location_junction_table = self
            .transaction
            .open_table(LOCATION_FROM_PRODUCT_LOCATION_JUNCTION_TABLE)?;
        let mut backward_root_locations_junction_table = self
            .transaction
            .open_table(LOCATION_FROM_ROOT_LOCATIONS_JUNCTION_TABLE)?;
        let mut backward_stock_movement_to_location_junction_table = self
            .transaction
            .open_table(LOCATION_FROM_STOCK_MOVEMENT_TO_LOCATION_JUNCTION_TABLE)?;

        for id in ids {
            location_table.remove(id)?;

            db_helpers::delete_from_backward_junction_table(
                &mut backward_stock_movement_from_location_junction_table,
                id,
            )?;
            db_helpers::delete_from_backward_junction_table(
                &mut backward_product_location_junction_table,
                id,
            )?;
            db_helpers::delete_from_backward_junction_table(
                &mut backward_root_locations_junction_table,
                id,
            )?;
            db_helpers::delete_from_backward_junction_table(
                &mut backward_stock_movement_to_location_junction_table,
                id,
            )?;
        }
        Ok(())
    }

    fn snapshot_rows(&self, ids: &[EntityId]) -> Result<TableLevelSnapshot, RepositoryError> {
        let location_table = self.transaction.open_table(LOCATION_TABLE)?;

        // Snapshot entity rows as postcard bytes
        let mut rows = Vec::new();
        for id in ids {
            if let Some(guard) = location_table.get(id)? {
                let entity = guard.value();
                let bytes = postcard::to_allocvec(&entity)
                    .map_err(|e| RepositoryError::Serialization(e.to_string()))?;
                rows.push((*id, bytes));
            }
        }

        // Snapshot forward junction tables
        let forward_junctions = Vec::new();

        // Snapshot backward junction tables (entries that reference any of the given ids)
        let mut backward_junctions = Vec::new();

        {
            let junction_table = self
                .transaction
                .open_table(LOCATION_FROM_STOCK_MOVEMENT_FROM_LOCATION_JUNCTION_TABLE)?;
            let mut entries = Vec::new();
            let mut iter = junction_table.iter()?;
            while let Some(Ok((left_id_guard, right_ids_guard))) = iter.next() {
                let left_id = left_id_guard.value();
                let right_ids = right_ids_guard.value();
                if ids.iter().any(|id| right_ids.contains(id)) {
                    entries.push((left_id, right_ids));
                }
            }
            if !entries.is_empty() {
                backward_junctions.push(JunctionSnapshot {
                    table_name: "location_from_stock_movement_from_location_junction".to_string(),
                    entries,
                });
            }
        }
        {
            let junction_table = self
                .transaction
                .open_table(LOCATION_FROM_PRODUCT_LOCATION_JUNCTION_TABLE)?;
            let mut entries = Vec::new();
            let mut iter = junction_table.iter()?;
            while let Some(Ok((left_id_guard, right_ids_guard))) = iter.next() {
                let left_id = left_id_guard.value();
                let right_ids = right_ids_guard.value();
                if ids.iter().any(|id| right_ids.contains(id)) {
                    entries.push((left_id, right_ids));
                }
            }
            if !entries.is_empty() {
                backward_junctions.push(JunctionSnapshot {
                    table_name: "location_from_product_location_junction".to_string(),
                    entries,
                });
            }
        }
        {
            let junction_table = self
                .transaction
                .open_table(LOCATION_FROM_ROOT_LOCATIONS_JUNCTION_TABLE)?;
            let mut entries = Vec::new();
            let mut iter = junction_table.iter()?;
            while let Some(Ok((left_id_guard, right_ids_guard))) = iter.next() {
                let left_id = left_id_guard.value();
                let right_ids = right_ids_guard.value();
                if ids.iter().any(|id| right_ids.contains(id)) {
                    entries.push((left_id, right_ids));
                }
            }
            if !entries.is_empty() {
                backward_junctions.push(JunctionSnapshot {
                    table_name: "location_from_root_locations_junction".to_string(),
                    entries,
                });
            }
        }
        {
            let junction_table = self
                .transaction
                .open_table(LOCATION_FROM_STOCK_MOVEMENT_TO_LOCATION_JUNCTION_TABLE)?;
            let mut entries = Vec::new();
            let mut iter = junction_table.iter()?;
            while let Some(Ok((left_id_guard, right_ids_guard))) = iter.next() {
                let left_id = left_id_guard.value();
                let right_ids = right_ids_guard.value();
                if ids.iter().any(|id| right_ids.contains(id)) {
                    entries.push((left_id, right_ids));
                }
            }
            if !entries.is_empty() {
                backward_junctions.push(JunctionSnapshot {
                    table_name: "location_from_stock_movement_to_location_junction".to_string(),
                    entries,
                });
            }
        }

        Ok(TableLevelSnapshot {
            entity_rows: TableSnapshot {
                table_name: "location".to_string(),
                rows,
            },
            forward_junctions,
            backward_junctions,
        })
    }

    fn restore_rows(&mut self, snap: &TableLevelSnapshot) -> Result<(), RepositoryError> {
        let mut location_table = self.transaction.open_table(LOCATION_TABLE)?;

        // Restore entity rows from postcard bytes (redb insert is upsert)
        for (id, bytes) in &snap.entity_rows.rows {
            let entity: Location = postcard::from_bytes(bytes)
                .map_err(|e| RepositoryError::Serialization(e.to_string()))?;
            location_table.insert(*id, entity)?;
        }

        // Restore forward junction entries

        // Restore backward junction entries

        {
            let mut junction_table = self
                .transaction
                .open_table(LOCATION_FROM_STOCK_MOVEMENT_FROM_LOCATION_JUNCTION_TABLE)?;
            for junction_snap in &snap.backward_junctions {
                if junction_snap.table_name == "location_from_stock_movement_from_location_junction"
                {
                    for (left_id, right_ids) in &junction_snap.entries {
                        junction_table.insert(*left_id, right_ids.clone())?;
                    }
                }
            }
        }
        {
            let mut junction_table = self
                .transaction
                .open_table(LOCATION_FROM_PRODUCT_LOCATION_JUNCTION_TABLE)?;
            for junction_snap in &snap.backward_junctions {
                if junction_snap.table_name == "location_from_product_location_junction" {
                    for (left_id, right_ids) in &junction_snap.entries {
                        junction_table.insert(*left_id, right_ids.clone())?;
                    }
                }
            }
        }
        {
            let mut junction_table = self
                .transaction
                .open_table(LOCATION_FROM_ROOT_LOCATIONS_JUNCTION_TABLE)?;
            for junction_snap in &snap.backward_junctions {
                if junction_snap.table_name == "location_from_root_locations_junction" {
                    for (left_id, right_ids) in &junction_snap.entries {
                        junction_table.insert(*left_id, right_ids.clone())?;
                    }
                }
            }
        }
        {
            let mut junction_table = self
                .transaction
                .open_table(LOCATION_FROM_STOCK_MOVEMENT_TO_LOCATION_JUNCTION_TABLE)?;
            for junction_snap in &snap.backward_junctions {
                if junction_snap.table_name == "location_from_stock_movement_to_location_junction" {
                    for (left_id, right_ids) in &junction_snap.entries {
                        junction_table.insert(*left_id, right_ids.clone())?;
                    }
                }
            }
        }

        Ok(())
    }
}

pub struct LocationRedbTableRO<'a> {
    transaction: &'a ReadTransaction,
}
impl<'a> LocationRedbTableRO<'a> {
    pub fn new(transaction: &'a ReadTransaction) -> Self {
        LocationRedbTableRO { transaction }
    }
}

impl<'a> LocationTableRO for LocationRedbTableRO<'a> {
    fn get(&self, id: &EntityId) -> Result<Option<Location>, RepositoryError> {
        let v = self.get_multi(std::slice::from_ref(id))?;
        Ok(v.into_iter().next().unwrap())
    }

    fn get_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<Location>>, RepositoryError> {
        if ids.is_empty() {
            return Ok(Vec::new());
        }
        let mut list = Vec::new();
        let location_table = self.transaction.open_table(LOCATION_TABLE)?;

        for id in ids {
            let item = if let Some(guard) = location_table.get(id)? {
                let entity = guard.value().clone();
                let mut _junction_complete = true;

                if _junction_complete {
                    Some(entity)
                } else {
                    None
                }
            } else {
                None
            };
            list.push(item);
        }

        Ok(list)
    }

    fn get_all(&self) -> Result<Vec<Location>, RepositoryError> {
        let mut list = Vec::new();
        let location_table = self.transaction.open_table(LOCATION_TABLE)?;

        let mut iter = location_table.iter()?;
        while let Some(Ok((id, data))) = iter.next() {
            let _id = id.value();
            let entity = data.value().clone();
            let mut _junction_complete = true;

            if _junction_complete {
                list.push(entity);
            }
        }

        Ok(list)
    }
}
