// This file is @generated by prost-build.
/// Inventory
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AddPurchaseRequest {
    #[prost(string, tag = "1")]
    pub material_id: ::prost::alloc::string::String,
    #[prost(double, tag = "2")]
    pub quantity: f64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeductMaterialsRequest {
    #[prost(map = "string, double", tag = "1")]
    pub deductions: ::std::collections::HashMap<::prost::alloc::string::String, f64>,
}
/// Recipes
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateRecipeRequest {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub finished_good_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub ingredients: ::prost::alloc::vec::Vec<super::models::RecipeIngredient>,
}
/// Production
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecuteProductionRequest {
    #[prost(string, tag = "1")]
    pub recipe_id: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub quantity: i32,
    #[prost(string, tag = "3")]
    pub chef_id: ::prost::alloc::string::String,
}
/// Sales
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateSaleRequest {
    #[prost(string, tag = "1")]
    pub customer_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub line_items: ::prost::alloc::vec::Vec<super::models::SaleLineItem>,
    #[prost(double, tag = "3")]
    pub amount_paid: f64,
    #[prost(string, tag = "4")]
    pub wallet_id: ::prost::alloc::string::String,
}
/// Wallets
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransferFundsRequest {
    #[prost(string, tag = "1")]
    pub source_wallet_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub destination_wallet_id: ::prost::alloc::string::String,
    #[prost(double, tag = "3")]
    pub amount: f64,
}
/// Debt
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RecordPaymentRequest {
    #[prost(string, tag = "1")]
    pub customer_id: ::prost::alloc::string::String,
    #[prost(double, tag = "2")]
    pub amount: f64,
    #[prost(string, tag = "3")]
    pub wallet_id: ::prost::alloc::string::String,
}
/// Expenses
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RecordExpenseRequest {
    #[prost(string, tag = "1")]
    pub description: ::prost::alloc::string::String,
    #[prost(double, tag = "2")]
    pub amount: f64,
    #[prost(enumeration = "super::models::ExpenseCategory", tag = "3")]
    pub category: i32,
    #[prost(string, tag = "4")]
    pub wallet_id: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub recorded_by: ::prost::alloc::string::String,
}
/// Reports
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DateRangeRequest {
    #[prost(message, optional, tag = "1")]
    pub start_date: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "2")]
    pub end_date: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct InventoryReportRequest {
    #[prost(double, tag = "1")]
    pub low_stock_threshold: f64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FinancialSummary {
    #[prost(double, tag = "1")]
    pub total_revenue: f64,
    #[prost(double, tag = "2")]
    pub total_expenses: f64,
    #[prost(double, tag = "3")]
    pub net_profit: f64,
    #[prost(message, repeated, tag = "4")]
    pub wallet_balances: ::prost::alloc::vec::Vec<super::models::Wallet>,
    #[prost(message, optional, tag = "5")]
    pub start_date: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "6")]
    pub end_date: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Invoice {
    #[prost(string, tag = "1")]
    pub business_name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub customer_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub customer_city: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub customer_mobile: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "5")]
    pub line_items: ::prost::alloc::vec::Vec<super::models::SaleLineItem>,
    #[prost(double, tag = "6")]
    pub total_amount: f64,
    #[prost(double, tag = "7")]
    pub amount_paid: f64,
    #[prost(double, tag = "8")]
    pub remaining_balance: f64,
    #[prost(string, tag = "9")]
    pub date: ::prost::alloc::string::String,
    #[prost(string, tag = "10")]
    pub invoice_number: ::prost::alloc::string::String,
}
