// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AppUser {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub full_name: ::prost::alloc::string::String,
    #[prost(enumeration = "UserRole", tag = "4")]
    pub role: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RawMaterial {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub unit: ::prost::alloc::string::String,
    #[prost(double, tag = "4")]
    pub current_quantity: f64,
    #[prost(message, optional, tag = "5")]
    pub last_updated: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FinishedGood {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(double, tag = "3")]
    pub current_quantity: f64,
    #[prost(double, tag = "4")]
    pub unit_price: f64,
    #[prost(message, optional, tag = "5")]
    pub last_updated: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RecipeIngredient {
    #[prost(string, tag = "1")]
    pub raw_material_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub raw_material_name: ::prost::alloc::string::String,
    #[prost(double, tag = "3")]
    pub required_quantity: f64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Recipe {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub finished_good_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub finished_good_name: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "5")]
    pub ingredients: ::prost::alloc::vec::Vec<RecipeIngredient>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProductionLog {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub recipe_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub recipe_name: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub chef_id: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub chef_name: ::prost::alloc::string::String,
    #[prost(int32, tag = "6")]
    pub production_quantity: i32,
    #[prost(map = "string, double", tag = "7")]
    pub materials_consumed: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        f64,
    >,
    #[prost(string, tag = "8")]
    pub finished_good_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "9")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Customer {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub city: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub mobile: ::prost::alloc::string::String,
    #[prost(int32, tag = "5")]
    pub reliability_rating: i32,
    #[prost(double, tag = "6")]
    pub total_debt: f64,
    #[prost(int32, tag = "7")]
    pub overdue_days: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SaleLineItem {
    #[prost(string, tag = "1")]
    pub finished_good_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub finished_good_name: ::prost::alloc::string::String,
    #[prost(int32, tag = "3")]
    pub quantity: i32,
    #[prost(double, tag = "4")]
    pub unit_price: f64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Sale {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub customer_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub customer_name: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "4")]
    pub line_items: ::prost::alloc::vec::Vec<SaleLineItem>,
    #[prost(double, tag = "5")]
    pub total_amount: f64,
    #[prost(double, tag = "6")]
    pub amount_paid: f64,
    #[prost(string, tag = "7")]
    pub payment_wallet_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "8")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Wallet {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(enumeration = "WalletType", tag = "3")]
    pub wallet_type: i32,
    #[prost(double, tag = "4")]
    pub current_balance: f64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WalletTransaction {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub wallet_id: ::prost::alloc::string::String,
    #[prost(double, tag = "3")]
    pub amount: f64,
    #[prost(string, tag = "4")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub related_entity_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "6")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DebtRecord {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub customer_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub customer_name: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub sale_id: ::prost::alloc::string::String,
    #[prost(double, tag = "5")]
    pub original_amount: f64,
    #[prost(double, tag = "6")]
    pub remaining_amount: f64,
    #[prost(message, optional, tag = "7")]
    pub sale_date: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(int32, tag = "8")]
    pub overdue_days: i32,
    #[prost(bool, tag = "9")]
    pub is_critical: bool,
    #[prost(bool, tag = "10")]
    pub is_settled: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Expense {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub description: ::prost::alloc::string::String,
    #[prost(double, tag = "3")]
    pub amount: f64,
    #[prost(enumeration = "ExpenseCategory", tag = "4")]
    pub category: i32,
    #[prost(string, tag = "5")]
    pub wallet_id: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub wallet_name: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub recorded_by: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "8")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SyncQueueItem {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub entity_type: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub entity_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub operation: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub payload: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "6")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(enumeration = "SyncStatus", tag = "7")]
    pub status: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConflictLog {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub entity_type: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub entity_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub local_version: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub remote_version: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub resolved_with: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "7")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum UserRole {
    Unspecified = 0,
    Admin = 1,
    Chef = 2,
    Representative = 3,
}
impl UserRole {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "USER_ROLE_UNSPECIFIED",
            Self::Admin => "USER_ROLE_ADMIN",
            Self::Chef => "USER_ROLE_CHEF",
            Self::Representative => "USER_ROLE_REPRESENTATIVE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "USER_ROLE_UNSPECIFIED" => Some(Self::Unspecified),
            "USER_ROLE_ADMIN" => Some(Self::Admin),
            "USER_ROLE_CHEF" => Some(Self::Chef),
            "USER_ROLE_REPRESENTATIVE" => Some(Self::Representative),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum WalletType {
    Unspecified = 0,
    Bank = 1,
    Cash = 2,
    Representative = 3,
}
impl WalletType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "WALLET_TYPE_UNSPECIFIED",
            Self::Bank => "WALLET_TYPE_BANK",
            Self::Cash => "WALLET_TYPE_CASH",
            Self::Representative => "WALLET_TYPE_REPRESENTATIVE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "WALLET_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "WALLET_TYPE_BANK" => Some(Self::Bank),
            "WALLET_TYPE_CASH" => Some(Self::Cash),
            "WALLET_TYPE_REPRESENTATIVE" => Some(Self::Representative),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ExpenseCategory {
    Unspecified = 0,
    Purchase = 1,
    OperatingCost = 2,
}
impl ExpenseCategory {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "EXPENSE_CATEGORY_UNSPECIFIED",
            Self::Purchase => "EXPENSE_CATEGORY_PURCHASE",
            Self::OperatingCost => "EXPENSE_CATEGORY_OPERATING_COST",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "EXPENSE_CATEGORY_UNSPECIFIED" => Some(Self::Unspecified),
            "EXPENSE_CATEGORY_PURCHASE" => Some(Self::Purchase),
            "EXPENSE_CATEGORY_OPERATING_COST" => Some(Self::OperatingCost),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SyncStatus {
    Unspecified = 0,
    Synced = 1,
    Pending = 2,
    Conflict = 3,
}
impl SyncStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "SYNC_STATUS_UNSPECIFIED",
            Self::Synced => "SYNC_STATUS_SYNCED",
            Self::Pending => "SYNC_STATUS_PENDING",
            Self::Conflict => "SYNC_STATUS_CONFLICT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SYNC_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "SYNC_STATUS_SYNCED" => Some(Self::Synced),
            "SYNC_STATUS_PENDING" => Some(Self::Pending),
            "SYNC_STATUS_CONFLICT" => Some(Self::Conflict),
            _ => None,
        }
    }
}
