// Generated by Qleany v1.5.5 from common_direct_access_mod.tera

pub mod budget_entry;
pub mod category;
pub mod contact;
pub mod deal;
pub mod location;
pub mod person;
pub mod product;
pub mod repository_factory;
pub mod root;
pub mod session;
pub(crate) mod setup;
pub mod stock_movement;
pub mod use_cases;
pub mod user;
