// Generated by Qleany v1.5.5 from common_entities.tera

use crate::types::EntityId;
use crate::types::HasId;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Root {
    pub id: EntityId,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
    pub products: Vec<EntityId>,
    pub categories: Vec<EntityId>,
    pub persons: Vec<EntityId>,
    pub locations: Vec<EntityId>,
    pub deals: Vec<EntityId>,
    pub users: Vec<EntityId>,
    pub stock_movements: Vec<EntityId>,
    pub budget_entries: Vec<EntityId>,
}

impl HasId for Root {
    fn id(&self) -> EntityId {
        self.id
    }
}

#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct User {
    pub id: EntityId,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
    pub username: String,
    pub password_hash: String,
    pub display_name: String,
    pub role: UserRole,
    pub is_active: bool,
    pub person: Option<EntityId>,
    pub session: Option<EntityId>,
}

impl HasId for User {
    fn id(&self) -> EntityId {
        self.id
    }
}
#[derive(Serialize, Deserialize, Default, Clone, Debug, PartialEq)]
pub enum UserRole {
    #[default]
    Admin,
    Manager,
    Operator,
    Viewer,
}

#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Session {
    pub id: EntityId,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
    pub token: String,
    pub expires_at: chrono::DateTime<chrono::Utc>,
}

impl HasId for Session {
    fn id(&self) -> EntityId {
        self.id
    }
}

#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct StockMovement {
    pub id: EntityId,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
    pub movement_type: MovementType,
    pub quantity: i64,
    pub note: String,
    pub product: Option<EntityId>,
    pub from_location: Option<EntityId>,
    pub to_location: Option<EntityId>,
    pub performed_by: Option<EntityId>,
}

impl HasId for StockMovement {
    fn id(&self) -> EntityId {
        self.id
    }
}
#[derive(Serialize, Deserialize, Default, Clone, Debug, PartialEq)]
pub enum MovementType {
    #[default]
    Inbound,
    Outbound,
    Transfer,
    Adjustment,
    Return,
}

#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct BudgetEntry {
    pub id: EntityId,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
    pub entry_type: BudgetEntryType,
    pub amount: f64,
    pub description: String,
    pub entry_date: chrono::DateTime<chrono::Utc>,
    pub product: Option<EntityId>,
    pub deal: Option<EntityId>,
    pub recorded_by: Option<EntityId>,
}

impl HasId for BudgetEntry {
    fn id(&self) -> EntityId {
        self.id
    }
}
#[derive(Serialize, Deserialize, Default, Clone, Debug, PartialEq)]
pub enum BudgetEntryType {
    #[default]
    Purchase,
    Sale,
    Expense,
    Forecast,
}

#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Product {
    pub id: EntityId,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
    pub name: String,
    pub reference: String,
    pub description: String,
    pub quantity: i64,
    pub price_unit: f64,
    pub status: ProductStatus,
    pub category: Option<EntityId>,
    pub supplier: Option<EntityId>,
    pub location: Option<EntityId>,
}

impl HasId for Product {
    fn id(&self) -> EntityId {
        self.id
    }
}
#[derive(Serialize, Deserialize, Default, Clone, Debug, PartialEq)]
pub enum ProductStatus {
    #[default]
    Available,
    OutOfStock,
    Discontinued,
    Reserved,
}

#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Category {
    pub id: EntityId,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
    pub name: String,
    pub description: String,
    pub parent_category: Option<EntityId>,
    pub subcategories: Vec<EntityId>,
}

impl HasId for Category {
    fn id(&self) -> EntityId {
        self.id
    }
}

#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Person {
    pub id: EntityId,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
    pub name: String,
    pub role: PersonRole,
    pub contact: Option<EntityId>,
}

impl HasId for Person {
    fn id(&self) -> EntityId {
        self.id
    }
}
#[derive(Serialize, Deserialize, Default, Clone, Debug, PartialEq)]
pub enum PersonRole {
    #[default]
    Manager,
    Supplier,
}

#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Contact {
    pub id: EntityId,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
    pub phone: String,
    pub email: String,
}

impl HasId for Contact {
    fn id(&self) -> EntityId {
        self.id
    }
}

#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Deal {
    pub id: EntityId,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
    pub title: String,
    pub description: String,
    pub unit_cost: f64,
    pub total_value: f64,
    pub start_date: chrono::DateTime<chrono::Utc>,
    pub end_date: chrono::DateTime<chrono::Utc>,
    pub frequency: DealFrequency,
    pub status: DealStatus,
    pub product: Option<EntityId>,
    pub supplier: Option<EntityId>,
    pub manager: Option<EntityId>,
}

impl HasId for Deal {
    fn id(&self) -> EntityId {
        self.id
    }
}
#[derive(Serialize, Deserialize, Default, Clone, Debug, PartialEq)]
pub enum DealFrequency {
    #[default]
    OneTime,
    Weekly,
    Monthly,
    Quarterly,
    Yearly,
}
#[derive(Serialize, Deserialize, Default, Clone, Debug, PartialEq)]
pub enum DealStatus {
    #[default]
    Draft,
    Active,
    Completed,
    Cancelled,
}

#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Location {
    pub id: EntityId,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
    pub name: String,
    pub address: String,
    pub latitude: f64,
    pub longitude: f64,
    pub capacity: i64,
}

impl HasId for Location {
    fn id(&self) -> EntityId {
        self.id
    }
}
