// Generated by Qleany v1.5.5 from common_entity_table.tera

use super::root_repository::RootRelationshipField;
use super::root_repository::RootTable;
use super::root_repository::RootTableRO;
use crate::database::Postcard;
use crate::entities::Root;
use crate::error::RepositoryError;
use crate::snapshot::{JunctionSnapshot, TableLevelSnapshot, TableSnapshot};
use crate::types::EntityId;
use redb::{ReadTransaction, ReadableTable, TableDefinition, WriteTransaction};

const ROOT_TABLE: TableDefinition<EntityId, Postcard<Root>> = TableDefinition::new("root");
const COUNTER_TABLE: TableDefinition<String, EntityId> = TableDefinition::new("__counter");
// forward relationships

const BUDGET_ENTRY_FROM_ROOT_BUDGET_ENTRIES_JUNCTION_TABLE: TableDefinition<
    EntityId,
    Vec<EntityId>,
> = TableDefinition::new("budget_entry_from_root_budget_entries_junction");
const CATEGORY_FROM_ROOT_CATEGORIES_JUNCTION_TABLE: TableDefinition<EntityId, Vec<EntityId>> =
    TableDefinition::new("category_from_root_categories_junction");
const DEAL_FROM_ROOT_DEALS_JUNCTION_TABLE: TableDefinition<EntityId, Vec<EntityId>> =
    TableDefinition::new("deal_from_root_deals_junction");
const LOCATION_FROM_ROOT_LOCATIONS_JUNCTION_TABLE: TableDefinition<EntityId, Vec<EntityId>> =
    TableDefinition::new("location_from_root_locations_junction");
const PERSON_FROM_ROOT_PERSONS_JUNCTION_TABLE: TableDefinition<EntityId, Vec<EntityId>> =
    TableDefinition::new("person_from_root_persons_junction");
const PRODUCT_FROM_ROOT_PRODUCTS_JUNCTION_TABLE: TableDefinition<EntityId, Vec<EntityId>> =
    TableDefinition::new("product_from_root_products_junction");
const STOCK_MOVEMENT_FROM_ROOT_STOCK_MOVEMENTS_JUNCTION_TABLE: TableDefinition<
    EntityId,
    Vec<EntityId>,
> = TableDefinition::new("stock_movement_from_root_stock_movements_junction");
const USER_FROM_ROOT_USERS_JUNCTION_TABLE: TableDefinition<EntityId, Vec<EntityId>> =
    TableDefinition::new("user_from_root_users_junction");
// backward relationships

fn get_junction_table_definition(
    field: &'_ RootRelationshipField,
) -> TableDefinition<'_, EntityId, Vec<EntityId>> {
    match field {
        RootRelationshipField::BudgetEntries => {
            BUDGET_ENTRY_FROM_ROOT_BUDGET_ENTRIES_JUNCTION_TABLE
        }
        RootRelationshipField::Categories => CATEGORY_FROM_ROOT_CATEGORIES_JUNCTION_TABLE,
        RootRelationshipField::Deals => DEAL_FROM_ROOT_DEALS_JUNCTION_TABLE,
        RootRelationshipField::Locations => LOCATION_FROM_ROOT_LOCATIONS_JUNCTION_TABLE,
        RootRelationshipField::Persons => PERSON_FROM_ROOT_PERSONS_JUNCTION_TABLE,
        RootRelationshipField::Products => PRODUCT_FROM_ROOT_PRODUCTS_JUNCTION_TABLE,
        RootRelationshipField::StockMovements => {
            STOCK_MOVEMENT_FROM_ROOT_STOCK_MOVEMENTS_JUNCTION_TABLE
        }
        RootRelationshipField::Users => USER_FROM_ROOT_USERS_JUNCTION_TABLE,
    }
}

pub struct RootRedbTable<'a> {
    transaction: &'a WriteTransaction,
}
impl<'a> RootRedbTable<'a> {
    pub fn new(transaction: &'a WriteTransaction) -> Self {
        RootRedbTable { transaction }
    }

    pub fn init_tables(transaction: &WriteTransaction) -> Result<(), RepositoryError> {
        transaction.open_table(ROOT_TABLE)?;
        transaction.open_table(COUNTER_TABLE)?;

        transaction.open_table(BUDGET_ENTRY_FROM_ROOT_BUDGET_ENTRIES_JUNCTION_TABLE)?;
        transaction.open_table(CATEGORY_FROM_ROOT_CATEGORIES_JUNCTION_TABLE)?;
        transaction.open_table(DEAL_FROM_ROOT_DEALS_JUNCTION_TABLE)?;
        transaction.open_table(LOCATION_FROM_ROOT_LOCATIONS_JUNCTION_TABLE)?;
        transaction.open_table(PERSON_FROM_ROOT_PERSONS_JUNCTION_TABLE)?;
        transaction.open_table(PRODUCT_FROM_ROOT_PRODUCTS_JUNCTION_TABLE)?;
        transaction.open_table(STOCK_MOVEMENT_FROM_ROOT_STOCK_MOVEMENTS_JUNCTION_TABLE)?;
        transaction.open_table(USER_FROM_ROOT_USERS_JUNCTION_TABLE)?;

        Ok(())
    }
}

impl<'a> RootTable for RootRedbTable<'a> {
    fn create(&mut self, entity: &Root) -> Result<Root, RepositoryError> {
        let v = self.create_multi(std::slice::from_ref(entity))?;
        Ok(v.into_iter().next().unwrap())
    }
    fn get(&self, id: &EntityId) -> Result<Option<Root>, RepositoryError> {
        let v = self.get_multi(std::slice::from_ref(id))?;
        Ok(v.into_iter().next().unwrap())
    }
    fn update(&mut self, entity: &Root) -> Result<Root, RepositoryError> {
        let v = self.update_multi(std::slice::from_ref(entity))?;
        Ok(v.into_iter().next().unwrap())
    }
    fn update_with_relationships(&mut self, entity: &Root) -> Result<Root, RepositoryError> {
        let v = self.update_with_relationships_multi(std::slice::from_ref(entity))?;
        Ok(v.into_iter().next().unwrap())
    }
    fn remove(&mut self, id: &EntityId) -> Result<(), RepositoryError> {
        self.remove_multi(std::slice::from_ref(id))
    }

    fn create_multi(&mut self, entities: &[Root]) -> Result<Vec<Root>, RepositoryError> {
        let mut created = Vec::new();
        let mut counter_table = self.transaction.open_table(COUNTER_TABLE)?;
        let mut counter = if let Some(counter) = counter_table.get(&"root".to_string())? {
            counter.value()
        } else {
            1
        };
        let mut root_table = self.transaction.open_table(ROOT_TABLE)?;

        let mut budget_entries_junction_table = self
            .transaction
            .open_table(BUDGET_ENTRY_FROM_ROOT_BUDGET_ENTRIES_JUNCTION_TABLE)?;
        let mut categories_junction_table = self
            .transaction
            .open_table(CATEGORY_FROM_ROOT_CATEGORIES_JUNCTION_TABLE)?;
        let mut deals_junction_table = self
            .transaction
            .open_table(DEAL_FROM_ROOT_DEALS_JUNCTION_TABLE)?;
        let mut locations_junction_table = self
            .transaction
            .open_table(LOCATION_FROM_ROOT_LOCATIONS_JUNCTION_TABLE)?;
        let mut persons_junction_table = self
            .transaction
            .open_table(PERSON_FROM_ROOT_PERSONS_JUNCTION_TABLE)?;
        let mut products_junction_table = self
            .transaction
            .open_table(PRODUCT_FROM_ROOT_PRODUCTS_JUNCTION_TABLE)?;
        let mut stock_movements_junction_table = self
            .transaction
            .open_table(STOCK_MOVEMENT_FROM_ROOT_STOCK_MOVEMENTS_JUNCTION_TABLE)?;
        let mut users_junction_table = self
            .transaction
            .open_table(USER_FROM_ROOT_USERS_JUNCTION_TABLE)?;

        for entity in entities {
            let new_entity = if entity.id == EntityId::default() {
                Root {
                    id: counter,
                    ..entity.clone()
                }
            } else {
                if root_table.get(&entity.id)?.is_some() {
                    return Err(RepositoryError::DuplicateId {
                        entity: "Root",
                        id: entity.id,
                    });
                }
                entity.clone()
            };

            root_table.insert(new_entity.id, new_entity.clone())?;

            budget_entries_junction_table
                .insert(new_entity.id, new_entity.budget_entries.clone())?;
            categories_junction_table.insert(new_entity.id, new_entity.categories.clone())?;
            deals_junction_table.insert(new_entity.id, new_entity.deals.clone())?;
            locations_junction_table.insert(new_entity.id, new_entity.locations.clone())?;
            persons_junction_table.insert(new_entity.id, new_entity.persons.clone())?;
            products_junction_table.insert(new_entity.id, new_entity.products.clone())?;
            stock_movements_junction_table
                .insert(new_entity.id, new_entity.stock_movements.clone())?;
            users_junction_table.insert(new_entity.id, new_entity.users.clone())?;
            created.push(new_entity);
            if entity.id == EntityId::default() {
                counter += 1;
            }
        }
        counter_table.insert("root".to_string(), counter)?;
        Ok(created)
    }

    fn get_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<Root>>, RepositoryError> {
        if ids.is_empty() {
            return Ok(Vec::new());
        }
        let mut list = Vec::new();
        let root_table = self.transaction.open_table(ROOT_TABLE)?;

        let budget_entries_junction_table = self
            .transaction
            .open_table(BUDGET_ENTRY_FROM_ROOT_BUDGET_ENTRIES_JUNCTION_TABLE)?;
        let categories_junction_table = self
            .transaction
            .open_table(CATEGORY_FROM_ROOT_CATEGORIES_JUNCTION_TABLE)?;
        let deals_junction_table = self
            .transaction
            .open_table(DEAL_FROM_ROOT_DEALS_JUNCTION_TABLE)?;
        let locations_junction_table = self
            .transaction
            .open_table(LOCATION_FROM_ROOT_LOCATIONS_JUNCTION_TABLE)?;
        let persons_junction_table = self
            .transaction
            .open_table(PERSON_FROM_ROOT_PERSONS_JUNCTION_TABLE)?;
        let products_junction_table = self
            .transaction
            .open_table(PRODUCT_FROM_ROOT_PRODUCTS_JUNCTION_TABLE)?;
        let stock_movements_junction_table = self
            .transaction
            .open_table(STOCK_MOVEMENT_FROM_ROOT_STOCK_MOVEMENTS_JUNCTION_TABLE)?;
        let users_junction_table = self
            .transaction
            .open_table(USER_FROM_ROOT_USERS_JUNCTION_TABLE)?;

        for id in ids {
            let item = if let Some(guard) = root_table.get(id)? {
                let mut entity = guard.value().clone();
                let mut _junction_complete = true;

                // get products from junction table
                let fetched_products = products_junction_table
                    .get(id)?
                    .map(|g| g.value().clone())
                    .unwrap_or_default();
                entity.products = fetched_products;
                // get categories from junction table
                let fetched_categories = categories_junction_table
                    .get(id)?
                    .map(|g| g.value().clone())
                    .unwrap_or_default();
                entity.categories = fetched_categories;
                // get persons from junction table
                let fetched_persons = persons_junction_table
                    .get(id)?
                    .map(|g| g.value().clone())
                    .unwrap_or_default();
                entity.persons = fetched_persons;
                // get locations from junction table
                let fetched_locations = locations_junction_table
                    .get(id)?
                    .map(|g| g.value().clone())
                    .unwrap_or_default();
                entity.locations = fetched_locations;
                // get deals from junction table
                let fetched_deals = deals_junction_table
                    .get(id)?
                    .map(|g| g.value().clone())
                    .unwrap_or_default();
                entity.deals = fetched_deals;
                // get users from junction table
                let fetched_users = users_junction_table
                    .get(id)?
                    .map(|g| g.value().clone())
                    .unwrap_or_default();
                entity.users = fetched_users;
                // get stock_movements from junction table
                let fetched_stock_movements = stock_movements_junction_table
                    .get(id)?
                    .map(|g| g.value().clone())
                    .unwrap_or_default();
                entity.stock_movements = fetched_stock_movements;
                // get budget_entries from junction table
                let fetched_budget_entries = budget_entries_junction_table
                    .get(id)?
                    .map(|g| g.value().clone())
                    .unwrap_or_default();
                entity.budget_entries = fetched_budget_entries;
                if _junction_complete {
                    Some(entity)
                } else {
                    None
                }
            } else {
                None
            };
            list.push(item);
        }

        Ok(list)
    }

    fn get_all(&self) -> Result<Vec<Root>, RepositoryError> {
        let mut list = Vec::new();
        let root_table = self.transaction.open_table(ROOT_TABLE)?;

        let budget_entries_junction_table = self
            .transaction
            .open_table(BUDGET_ENTRY_FROM_ROOT_BUDGET_ENTRIES_JUNCTION_TABLE)?;
        let categories_junction_table = self
            .transaction
            .open_table(CATEGORY_FROM_ROOT_CATEGORIES_JUNCTION_TABLE)?;
        let deals_junction_table = self
            .transaction
            .open_table(DEAL_FROM_ROOT_DEALS_JUNCTION_TABLE)?;
        let locations_junction_table = self
            .transaction
            .open_table(LOCATION_FROM_ROOT_LOCATIONS_JUNCTION_TABLE)?;
        let persons_junction_table = self
            .transaction
            .open_table(PERSON_FROM_ROOT_PERSONS_JUNCTION_TABLE)?;
        let products_junction_table = self
            .transaction
            .open_table(PRODUCT_FROM_ROOT_PRODUCTS_JUNCTION_TABLE)?;
        let stock_movements_junction_table = self
            .transaction
            .open_table(STOCK_MOVEMENT_FROM_ROOT_STOCK_MOVEMENTS_JUNCTION_TABLE)?;
        let users_junction_table = self
            .transaction
            .open_table(USER_FROM_ROOT_USERS_JUNCTION_TABLE)?;

        let mut iter = root_table.iter()?;
        while let Some(Ok((id, data))) = iter.next() {
            let id = id.value();
            let mut entity = data.value().clone();
            let mut _junction_complete = true;

            // get products from junction table
            let fetched_products = products_junction_table
                .get(&id)?
                .map(|g| g.value().clone())
                .unwrap_or_default();
            entity.products = fetched_products;
            // get categories from junction table
            let fetched_categories = categories_junction_table
                .get(&id)?
                .map(|g| g.value().clone())
                .unwrap_or_default();
            entity.categories = fetched_categories;
            // get persons from junction table
            let fetched_persons = persons_junction_table
                .get(&id)?
                .map(|g| g.value().clone())
                .unwrap_or_default();
            entity.persons = fetched_persons;
            // get locations from junction table
            let fetched_locations = locations_junction_table
                .get(&id)?
                .map(|g| g.value().clone())
                .unwrap_or_default();
            entity.locations = fetched_locations;
            // get deals from junction table
            let fetched_deals = deals_junction_table
                .get(&id)?
                .map(|g| g.value().clone())
                .unwrap_or_default();
            entity.deals = fetched_deals;
            // get users from junction table
            let fetched_users = users_junction_table
                .get(&id)?
                .map(|g| g.value().clone())
                .unwrap_or_default();
            entity.users = fetched_users;
            // get stock_movements from junction table
            let fetched_stock_movements = stock_movements_junction_table
                .get(&id)?
                .map(|g| g.value().clone())
                .unwrap_or_default();
            entity.stock_movements = fetched_stock_movements;
            // get budget_entries from junction table
            let fetched_budget_entries = budget_entries_junction_table
                .get(&id)?
                .map(|g| g.value().clone())
                .unwrap_or_default();
            entity.budget_entries = fetched_budget_entries;

            if _junction_complete {
                list.push(entity);
            }
        }

        Ok(list)
    }

    // Scalar-only update: writes entity data to the main table but does NOT touch junction tables.
    // The serialized entity may contain stale/default relationship field values in the main table;
    // this is harmless because get_multi() always overlays fresh data from junction tables.
    // Use update_with_relationships_multi() to write both scalars and relationships.
    fn update_multi(&mut self, entities: &[Root]) -> Result<Vec<Root>, RepositoryError> {
        let mut root_table = self.transaction.open_table(ROOT_TABLE)?;
        let ids: Vec<EntityId> = entities.iter().map(|e| e.id).collect();

        for entity in entities {
            root_table.insert(entity.id, entity)?;
        }
        drop(root_table);

        // Re-read entities to populate relationship fields from junction tables
        let result = self.get_multi(&ids)?;
        Ok(result.into_iter().flatten().collect())
    }

    fn update_with_relationships_multi(
        &mut self,
        entities: &[Root],
    ) -> Result<Vec<Root>, RepositoryError> {
        let mut root_table = self.transaction.open_table(ROOT_TABLE)?;

        let mut budget_entries_junction_table = self
            .transaction
            .open_table(BUDGET_ENTRY_FROM_ROOT_BUDGET_ENTRIES_JUNCTION_TABLE)?;
        let mut categories_junction_table = self
            .transaction
            .open_table(CATEGORY_FROM_ROOT_CATEGORIES_JUNCTION_TABLE)?;
        let mut deals_junction_table = self
            .transaction
            .open_table(DEAL_FROM_ROOT_DEALS_JUNCTION_TABLE)?;
        let mut locations_junction_table = self
            .transaction
            .open_table(LOCATION_FROM_ROOT_LOCATIONS_JUNCTION_TABLE)?;
        let mut persons_junction_table = self
            .transaction
            .open_table(PERSON_FROM_ROOT_PERSONS_JUNCTION_TABLE)?;
        let mut products_junction_table = self
            .transaction
            .open_table(PRODUCT_FROM_ROOT_PRODUCTS_JUNCTION_TABLE)?;
        let mut stock_movements_junction_table = self
            .transaction
            .open_table(STOCK_MOVEMENT_FROM_ROOT_STOCK_MOVEMENTS_JUNCTION_TABLE)?;
        let mut users_junction_table = self
            .transaction
            .open_table(USER_FROM_ROOT_USERS_JUNCTION_TABLE)?;
        let ids: Vec<EntityId> = entities.iter().map(|e| e.id).collect();

        for entity in entities {
            root_table.insert(entity.id, entity)?;

            products_junction_table.insert(entity.id, entity.products.clone())?;
            categories_junction_table.insert(entity.id, entity.categories.clone())?;
            persons_junction_table.insert(entity.id, entity.persons.clone())?;
            locations_junction_table.insert(entity.id, entity.locations.clone())?;
            deals_junction_table.insert(entity.id, entity.deals.clone())?;
            users_junction_table.insert(entity.id, entity.users.clone())?;
            stock_movements_junction_table.insert(entity.id, entity.stock_movements.clone())?;
            budget_entries_junction_table.insert(entity.id, entity.budget_entries.clone())?;
        }
        drop(root_table);
        drop(budget_entries_junction_table);
        drop(categories_junction_table);
        drop(deals_junction_table);
        drop(locations_junction_table);
        drop(persons_junction_table);
        drop(products_junction_table);
        drop(stock_movements_junction_table);
        drop(users_junction_table);

        // Re-read entities to populate relationship fields from junction tables
        let result = self.get_multi(&ids)?;
        Ok(result.into_iter().flatten().collect())
    }

    fn remove_multi(&mut self, ids: &[EntityId]) -> Result<(), RepositoryError> {
        let mut root_table = self.transaction.open_table(ROOT_TABLE)?;

        // forward relationships

        let mut budget_entries_junction_table = self
            .transaction
            .open_table(BUDGET_ENTRY_FROM_ROOT_BUDGET_ENTRIES_JUNCTION_TABLE)?;
        let mut categories_junction_table = self
            .transaction
            .open_table(CATEGORY_FROM_ROOT_CATEGORIES_JUNCTION_TABLE)?;
        let mut deals_junction_table = self
            .transaction
            .open_table(DEAL_FROM_ROOT_DEALS_JUNCTION_TABLE)?;
        let mut locations_junction_table = self
            .transaction
            .open_table(LOCATION_FROM_ROOT_LOCATIONS_JUNCTION_TABLE)?;
        let mut persons_junction_table = self
            .transaction
            .open_table(PERSON_FROM_ROOT_PERSONS_JUNCTION_TABLE)?;
        let mut products_junction_table = self
            .transaction
            .open_table(PRODUCT_FROM_ROOT_PRODUCTS_JUNCTION_TABLE)?;
        let mut stock_movements_junction_table = self
            .transaction
            .open_table(STOCK_MOVEMENT_FROM_ROOT_STOCK_MOVEMENTS_JUNCTION_TABLE)?;
        let mut users_junction_table = self
            .transaction
            .open_table(USER_FROM_ROOT_USERS_JUNCTION_TABLE)?;

        // backward relationships

        for id in ids {
            root_table.remove(id)?;

            products_junction_table.remove(id)?;
            categories_junction_table.remove(id)?;
            persons_junction_table.remove(id)?;
            locations_junction_table.remove(id)?;
            deals_junction_table.remove(id)?;
            users_junction_table.remove(id)?;
            stock_movements_junction_table.remove(id)?;
            budget_entries_junction_table.remove(id)?;
        }
        Ok(())
    }
    fn get_relationship(
        &self,
        id: &EntityId,
        field: &RootRelationshipField,
    ) -> Result<Vec<EntityId>, RepositoryError> {
        let table = self
            .transaction
            .open_table(get_junction_table_definition(field))?;
        let guard = table.get(id)?;
        Ok(guard.map(|g| g.value().clone()).unwrap_or_default())
    }

    fn get_relationship_many(
        &self,
        ids: &[EntityId],
        field: &RootRelationshipField,
    ) -> Result<std::collections::HashMap<EntityId, Vec<EntityId>>, RepositoryError> {
        let table = self
            .transaction
            .open_table(get_junction_table_definition(field))?;
        let mut map = std::collections::HashMap::new();
        for id in ids {
            let right_ids = table
                .get(id)?
                .map(|g| g.value().clone())
                .unwrap_or_default();
            map.insert(*id, right_ids);
        }
        Ok(map)
    }

    fn get_relationship_count(
        &self,
        id: &EntityId,
        field: &RootRelationshipField,
    ) -> Result<usize, RepositoryError> {
        let table = self
            .transaction
            .open_table(get_junction_table_definition(field))?;
        Ok(table.get(id)?.map(|g| g.value().len()).unwrap_or(0))
    }

    fn get_relationship_in_range(
        &self,
        id: &EntityId,
        field: &RootRelationshipField,
        offset: usize,
        limit: usize,
    ) -> Result<Vec<EntityId>, RepositoryError> {
        let table = self
            .transaction
            .open_table(get_junction_table_definition(field))?;
        let all = table
            .get(id)?
            .map(|g| g.value().clone())
            .unwrap_or_default();
        Ok(all.into_iter().skip(offset).take(limit).collect())
    }

    fn get_relationships_from_right_ids(
        &self,
        field: &RootRelationshipField,
        right_ids: &[EntityId],
    ) -> Result<Vec<(EntityId, Vec<EntityId>)>, RepositoryError> {
        let table = self
            .transaction
            .open_table(get_junction_table_definition(field))?;
        let mut iter = table.iter()?;
        let mut rels = vec![];
        while let Some(Ok((left_id, right_entities))) = iter.next() {
            let left_id = left_id.value();
            let right_entities = right_entities.value();
            if right_ids.iter().any(|eid| right_entities.contains(eid)) {
                rels.push((left_id, right_entities));
            }
        }
        Ok(rels)
    }

    fn set_relationship_multi(
        &mut self,
        field: &RootRelationshipField,
        relationships: Vec<(EntityId, Vec<EntityId>)>,
    ) -> Result<(), RepositoryError> {
        let mut table = self
            .transaction
            .open_table(get_junction_table_definition(field))?;
        for (left_id, entities) in relationships {
            table.insert(left_id, entities)?;
        }
        Ok(())
    }

    fn set_relationship(
        &mut self,
        id: &EntityId,
        field: &RootRelationshipField,
        right_ids: &[EntityId],
    ) -> Result<(), RepositoryError> {
        let mut table = self
            .transaction
            .open_table(get_junction_table_definition(field))?;
        table.insert(*id, right_ids.to_vec())?;
        Ok(())
    }

    fn move_relationship_ids(
        &mut self,
        id: &EntityId,
        field: &RootRelationshipField,
        ids_to_move: &[EntityId],
        new_index: i32,
    ) -> Result<Vec<EntityId>, RepositoryError> {
        if ids_to_move.is_empty() {
            return self.get_relationship(id, field);
        }
        let current_ids = self.get_relationship(id, field)?;
        let move_set: std::collections::HashSet<EntityId> = ids_to_move.iter().copied().collect();
        let mut remaining: Vec<EntityId> = current_ids
            .into_iter()
            .filter(|eid| !move_set.contains(eid))
            .collect();
        let insert_pos = if new_index < 0 || (new_index as usize) > remaining.len() {
            remaining.len()
        } else {
            new_index as usize
        };
        for (i, &eid) in ids_to_move.iter().enumerate() {
            remaining.insert(insert_pos + i, eid);
        }
        let mut table = self
            .transaction
            .open_table(get_junction_table_definition(field))?;
        table.insert(*id, remaining.clone())?;
        Ok(remaining)
    }

    fn snapshot_rows(&self, ids: &[EntityId]) -> Result<TableLevelSnapshot, RepositoryError> {
        let root_table = self.transaction.open_table(ROOT_TABLE)?;

        // Snapshot entity rows as postcard bytes
        let mut rows = Vec::new();
        for id in ids {
            if let Some(guard) = root_table.get(id)? {
                let entity = guard.value();
                let bytes = postcard::to_allocvec(&entity)
                    .map_err(|e| RepositoryError::Serialization(e.to_string()))?;
                rows.push((*id, bytes));
            }
        }

        // Snapshot forward junction tables
        let mut forward_junctions = Vec::new();

        {
            let junction_table = self
                .transaction
                .open_table(BUDGET_ENTRY_FROM_ROOT_BUDGET_ENTRIES_JUNCTION_TABLE)?;
            let mut entries = Vec::new();
            for id in ids {
                if let Some(guard) = junction_table.get(id)? {
                    entries.push((*id, guard.value().clone()));
                }
            }
            forward_junctions.push(JunctionSnapshot {
                table_name: "budget_entry_from_root_budget_entries_junction".to_string(),
                entries,
            });
        }
        {
            let junction_table = self
                .transaction
                .open_table(CATEGORY_FROM_ROOT_CATEGORIES_JUNCTION_TABLE)?;
            let mut entries = Vec::new();
            for id in ids {
                if let Some(guard) = junction_table.get(id)? {
                    entries.push((*id, guard.value().clone()));
                }
            }
            forward_junctions.push(JunctionSnapshot {
                table_name: "category_from_root_categories_junction".to_string(),
                entries,
            });
        }
        {
            let junction_table = self
                .transaction
                .open_table(DEAL_FROM_ROOT_DEALS_JUNCTION_TABLE)?;
            let mut entries = Vec::new();
            for id in ids {
                if let Some(guard) = junction_table.get(id)? {
                    entries.push((*id, guard.value().clone()));
                }
            }
            forward_junctions.push(JunctionSnapshot {
                table_name: "deal_from_root_deals_junction".to_string(),
                entries,
            });
        }
        {
            let junction_table = self
                .transaction
                .open_table(LOCATION_FROM_ROOT_LOCATIONS_JUNCTION_TABLE)?;
            let mut entries = Vec::new();
            for id in ids {
                if let Some(guard) = junction_table.get(id)? {
                    entries.push((*id, guard.value().clone()));
                }
            }
            forward_junctions.push(JunctionSnapshot {
                table_name: "location_from_root_locations_junction".to_string(),
                entries,
            });
        }
        {
            let junction_table = self
                .transaction
                .open_table(PERSON_FROM_ROOT_PERSONS_JUNCTION_TABLE)?;
            let mut entries = Vec::new();
            for id in ids {
                if let Some(guard) = junction_table.get(id)? {
                    entries.push((*id, guard.value().clone()));
                }
            }
            forward_junctions.push(JunctionSnapshot {
                table_name: "person_from_root_persons_junction".to_string(),
                entries,
            });
        }
        {
            let junction_table = self
                .transaction
                .open_table(PRODUCT_FROM_ROOT_PRODUCTS_JUNCTION_TABLE)?;
            let mut entries = Vec::new();
            for id in ids {
                if let Some(guard) = junction_table.get(id)? {
                    entries.push((*id, guard.value().clone()));
                }
            }
            forward_junctions.push(JunctionSnapshot {
                table_name: "product_from_root_products_junction".to_string(),
                entries,
            });
        }
        {
            let junction_table = self
                .transaction
                .open_table(STOCK_MOVEMENT_FROM_ROOT_STOCK_MOVEMENTS_JUNCTION_TABLE)?;
            let mut entries = Vec::new();
            for id in ids {
                if let Some(guard) = junction_table.get(id)? {
                    entries.push((*id, guard.value().clone()));
                }
            }
            forward_junctions.push(JunctionSnapshot {
                table_name: "stock_movement_from_root_stock_movements_junction".to_string(),
                entries,
            });
        }
        {
            let junction_table = self
                .transaction
                .open_table(USER_FROM_ROOT_USERS_JUNCTION_TABLE)?;
            let mut entries = Vec::new();
            for id in ids {
                if let Some(guard) = junction_table.get(id)? {
                    entries.push((*id, guard.value().clone()));
                }
            }
            forward_junctions.push(JunctionSnapshot {
                table_name: "user_from_root_users_junction".to_string(),
                entries,
            });
        }

        // Snapshot backward junction tables (entries that reference any of the given ids)
        let backward_junctions = Vec::new();

        Ok(TableLevelSnapshot {
            entity_rows: TableSnapshot {
                table_name: "root".to_string(),
                rows,
            },
            forward_junctions,
            backward_junctions,
        })
    }

    fn restore_rows(&mut self, snap: &TableLevelSnapshot) -> Result<(), RepositoryError> {
        let mut root_table = self.transaction.open_table(ROOT_TABLE)?;

        // Restore entity rows from postcard bytes (redb insert is upsert)
        for (id, bytes) in &snap.entity_rows.rows {
            let entity: Root = postcard::from_bytes(bytes)
                .map_err(|e| RepositoryError::Serialization(e.to_string()))?;
            root_table.insert(*id, entity)?;
        }

        // Restore forward junction entries

        {
            let mut junction_table = self
                .transaction
                .open_table(BUDGET_ENTRY_FROM_ROOT_BUDGET_ENTRIES_JUNCTION_TABLE)?;
            for junction_snap in &snap.forward_junctions {
                if junction_snap.table_name == "budget_entry_from_root_budget_entries_junction" {
                    for (left_id, right_ids) in &junction_snap.entries {
                        junction_table.insert(*left_id, right_ids.clone())?;
                    }
                }
            }
        }
        {
            let mut junction_table = self
                .transaction
                .open_table(CATEGORY_FROM_ROOT_CATEGORIES_JUNCTION_TABLE)?;
            for junction_snap in &snap.forward_junctions {
                if junction_snap.table_name == "category_from_root_categories_junction" {
                    for (left_id, right_ids) in &junction_snap.entries {
                        junction_table.insert(*left_id, right_ids.clone())?;
                    }
                }
            }
        }
        {
            let mut junction_table = self
                .transaction
                .open_table(DEAL_FROM_ROOT_DEALS_JUNCTION_TABLE)?;
            for junction_snap in &snap.forward_junctions {
                if junction_snap.table_name == "deal_from_root_deals_junction" {
                    for (left_id, right_ids) in &junction_snap.entries {
                        junction_table.insert(*left_id, right_ids.clone())?;
                    }
                }
            }
        }
        {
            let mut junction_table = self
                .transaction
                .open_table(LOCATION_FROM_ROOT_LOCATIONS_JUNCTION_TABLE)?;
            for junction_snap in &snap.forward_junctions {
                if junction_snap.table_name == "location_from_root_locations_junction" {
                    for (left_id, right_ids) in &junction_snap.entries {
                        junction_table.insert(*left_id, right_ids.clone())?;
                    }
                }
            }
        }
        {
            let mut junction_table = self
                .transaction
                .open_table(PERSON_FROM_ROOT_PERSONS_JUNCTION_TABLE)?;
            for junction_snap in &snap.forward_junctions {
                if junction_snap.table_name == "person_from_root_persons_junction" {
                    for (left_id, right_ids) in &junction_snap.entries {
                        junction_table.insert(*left_id, right_ids.clone())?;
                    }
                }
            }
        }
        {
            let mut junction_table = self
                .transaction
                .open_table(PRODUCT_FROM_ROOT_PRODUCTS_JUNCTION_TABLE)?;
            for junction_snap in &snap.forward_junctions {
                if junction_snap.table_name == "product_from_root_products_junction" {
                    for (left_id, right_ids) in &junction_snap.entries {
                        junction_table.insert(*left_id, right_ids.clone())?;
                    }
                }
            }
        }
        {
            let mut junction_table = self
                .transaction
                .open_table(STOCK_MOVEMENT_FROM_ROOT_STOCK_MOVEMENTS_JUNCTION_TABLE)?;
            for junction_snap in &snap.forward_junctions {
                if junction_snap.table_name == "stock_movement_from_root_stock_movements_junction" {
                    for (left_id, right_ids) in &junction_snap.entries {
                        junction_table.insert(*left_id, right_ids.clone())?;
                    }
                }
            }
        }
        {
            let mut junction_table = self
                .transaction
                .open_table(USER_FROM_ROOT_USERS_JUNCTION_TABLE)?;
            for junction_snap in &snap.forward_junctions {
                if junction_snap.table_name == "user_from_root_users_junction" {
                    for (left_id, right_ids) in &junction_snap.entries {
                        junction_table.insert(*left_id, right_ids.clone())?;
                    }
                }
            }
        }

        // Restore backward junction entries

        Ok(())
    }
}

pub struct RootRedbTableRO<'a> {
    transaction: &'a ReadTransaction,
}
impl<'a> RootRedbTableRO<'a> {
    pub fn new(transaction: &'a ReadTransaction) -> Self {
        RootRedbTableRO { transaction }
    }
}

impl<'a> RootTableRO for RootRedbTableRO<'a> {
    fn get(&self, id: &EntityId) -> Result<Option<Root>, RepositoryError> {
        let v = self.get_multi(std::slice::from_ref(id))?;
        Ok(v.into_iter().next().unwrap())
    }

    fn get_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<Root>>, RepositoryError> {
        if ids.is_empty() {
            return Ok(Vec::new());
        }
        let mut list = Vec::new();
        let root_table = self.transaction.open_table(ROOT_TABLE)?;

        let budget_entries_junction_table = self
            .transaction
            .open_table(BUDGET_ENTRY_FROM_ROOT_BUDGET_ENTRIES_JUNCTION_TABLE)?;
        let categories_junction_table = self
            .transaction
            .open_table(CATEGORY_FROM_ROOT_CATEGORIES_JUNCTION_TABLE)?;
        let deals_junction_table = self
            .transaction
            .open_table(DEAL_FROM_ROOT_DEALS_JUNCTION_TABLE)?;
        let locations_junction_table = self
            .transaction
            .open_table(LOCATION_FROM_ROOT_LOCATIONS_JUNCTION_TABLE)?;
        let persons_junction_table = self
            .transaction
            .open_table(PERSON_FROM_ROOT_PERSONS_JUNCTION_TABLE)?;
        let products_junction_table = self
            .transaction
            .open_table(PRODUCT_FROM_ROOT_PRODUCTS_JUNCTION_TABLE)?;
        let stock_movements_junction_table = self
            .transaction
            .open_table(STOCK_MOVEMENT_FROM_ROOT_STOCK_MOVEMENTS_JUNCTION_TABLE)?;
        let users_junction_table = self
            .transaction
            .open_table(USER_FROM_ROOT_USERS_JUNCTION_TABLE)?;

        for id in ids {
            let item = if let Some(guard) = root_table.get(id)? {
                let mut entity = guard.value().clone();
                let mut _junction_complete = true;

                // get products from junction table
                let fetched_products = products_junction_table
                    .get(id)?
                    .map(|g| g.value().clone())
                    .unwrap_or_default();
                entity.products = fetched_products;
                // get categories from junction table
                let fetched_categories = categories_junction_table
                    .get(id)?
                    .map(|g| g.value().clone())
                    .unwrap_or_default();
                entity.categories = fetched_categories;
                // get persons from junction table
                let fetched_persons = persons_junction_table
                    .get(id)?
                    .map(|g| g.value().clone())
                    .unwrap_or_default();
                entity.persons = fetched_persons;
                // get locations from junction table
                let fetched_locations = locations_junction_table
                    .get(id)?
                    .map(|g| g.value().clone())
                    .unwrap_or_default();
                entity.locations = fetched_locations;
                // get deals from junction table
                let fetched_deals = deals_junction_table
                    .get(id)?
                    .map(|g| g.value().clone())
                    .unwrap_or_default();
                entity.deals = fetched_deals;
                // get users from junction table
                let fetched_users = users_junction_table
                    .get(id)?
                    .map(|g| g.value().clone())
                    .unwrap_or_default();
                entity.users = fetched_users;
                // get stock_movements from junction table
                let fetched_stock_movements = stock_movements_junction_table
                    .get(id)?
                    .map(|g| g.value().clone())
                    .unwrap_or_default();
                entity.stock_movements = fetched_stock_movements;
                // get budget_entries from junction table
                let fetched_budget_entries = budget_entries_junction_table
                    .get(id)?
                    .map(|g| g.value().clone())
                    .unwrap_or_default();
                entity.budget_entries = fetched_budget_entries;
                if _junction_complete {
                    Some(entity)
                } else {
                    None
                }
            } else {
                None
            };
            list.push(item);
        }

        Ok(list)
    }

    fn get_all(&self) -> Result<Vec<Root>, RepositoryError> {
        let mut list = Vec::new();
        let root_table = self.transaction.open_table(ROOT_TABLE)?;

        let budget_entries_junction_table = self
            .transaction
            .open_table(BUDGET_ENTRY_FROM_ROOT_BUDGET_ENTRIES_JUNCTION_TABLE)?;
        let categories_junction_table = self
            .transaction
            .open_table(CATEGORY_FROM_ROOT_CATEGORIES_JUNCTION_TABLE)?;
        let deals_junction_table = self
            .transaction
            .open_table(DEAL_FROM_ROOT_DEALS_JUNCTION_TABLE)?;
        let locations_junction_table = self
            .transaction
            .open_table(LOCATION_FROM_ROOT_LOCATIONS_JUNCTION_TABLE)?;
        let persons_junction_table = self
            .transaction
            .open_table(PERSON_FROM_ROOT_PERSONS_JUNCTION_TABLE)?;
        let products_junction_table = self
            .transaction
            .open_table(PRODUCT_FROM_ROOT_PRODUCTS_JUNCTION_TABLE)?;
        let stock_movements_junction_table = self
            .transaction
            .open_table(STOCK_MOVEMENT_FROM_ROOT_STOCK_MOVEMENTS_JUNCTION_TABLE)?;
        let users_junction_table = self
            .transaction
            .open_table(USER_FROM_ROOT_USERS_JUNCTION_TABLE)?;

        let mut iter = root_table.iter()?;
        while let Some(Ok((id, data))) = iter.next() {
            let id = id.value();
            let mut entity = data.value().clone();
            let mut _junction_complete = true;

            // get products from junction table
            let fetched_products = products_junction_table
                .get(&id)?
                .map(|g| g.value().clone())
                .unwrap_or_default();
            entity.products = fetched_products;
            // get categories from junction table
            let fetched_categories = categories_junction_table
                .get(&id)?
                .map(|g| g.value().clone())
                .unwrap_or_default();
            entity.categories = fetched_categories;
            // get persons from junction table
            let fetched_persons = persons_junction_table
                .get(&id)?
                .map(|g| g.value().clone())
                .unwrap_or_default();
            entity.persons = fetched_persons;
            // get locations from junction table
            let fetched_locations = locations_junction_table
                .get(&id)?
                .map(|g| g.value().clone())
                .unwrap_or_default();
            entity.locations = fetched_locations;
            // get deals from junction table
            let fetched_deals = deals_junction_table
                .get(&id)?
                .map(|g| g.value().clone())
                .unwrap_or_default();
            entity.deals = fetched_deals;
            // get users from junction table
            let fetched_users = users_junction_table
                .get(&id)?
                .map(|g| g.value().clone())
                .unwrap_or_default();
            entity.users = fetched_users;
            // get stock_movements from junction table
            let fetched_stock_movements = stock_movements_junction_table
                .get(&id)?
                .map(|g| g.value().clone())
                .unwrap_or_default();
            entity.stock_movements = fetched_stock_movements;
            // get budget_entries from junction table
            let fetched_budget_entries = budget_entries_junction_table
                .get(&id)?
                .map(|g| g.value().clone())
                .unwrap_or_default();
            entity.budget_entries = fetched_budget_entries;

            if _junction_complete {
                list.push(entity);
            }
        }

        Ok(list)
    }
    fn get_relationship(
        &self,
        id: &EntityId,
        field: &RootRelationshipField,
    ) -> Result<Vec<EntityId>, RepositoryError> {
        let table = self
            .transaction
            .open_table(get_junction_table_definition(field))?;
        let guard = table.get(id)?;
        Ok(guard.map(|g| g.value().clone()).unwrap_or_default())
    }

    fn get_relationship_many(
        &self,
        ids: &[EntityId],
        field: &RootRelationshipField,
    ) -> Result<std::collections::HashMap<EntityId, Vec<EntityId>>, RepositoryError> {
        let table = self
            .transaction
            .open_table(get_junction_table_definition(field))?;
        let mut map = std::collections::HashMap::new();
        for id in ids {
            let right_ids = table
                .get(id)?
                .map(|g| g.value().clone())
                .unwrap_or_default();
            map.insert(*id, right_ids);
        }
        Ok(map)
    }

    fn get_relationship_count(
        &self,
        id: &EntityId,
        field: &RootRelationshipField,
    ) -> Result<usize, RepositoryError> {
        let table = self
            .transaction
            .open_table(get_junction_table_definition(field))?;
        Ok(table.get(id)?.map(|g| g.value().len()).unwrap_or(0))
    }

    fn get_relationship_in_range(
        &self,
        id: &EntityId,
        field: &RootRelationshipField,
        offset: usize,
        limit: usize,
    ) -> Result<Vec<EntityId>, RepositoryError> {
        let table = self
            .transaction
            .open_table(get_junction_table_definition(field))?;
        let all = table
            .get(id)?
            .map(|g| g.value().clone())
            .unwrap_or_default();
        Ok(all.into_iter().skip(offset).take(limit).collect())
    }

    fn get_relationships_from_right_ids(
        &self,
        field: &RootRelationshipField,
        right_ids: &[EntityId],
    ) -> Result<Vec<(EntityId, Vec<EntityId>)>, RepositoryError> {
        let table = self
            .transaction
            .open_table(get_junction_table_definition(field))?;
        let mut iter = table.iter()?;
        let mut rels = vec![];
        while let Some(Ok((left_id, right_entities))) = iter.next() {
            let left_id = left_id.value();
            let right_entities = right_entities.value();
            if right_ids.iter().any(|eid| right_entities.contains(eid)) {
                rels.push((left_id, right_entities));
            }
        }
        Ok(rels)
    }
}
