// Generated by Qleany v1.5.5 from feature_use_case.tera
use crate::FindNearestLocationsDto;
use crate::NearestLocationsDto;
use anyhow::Result;
use common::database::QueryUnitOfWork;
use common::entities::Location;
use common::types::EntityId;

pub trait FindNearestLocationsUnitOfWorkFactoryTrait: Send + Sync {
    fn create(&self) -> Box<dyn FindNearestLocationsUnitOfWorkTrait>;
}

// Exactly the same macros must be set in the use case uow trait file in ../units_of_work/find_nearest_locations_uow.rs
#[macros::uow_action(entity = "Location", action = "GetRO")]
#[macros::uow_action(entity = "Location", action = "GetMultiRO")]
#[macros::uow_action(entity = "Location", action = "GetAllRO")]
pub trait FindNearestLocationsUnitOfWorkTrait: QueryUnitOfWork {}

/// Haversine distance in kilometers between two lat/lon points.
fn haversine_km(lat1: f64, lon1: f64, lat2: f64, lon2: f64) -> f64 {
    const R: f64 = 6371.0; // Earth radius in km
    let d_lat = (lat2 - lat1).to_radians();
    let d_lon = (lon2 - lon1).to_radians();
    let a = (d_lat / 2.0).sin().powi(2)
        + lat1.to_radians().cos() * lat2.to_radians().cos() * (d_lon / 2.0).sin().powi(2);
    let c = 2.0 * a.sqrt().asin();
    R * c
}

pub struct FindNearestLocationsUseCase {
    uow_factory: Box<dyn FindNearestLocationsUnitOfWorkFactoryTrait>,
}

impl FindNearestLocationsUseCase {
    pub fn new(uow_factory: Box<dyn FindNearestLocationsUnitOfWorkFactoryTrait>) -> Self {
        FindNearestLocationsUseCase { uow_factory }
    }

    pub fn execute(&mut self, dto: &FindNearestLocationsDto) -> Result<NearestLocationsDto> {
        let uow = self.uow_factory.create();
        uow.begin_transaction()?;

        // 1. Get all locations
        let locations = uow.get_all_location()?;

        // 2. Compute distance from query point to each location
        let mut with_distance: Vec<(&Location, f64)> = locations
            .iter()
            .map(|loc| {
                let dist = haversine_km(dto.latitude, dto.longitude, loc.latitude, loc.longitude);
                (loc, dist)
            })
            .collect();

        // 3. Sort by distance
        with_distance.sort_by(|a, b| a.1.partial_cmp(&b.1).unwrap_or(std::cmp::Ordering::Equal));

        // 4. Take max_results
        let max = dto.max_results.max(0) as usize;
        let results = &with_distance[..max.min(with_distance.len())];

        let mut location_ids = Vec::with_capacity(results.len());
        let mut names = Vec::with_capacity(results.len());
        let mut distances_km = Vec::with_capacity(results.len());

        for (loc, dist) in results {
            location_ids.push(loc.id as i64);
            names.push(loc.name.clone());
            distances_km.push(*dist);
        }

        uow.end_transaction()?;

        Ok(NearestLocationsDto {
            location_ids,
            names,
            distances_km,
        })
    }
}
