// Generated by Qleany v1.5.5 from feature_dtos.tera

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateUserDto {
    pub username: String,
    pub password: String,
    pub display_name: String,
    pub role: CreateUserRole,
    pub person_id: i64,
}

#[derive(Serialize, Deserialize, Default, Clone, Debug, PartialEq)]
pub enum CreateUserRole {
    #[default]
    Admin,
    Manager,
    Operator,
    Viewer,
}
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateUserResultDto {
    pub user_id: i64,
}
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct DeactivateUserDto {
    pub user_id: i64,
}
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct UserListDto {
    pub user_ids: Vec<i64>,
    pub usernames: Vec<String>,
    pub display_names: Vec<String>,
    pub roles: Vec<String>,
    pub is_active: Vec<bool>,
}
